import {
  BadgeCategory,
  BadgeDefinition,
  BadgeTier,
} from "@/types/badges";

export const BADGE_TIER_COLORS: Record<BadgeTier, string> = {
  bronze: "#B87333",
  silver: "#A7B0BE",
  gold: "#F2B84B",
  platinum: "#8B6CFF",
};

export const BADGE_CATEGORY_COLORS: Record<BadgeCategory, string> = {
  posting: "#346BFF",
  likes: "#E7476E",
  comments: "#28A879",
  shares: "#9B5DE5",
  community: "#F18F01",
};

export const BADGE_CATEGORY_LABELS: Record<BadgeCategory, string> = {
  posting: "Posting",
  likes: "Likes",
  comments: "Comments",
  shares: "Shares",
  community: "Community",
};

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  {
    id: "posting-first-take",
    name: "First Take",
    description: "Create your first forum post.",
    category: "posting",
    metric: "postsCreated",
    tier: "bronze",
    threshold: 1,
    symbol: "✍️",
    sortOrder: 1,
  },
  {
    id: "posting-contributor",
    name: "Contributor",
    description: "Create 10 forum posts.",
    category: "posting",
    metric: "postsCreated",
    tier: "silver",
    threshold: 10,
    symbol: "✍️",
    sortOrder: 2,
  },
  {
    id: "posting-columnist",
    name: "Columnist",
    description: "Create 50 forum posts.",
    category: "posting",
    metric: "postsCreated",
    tier: "gold",
    threshold: 50,
    symbol: "📰",
    sortOrder: 3,
  },
  {
    id: "posting-franchise-voice",
    name: "Franchise Voice",
    description: "Create 250 forum posts.",
    category: "posting",
    metric: "postsCreated",
    tier: "platinum",
    threshold: 250,
    symbol: "🎙️",
    sortOrder: 4,
  },

  {
    id: "likes-crowd-pleaser",
    name: "Crowd Pleaser",
    description: "Receive 10 likes on your posts.",
    category: "likes",
    metric: "likesReceived",
    tier: "bronze",
    threshold: 10,
    symbol: "❤️",
    sortOrder: 5,
  },
  {
    id: "likes-fan-favorite",
    name: "Fan Favorite",
    description: "Receive 100 likes on your posts.",
    category: "likes",
    metric: "likesReceived",
    tier: "silver",
    threshold: 100,
    symbol: "❤️",
    sortOrder: 6,
  },
  {
    id: "likes-headliner",
    name: "Headliner",
    description: "Receive 500 likes on your posts.",
    category: "likes",
    metric: "likesReceived",
    tier: "gold",
    threshold: 500,
    symbol: "🌟",
    sortOrder: 7,
  },
  {
    id: "likes-community-icon",
    name: "Community Icon",
    description: "Receive 2,000 likes on your posts.",
    category: "likes",
    metric: "likesReceived",
    tier: "platinum",
    threshold: 2000,
    symbol: "👑",
    sortOrder: 8,
  },

  {
    id: "comments-conversation-starter",
    name: "Conversation Starter",
    description: "Receive 10 comments on your posts.",
    category: "comments",
    metric: "commentsReceived",
    tier: "bronze",
    threshold: 10,
    symbol: "💬",
    sortOrder: 9,
  },
  {
    id: "comments-debate-captain",
    name: "Debate Captain",
    description: "Receive 100 comments on your posts.",
    category: "comments",
    metric: "commentsReceived",
    tier: "silver",
    threshold: 100,
    symbol: "🗣️",
    sortOrder: 10,
  },
  {
    id: "comments-community-analyst",
    name: "Community Analyst",
    description: "Receive 500 comments on your posts.",
    category: "comments",
    metric: "commentsReceived",
    tier: "gold",
    threshold: 500,
    symbol: "📊",
    sortOrder: 11,
  },
  {
    id: "comments-floor-general",
    name: "Floor General",
    description: "Receive 2,000 comments on your posts.",
    category: "comments",
    metric: "commentsReceived",
    tier: "platinum",
    threshold: 2000,
    symbol: "🏀",
    sortOrder: 12,
  },

  {
    id: "shares-worth-sharing",
    name: "Worth Sharing",
    description: "Have your posts shared 5 times.",
    category: "shares",
    metric: "sharesReceived",
    tier: "bronze",
    threshold: 5,
    symbol: "🔁",
    sortOrder: 13,
  },
  {
    id: "shares-viral-spark",
    name: "Viral Spark",
    description: "Have your posts shared 50 times.",
    category: "shares",
    metric: "sharesReceived",
    tier: "silver",
    threshold: 50,
    symbol: "⚡",
    sortOrder: 14,
  },
  {
    id: "shares-trendsetter",
    name: "Trendsetter",
    description: "Have your posts shared 250 times.",
    category: "shares",
    metric: "sharesReceived",
    tier: "gold",
    threshold: 250,
    symbol: "📈",
    sortOrder: 15,
  },
  {
    id: "shares-broadcast-legend",
    name: "Broadcast Legend",
    description: "Have your posts shared 1,000 times.",
    category: "shares",
    metric: "sharesReceived",
    tier: "platinum",
    threshold: 1000,
    symbol: "📡",
    sortOrder: 16,
  },

  {
    id: "community-momentum",
    name: "Momentum",
    description: "Generate 50 total forum interactions.",
    category: "community",
    metric: "totalEngagement",
    tier: "bronze",
    threshold: 50,
    symbol: "🔥",
    sortOrder: 17,
  },
  {
    id: "community-playmaker",
    name: "Playmaker",
    description: "Generate 500 total forum interactions.",
    category: "community",
    metric: "totalEngagement",
    tier: "silver",
    threshold: 500,
    symbol: "⭐",
    sortOrder: 18,
  },
  {
    id: "community-all-star",
    name: "All-Star Presence",
    description: "Generate 2,500 total forum interactions.",
    category: "community",
    metric: "totalEngagement",
    tier: "gold",
    threshold: 2500,
    symbol: "🏆",
    sortOrder: 19,
  },
  {
    id: "community-mvp",
    name: "Community MVP",
    description: "Generate 10,000 total forum interactions.",
    category: "community",
    metric: "totalEngagement",
    tier: "platinum",
    threshold: 10000,
    symbol: "💎",
    sortOrder: 20,
  },
];