import MWCLogo from "assets/College_Logos/Conference_Logos/MWC.png";
import PlaceholderLogo from "assets/Placeholders/teamPlaceholder.png";
import ACCLogo from "../assets/College_Logos/Conference_Logos/ACC.png";
import AMEastLogo from "../assets/College_Logos/Conference_Logos/AmericaEast.png";
import AACLogo from "../assets/College_Logos/Conference_Logos/American.png";
import BIG12Logo from "../assets/College_Logos/Conference_Logos/Big12.png";
import BIG12Logolight from "../assets/College_Logos/Conference_Logos/BIG12Light.png";
import BIG10Logo from "../assets/College_Logos/Conference_Logos/BigTen.png";
import BIG10Logolight from "../assets/College_Logos/Conference_Logos/BIGTenLight.png";
import CAALogo from "../assets/College_Logos/Conference_Logos/CAA.png";
import CUSALogo from "../assets/College_Logos/Conference_Logos/CUSA.png";
import IvyLeagueLogo from "../assets/College_Logos/Conference_Logos/IvyLeague.png";
import MACLogo from "../assets/College_Logos/Conference_Logos/MAC.png";
import MEACLogo from "../assets/College_Logos/Conference_Logos/MEAC.png";
import MVFCLogo from "../assets/College_Logos/Conference_Logos/MVFC.png";
import NECLogo from "../assets/College_Logos/Conference_Logos/NEC.png";
import OVCLogo from "../assets/College_Logos/Conference_Logos/OVC.png";
import PatriotLeagueLogo from "../assets/College_Logos/Conference_Logos/PatriotLeague.png";
import SECLogo from "../assets/College_Logos/Conference_Logos/SEC.png";
import SLCLogo from "../assets/College_Logos/Conference_Logos/SLC.png";
import SoConLogo from "../assets/College_Logos/Conference_Logos/SoCon.png";
import SWACLogo from "../assets/College_Logos/Conference_Logos/SWAC.png";
import { Conference } from "./cfbConferences";

export const cbbConferences: Conference[] = [
  {
    id: 1,
    uid: "s:40~l:41~g:3",
    groupId: 3,
    name: "Atlantic 10 Conference",
    shortName: "A-10",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/atlantic_10.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 2,
    uid: "s:40~l:41~g:2",
    groupId: 2,
    name: "Atlantic Coast Conference",
    shortName: "ACC",
    parentGroupId: 50,
    logo: ACCLogo,
    logoLight: ACCLogo,
    color: "#013CA6",
    secondaryColor: "#A5A9AB",
  },
  {
    id: 3,
    uid: "s:40~l:41~g:1",
    groupId: 1,
    name: "America East Conference",
    shortName: "Am. East",
    parentGroupId: 50,
    logo: AMEastLogo,
    logoLight: AMEastLogo,
    color: null,
    secondaryColor: null,
  },
  {
    id: 4,
    uid: "s:40~l:41~g:62",
    groupId: 62,
    name: "American Conference",
    shortName: "American",
    parentGroupId: 50,
    logo: AACLogo,
    logoLight: AACLogo,
    color: null,
    secondaryColor: null,
  },
  {
    id: 5,
    uid: "s:40~l:41~g:46",
    groupId: 46,
    name: "ASUN Conference",
    shortName: "ASUN",
    parentGroupId: 50,
    logo: null,
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 6,
    uid: "s:40~l:41~g:8",
    groupId: 8,
    name: "Big 12 Conference",
    shortName: "Big 12",
    parentGroupId: 50,
    logo: BIG12Logo,
    logoLight: BIG12Logolight,
    color: "#C41230",
    secondaryColor: "#FFFFFF",
  },
  {
    id: 7,
    uid: "s:40~l:41~g:4",
    groupId: 4,
    name: "Big East Conference",
    shortName: "Big East",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/big_east.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 8,
    uid: "s:40~l:41~g:5",
    groupId: 5,
    name: "Big Sky Conference",
    shortName: "Big Sky",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/big_sky.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 9,
    uid: "s:40~l:41~g:6",
    groupId: 6,
    name: "Big South Conference",
    shortName: "Big South",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/big_south.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 10,
    uid: "s:40~l:41~g:7",
    groupId: 7,
    name: "Big Ten Conference",
    shortName: "Big Ten",
    parentGroupId: 50,
    logo: BIG10Logolight,
    logoLight: BIG10Logo,
    color: "#0088CE",
    secondaryColor: "#000000",
  },
  {
    id: 11,
    uid: "s:40~l:41~g:9",
    groupId: 9,
    name: "Big West Conference",
    shortName: "Big West",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/big_west.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 12,
    uid: "s:40~l:41~g:10",
    groupId: 10,
    name: "Coastal Athletic Association",
    shortName: "CAA",
    parentGroupId: 50,
    logo: CAALogo,
    logoLight: CAALogo,
    color: null,
    secondaryColor: null,
  },
  {
    id: 13,
    uid: "s:40~l:41~g:11",
    groupId: 11,
    name: "Conference USA",
    shortName: "CUSA",
    parentGroupId: 50,
    logo: CUSALogo,
    logoLight: CUSALogo,
    color: "#003865",
    secondaryColor: "#A6192E",
  },
  {
    id: 14,
    uid: "s:40~l:41~g:45",
    groupId: 45,
    name: "Horizon League",
    shortName: "Horizon",
    parentGroupId: 50,
    logo: null,
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 15,
    uid: "s:40~l:41~g:12",
    groupId: 12,
    name: "Ivy League",
    shortName: "Ivy",
    parentGroupId: 50,
    logo: IvyLeagueLogo,
    logoLight: IvyLeagueLogo,
    color: null,
    secondaryColor: null,
  },
  {
    id: 16,
    uid: "s:40~l:41~g:13",
    groupId: 13,
    name: "Metro Atlantic Athletic Conference",
    shortName: "MAAC",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/maac.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 17,
    uid: "s:40~l:41~g:14",
    groupId: 14,
    name: "Mid-American Conference",
    shortName: "MAC",
    parentGroupId: 50,
    logo: MACLogo,
    logoLight: MACLogo,
    color: "#0B213E",
    secondaryColor: "#019E4F",
  },
  {
    id: 18,
    uid: "s:40~l:41~g:16",
    groupId: 16,
    name: "Mid-Eastern Athletic Conference",
    shortName: "MEAC",
    parentGroupId: 50,
    logo: MEACLogo,
    logoLight: MEACLogo,
    color: null,
    secondaryColor: null,
  },
  {
    id: 19,
    uid: "s:40~l:41~g:44",
    groupId: 44,
    name: "Mountain West Conference",
    shortName: "Mountain West",
    parentGroupId: 50,
    logo: MWCLogo,
    logoLight: MWCLogo,
    color: "#4F2D7F",
    secondaryColor: "#AFAFAF",
  },
  {
    id: 20,
    uid: "s:40~l:41~g:18",
    groupId: 18,
    name: "Missouri Valley Conference",
    shortName: "MVC",
    parentGroupId: 50,
    logo: MVFCLogo,
    logoLight: MVFCLogo,
    color: "#003976",
    secondaryColor: "#C8102E",
  },
  {
    id: 21,
    uid: "s:40~l:41~g:19",
    groupId: 19,
    name: "Northeast Conference",
    shortName: "NEC",
    parentGroupId: 50,
    logo: NECLogo,
    logoLight: NECLogo,
    color: "#006BA3",
    secondaryColor: "#231F20",
  },
  {
    id: 22,
    uid: "s:40~l:41~g:20",
    groupId: 20,
    name: "Ohio Valley Conference",
    shortName: "OVC",
    parentGroupId: 50,
    logo: OVCLogo,
    logoLight: OVCLogo,
    color: null,
    secondaryColor: null,
  },
  {
    id: 23,
    uid: "s:40~l:41~g:22",
    groupId: 22,
    name: "Patriot League",
    shortName: "Patriot",
    parentGroupId: 50,
    logo: PatriotLeagueLogo,
    logoLight: PatriotLeagueLogo,
    color: "#25355F",
    secondaryColor: "#D72633",
  },
  {
    id: 24,
    uid: "s:40~l:41~g:23",
    groupId: 23,
    name: "Southeastern Conference",
    shortName: "SEC",
    parentGroupId: 50,
    logo: SECLogo,
    logoLight: SECLogo,
    color: "#22356B",
    secondaryColor: "#FFFFFF",
  },
  {
    id: 25,
    uid: "s:40~l:41~g:24",
    groupId: 24,
    name: "Southern Conference",
    shortName: "SoCon",
    parentGroupId: 50,
    logo: SoConLogo,
    logoLight: SoConLogo,
    color: "#001489",
    secondaryColor: "#DA291C",
  },
  {
    id: 26,
    uid: "s:40~l:41~g:25",
    groupId: 25,
    name: "Southland Conference",
    shortName: "Southland",
    parentGroupId: 50,
    logo: SLCLogo,
    logoLight: SLCLogo,
    color: "#000000",
    secondaryColor: "#C2A553",
  },
  {
    id: 27,
    uid: "s:40~l:41~g:49",
    groupId: 49,
    name: "Summit League",
    shortName: "Summit",
    parentGroupId: 50,
    logo: null,
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 28,
    uid: "s:40~l:41~g:27",
    groupId: 27,
    name: "Sun Belt Conference",
    shortName: "Sun Belt",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/sun_belt.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 29,
    uid: "s:40~l:41~g:26",
    groupId: 26,
    name: "Southwestern Athletic Conference",
    shortName: "SWAC",
    parentGroupId: 50,
    logo: SWACLogo,
    logoLight: SWACLogo,
    color: "#E01821",
    secondaryColor: "#B0B0B0",
  },
  {
    id: 30,
    uid: "s:40~l:41~g:30",
    groupId: 30,
    name: "Western Athletic Conference",
    shortName: "WAC",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/wac.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
  {
    id: 31,
    uid: "s:40~l:41~g:29",
    groupId: 29,
    name: "West Coast Conference",
    shortName: "WCC",
    parentGroupId: 50,
    logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/sml/trans/west_coast.gif",
    logoLight: null,
    color: null,
    secondaryColor: null,
  },
];

export function getCBBConferenceLogo(id: number | string, isDark: boolean) {
  const conference = cbbConferences.find(
    (t) => String(t.groupId) === String(id),
  );

  if (!conference) return PlaceholderLogo;

  return isDark ? conference.logoLight || conference.logo : conference.logo;
}
