import { BaseballTeam } from "types/baseball";

import {
  default as AngelsLogo,
  default as AngelsLogoLight,
} from "assets/Baseball/MLB_Logos/Angels.png";
import {
  default as AstrosLogo,
  default as AstrosLogoLight,
} from "assets/Baseball/MLB_Logos/Astros.png";
import AthleticsLogo from "assets/Baseball/MLB_Logos/Athletics.png";
import AthleticsLogoLight from "assets/Baseball/MLB_Logos/AthleticsLight.png";
import {
  default as BlueJaysLogo,
  default as BlueJaysLogoLight,
} from "assets/Baseball/MLB_Logos/BlueJays.png";
import BravesLogo from "assets/Baseball/MLB_Logos/Braves.png";
import BravesLogoLight from "assets/Baseball/MLB_Logos/BravesLight.png";
import {
  default as BrewersLogo,
  default as BrewersLogoLight,
} from "assets/Baseball/MLB_Logos/Brewers.png";
import CardinalsLogo from "assets/Baseball/MLB_Logos/Cardinals.png";
import CardinalsLogoLight from "assets/Baseball/MLB_Logos/CardinalsLight.png";
import {
  default as CubsLogo,
  default as CubsLogoLight,
} from "assets/Baseball/MLB_Logos/Cubs.png";
import {
  default as DiamondbacksLogo,
  default as DiamondbacksLogoLight,
} from "assets/Baseball/MLB_Logos/Diamondbacks.png";
import DodgersLogo from "assets/Baseball/MLB_Logos/Dodgers.png";
import DodgersLogoLight from "assets/Baseball/MLB_Logos/DodgersLight.png";
import {
  default as GiantsLogo,
  default as GiantsLogoLight,
} from "assets/Baseball/MLB_Logos/Giants.png";
import GuardiansLogo from "assets/Baseball/MLB_Logos/Guardians.png";
import GuardiansLogoLight from "assets/Baseball/MLB_Logos/GuardiansLight.png";
import {
  default as MarinersLogo,
  default as MarinersLogoLight,
} from "assets/Baseball/MLB_Logos/Mariners.png";
import {
  default as MarlinsLogo,
  default as MarlinsLogoLight,
} from "assets/Baseball/MLB_Logos/Marlins.png";
import {
  default as MetsLogo,
  default as MetsLogoLight,
} from "assets/Baseball/MLB_Logos/Mets.png";
import NationalsLogo from "assets/Baseball/MLB_Logos/Nationals.png";
import NationalsLogoLight from "assets/Baseball/MLB_Logos/NationalsLight.png";
import {
  default as OriolesLogo,
  default as OriolesLogoLight,
} from "assets/Baseball/MLB_Logos/Orioles.png";
import PadresLogo from "assets/Baseball/MLB_Logos/Padres.png";
import PadresLogoLight from "assets/Baseball/MLB_Logos/PadresLight.png";
import PhilliesLogo from "assets/Baseball/MLB_Logos/Phillies.png";
import PhilliesLogoLight from "assets/Baseball/MLB_Logos/PhilliesLight.png";
import {
  default as PiratesLogo,
  default as PiratesLogoLight,
} from "assets/Baseball/MLB_Logos/Pirates.png";
import RangersLogo from "assets/Baseball/MLB_Logos/Rangers.png";
import RangersLogoLight from "assets/Baseball/MLB_Logos/RangersLight.png";
import RaysLogo from "assets/Baseball/MLB_Logos/Rays.png";
import RaysLogoLight from "assets/Baseball/MLB_Logos/RaysLight.png";
import RedsLogo from "assets/Baseball/MLB_Logos/Reds.png";
import RedsLogoLight from "assets/Baseball/MLB_Logos/RedsLight.png";
import RedSoxLogo from "assets/Baseball/MLB_Logos/RedSox.png";
import RedSoxLogoLight from "assets/Baseball/MLB_Logos/RedSoxLight.png";
import RockiesLogo from "assets/Baseball/MLB_Logos/Rockies.png";
import RockiesLogoLight from "assets/Baseball/MLB_Logos/RockiesLight.png";
import RoyalsLogo from "assets/Baseball/MLB_Logos/Royals.png";
import RoyalsLogoLight from "assets/Baseball/MLB_Logos/RoyalsLight.png";
import TigersLogo from "assets/Baseball/MLB_Logos/Tigers.png";
import TigersLogoLight from "assets/Baseball/MLB_Logos/TigersLight.png";
import TwinsLogo from "assets/Baseball/MLB_Logos/Twins.png";
import TwinsLogoLight from "assets/Baseball/MLB_Logos/TwinsLight.png";
import WhiteSoxLogo from "assets/Baseball/MLB_Logos/WhiteSox.png";
import WhiteSoxLogoLight from "assets/Baseball/MLB_Logos/WhiteSoxLight.png";
import YankeesLogo from "assets/Baseball/MLB_Logos/Yankees.png";
import YankeesLogoLight from "assets/Baseball/MLB_Logos/YankeesLight.png";
import PlaceholderLogo from "../assets/Placeholders/teamPlaceholder.png";

export const mlbTeams: BaseballTeam[] = [
  {
    id: 2,
    espnId: 29,
    name: "Diamondbacks",
    shortName: "Diamondbacks",
    fullName: "Arizona Diamondbacks",
    code: "ARI",
    color: "#aa182c",
    secondaryColor: "#000000",
    logo: DiamondbacksLogo,
    logoLight: DiamondbacksLogoLight,
    established: 1998,
    latitude: 33.4455,
    longitude: -112.0667,
    venueName: "Chase Field",
    venueCapacity: "48,405",
    address: "401 E Jefferson St, Phoenix, AZ 85004",
    city: "Phoenix, AZ",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/diamondbacks.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 963,
    espnId: 11,
    name: "Athletics",
    shortName: "Athletics",
    fullName: "Oakland Athletics",
    code: "ATH",
    color: "#003831",
    secondaryColor: "#efb21e",
    logo: AthleticsLogo,
    logoLight: AthleticsLogoLight,
    established: 1901,
    latitude: 37.7516,
    longitude: -122.2005,
    venueName: "Oakland Coliseum",
    venueCapacity: "63,132",
    address: "7000 Coliseum Way, Oakland, CA 94621",
    city: "Oakland, CA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/athletics.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 3,
    espnId: 15,
    name: "Braves",
    shortName: "Braves",
    fullName: "Atlanta Braves",
    code: "ATL",
    color: "#0c2340",
    secondaryColor: "#ba0c2f",
    logo: BravesLogo,
    logoLight: BravesLogoLight,
    established: 1876,
    latitude: 33.8907,
    longitude: -84.4677,
    venueName: "Truist Park",
    venueCapacity: "41,149",
    address: "755 Battery Ave SE, Atlanta, GA 30339",
    city: "Atlanta, GA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/braves.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 4,
    espnId: 1,
    name: "Orioles",
    shortName: "Orioles",
    fullName: "Baltimore Orioles",
    code: "BAL",
    color: "#df4601",
    secondaryColor: "#000000",
    logo: OriolesLogo,
    logoLight: OriolesLogoLight,
    established: 1901,
    latitude: 39.2839,
    longitude: -76.6217,
    venueName: "Oriole Park at Camden Yards",
    venueCapacity: "45,971",
    address: "333 W Camden St, Baltimore, MD 21201",
    city: "Baltimore, MD",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/braves.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 5,
    espnId: 2,
    name: "Red Sox",
    shortName: "Red Sox",
    fullName: "Boston Red Sox",
    code: "BOS",
    color: "#0d2b56",
    secondaryColor: "#bd3039",
    logo: RedSoxLogo,
    logoLight: RedSoxLogoLight,
    established: 1901,
    latitude: 42.3465,
    longitude: -71.0972,
    venueName: "Fenway Park",
    venueCapacity: "37,755",
    address: "4 Jersey St, Boston, MA 02215",
    city: "Boston, MA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/redsox.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 6,
    espnId: 16,
    name: "Cubs",
    shortName: "Cubs",
    fullName: "Chicago Cubs",
    code: "CHC",
    color: "#0e3386",
    secondaryColor: "#cc3433",
    logo: CubsLogo,
    logoLight: CubsLogoLight,
    established: 1876,
    latitude: 41.9484,
    longitude: -87.6553,
    venueName: "Wrigley Field",
    venueCapacity: "41,649",
    address: "1060 W Addison St, Chicago, IL 60613",
    city: "Chicago, IL",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/cubs.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 7,
    espnId: 4,
    name: "White Sox",
    shortName: "White Sox",
    fullName: "Chicago White Sox",
    code: "CHW",
    color: "#000000",
    secondaryColor: "#c4ced4",
    logo: WhiteSoxLogo,
    logoLight: WhiteSoxLogoLight,
    established: 1901,
    latitude: 41.8299,
    longitude: -87.6339,
    venueName: "Guaranteed Rate Field",
    venueCapacity: "40,615",
    address: "333 W 35th St, Chicago, IL 60616",
    city: "Chicago, IL",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/whitesox.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 8,
    espnId: 17,
    name: "Reds",
    shortName: "Reds",
    fullName: "Cincinnati Reds",
    code: "CIN",
    color: "#c6011f",
    secondaryColor: "#ffffff",
    logo: RedsLogo,
    logoLight: RedsLogoLight,
    established: 1882,
    latitude: 39.097,
    longitude: -84.507,
    venueName: "Great American Ball Park",
    venueCapacity: "42,319",
    address: "100 Joe Nuxhall Way, Cincinnati, OH 45202",
    city: "Cincinnati, OH",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/reds.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 9,
    espnId: 5,
    name: "Guardians",
    shortName: "Guardians",
    fullName: "Cleveland Guardians",
    code: "CLE",
    color: "#002b5c",
    secondaryColor: "#e31937",
    logo: GuardiansLogo,
    logoLight: GuardiansLogoLight,
    established: 1901,
    latitude: 41.4962,
    longitude: -81.6852,
    venueName: "Progressive Field",
    venueCapacity: "34,830",
    address: "2401 Ontario St, Cleveland, OH 44115",
    city: "Cleveland, OH",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/guardians.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 10,
    espnId: 27,
    name: "Rockies",
    shortName: "Rockies",
    fullName: "Colorado Rockies",
    code: "COL",
    color: "#33006f",
    secondaryColor: "#000000",
    logo: RockiesLogo,
    logoLight: RockiesLogoLight,
    established: 1993,
    latitude: 39.7559,
    longitude: -104.9942,
    venueName: "Coors Field",
    venueCapacity: "50,398",
    address: "2001 Blake St, Denver, CO 80205",
    city: "Denver, CO",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/rockies.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 12,
    espnId: 6,
    name: "Tigers",
    shortName: "Tigers",
    fullName: "Detroit Tigers",
    code: "DET",
    color: "#0a2240",
    secondaryColor: "#ff4713",
    logo: TigersLogo,
    logoLight: TigersLogoLight,
    established: 1901,
    latitude: 42.3391,
    longitude: -83.0484,
    venueName: "Comerica Park",
    venueCapacity: "41,083",
    address: "2100 Woodward Ave, Detroit, MI 48201",
    city: "Detroit, MI",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/tigers.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 15,
    espnId: 18,
    name: "Astros",
    shortName: "Astros",
    fullName: "Houston Astros",
    code: "HOU",
    color: "#002d62",
    secondaryColor: "#eb6e1f",
    logo: AstrosLogo,
    logoLight: AstrosLogoLight,
    established: 1962,
    latitude: 29.7573,
    longitude: -95.3555,
    venueName: "Minute Maid Park",
    venueCapacity: "41,168",
    address: "501 Crawford St, Houston, TX 77002",
    city: "Houston, TX",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/astros.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 16,
    espnId: 7,
    name: "Royals",
    shortName: "Royals",
    fullName: "Kansas City Royals",
    code: "KC",
    color: "#004687",
    secondaryColor: "#7ab2dd",
    logo: RoyalsLogo,
    logoLight: RoyalsLogoLight,
    established: 1969,
    latitude: 39.0516,
    longitude: -94.4808,
    venueName: "Kauffman Stadium",
    venueCapacity: "37,903",
    address: "1 Royal Way, Kansas City, MO 64129",
    city: "Kansas City, MO",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/royals.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 17,
    espnId: 3,
    name: "Angels",
    shortName: "Angels",
    fullName: "Los Angeles Angels",
    code: "LAA",
    color: "#ba0021",
    secondaryColor: "#c4ced4",
    logo: AngelsLogo,
    logoLight: AngelsLogoLight,
    established: 1961,
    latitude: 33.8003,
    longitude: -117.8827,
    venueName: "Angel Stadium",
    venueCapacity: "45,517",
    address: "2000 E Gene Autry Way, Anaheim, CA 92806",
    city: "Anaheim, CA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/angels.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 18,
    espnId: 19,
    name: "Dodgers",
    shortName: "Dodgers",
    fullName: "Los Angeles Dodgers",
    code: "LAD",
    color: "#005a9c",
    secondaryColor: "#ffffff",
    logo: DodgersLogo,
    logoLight: DodgersLogoLight,
    established: 1884,
    latitude: 34.0739,
    longitude: -118.24,
    venueName: "Dodger Stadium",
    venueCapacity: "56,000",
    address: "1000 Vin Scully Ave, Los Angeles, CA 90012",
    city: "Los Angeles, CA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/dodgers.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 19,
    espnId: 28,
    name: "Marlins",
    shortName: "Marlins",
    fullName: "Miami Marlins",
    code: "MIA",
    color: "#00a3e0",
    secondaryColor: "#000000",
    logo: MarlinsLogo,
    logoLight: MarlinsLogoLight,
    established: 1993,
    latitude: 25.7781,
    longitude: -80.2198,
    venueName: "loanDepot park",
    venueCapacity: "36,742",
    address: "501 Marlins Way, Miami, FL 33125",
    city: "Miami, FL",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/marlins.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 20,
    espnId: 8,
    name: "Brewers",
    shortName: "Brewers",
    fullName: "Milwaukee Brewers",
    code: "MIL",
    color: "#13294b",
    secondaryColor: "#ffc72c",
    logo: BrewersLogo,
    logoLight: BrewersLogoLight,
    established: 1969,
    latitude: 43.028,
    longitude: -87.9712,
    venueName: "American Family Field",
    venueCapacity: "41,900",
    address: "1 Brewers Way, Milwaukee, WI 53214",
    city: "Milwaukee, WI",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/brewers.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 22,
    espnId: 9,
    name: "Twins",
    shortName: "Twins",
    fullName: "Minnesota Twins",
    code: "MIN",
    color: "#031f40",
    secondaryColor: "#e20e32",
    logo: TwinsLogo,
    logoLight: TwinsLogoLight,
    established: 1901,
    latitude: 44.9817,
    longitude: -93.2777,
    venueName: "Target Field",
    venueCapacity: "38,544",
    address: "1 Twins Way, Minneapolis, MN 55403",
    city: "Minneapolis, MN",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/twins.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 24,
    espnId: 21,
    name: "Mets",
    shortName: "Mets",
    fullName: "New York Mets",
    code: "NYM",
    color: "#002d72",
    secondaryColor: "#ff5910",
    logo: MetsLogo,
    logoLight: MetsLogoLight,
    established: 1962,
    latitude: 40.7571,
    longitude: -73.8458,
    venueName: "Citi Field",
    venueCapacity: "41,922",
    address: "41 Seaver Way, Queens, NY 11368",
    city: "Queens, NY",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/mets.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 25,
    espnId: 10,
    name: "Yankees",
    shortName: "Yankees",
    fullName: "New York Yankees",
    code: "NYY",
    color: "#132448",
    secondaryColor: "#c4ced4",
    logo: YankeesLogo,
    logoLight: YankeesLogoLight,
    established: 1901,
    latitude: 40.8296,
    longitude: -73.9262,
    venueName: "Yankee Stadium",
    venueCapacity: "46,537",
    address: "1 E 161st St, Bronx, NY 10451",
    city: "Bronx, NY",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/yankees.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 27,
    espnId: 22,
    name: "Phillies",
    shortName: "Phillies",
    fullName: "Philadelphia Phillies",
    code: "PHI",
    color: "#e81828",
    secondaryColor: "#003278",
    logo: PhilliesLogo,
    logoLight: PhilliesLogoLight,
    established: 1883,
    latitude: 39.9057,
    longitude: -75.1665,
    venueName: "Citizens Bank Park",
    venueCapacity: "42,792",
    address: "1 Citizens Bank Way, Philadelphia, PA 19148",
    city: "Philadelphia, PA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/phillies.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 28,
    espnId: 23,
    name: "Pirates",
    shortName: "Pirates",
    fullName: "Pittsburgh Pirates",
    code: "PIT",
    color: "#000000",
    secondaryColor: "#fdb827",
    logo: PiratesLogo,
    logoLight: PiratesLogoLight,
    established: 1882,
    latitude: 40.4469,
    longitude: -80.0057,
    venueName: "PNC Park",
    venueCapacity: "38,362",
    address: "115 Federal St, Pittsburgh, PA 15212",
    city: "Pittsburgh, PA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/pirates.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 30,
    espnId: 25,
    name: "Padres",
    shortName: "Padres",
    fullName: "San Diego Padres",
    code: "SD",
    color: "#2f241d",
    secondaryColor: "#ffc425",
    logo: PadresLogo,
    logoLight: PadresLogoLight,
    established: 1969,
    latitude: 32.7073,
    longitude: -117.1573,
    venueName: "Petco Park",
    venueCapacity: "40,209",
    address: "100 Park Blvd, San Diego, CA 92101",
    city: "San Diego, CA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/padres.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 31,
    espnId: 26,
    name: "Giants",
    shortName: "Giants",
    fullName: "San Francisco Giants",
    code: "SF",
    color: "#000000",
    secondaryColor: "#fd5a1e",
    logo: GiantsLogo,
    logoLight: GiantsLogoLight,
    established: 1883,
    latitude: 37.7786,
    longitude: -122.3893,
    venueName: "Oracle Park",
    venueCapacity: "41,915",
    address: "24 Willie Mays Plaza, San Francisco, CA 94107",
    city: "San Francisco, CA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/giants.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 32,
    espnId: 12,
    name: "Mariners",
    shortName: "Mariners",
    fullName: "Seattle Mariners",
    code: "SEA",
    color: "#005c5c",
    secondaryColor: "#0c2c56",
    logo: MarinersLogo,
    logoLight: MarinersLogoLight,
    established: 1977,
    latitude: 47.5914,
    longitude: -122.3325,
    venueName: "T-Mobile Park",
    venueCapacity: "47,929",
    address: "1250 1st Ave S, Seattle, WA 98134",
    city: "Seattle, WA",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/mariners.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 33,
    espnId: 24,
    name: "Cardinals",
    shortName: "Cardinals",
    fullName: "St. Louis Cardinals",
    code: "STL",
    color: "#be0a14",
    secondaryColor: "#001541",
    logo: CardinalsLogo,
    logoLight: CardinalsLogoLight,
    established: 1882,
    latitude: 38.6226,
    longitude: -90.1928,
    venueName: "Busch Stadium",
    venueCapacity: "45,529",
    address: "700 Clark Ave, St. Louis, MO 63102",
    city: "St. Louis, MO",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/cardinals.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 34,
    espnId: 30,
    name: "Rays",
    shortName: "Rays",
    fullName: "Tampa Bay Rays",
    code: "TB",
    color: "#092c5c",
    secondaryColor: "#8fbce6",
    logo: RaysLogo,
    logoLight: RaysLogoLight,
    established: 1998,
    latitude: 27.7683,
    longitude: -82.6534,
    venueName: "Tropicana Field",
    venueCapacity: "25,025",
    address: "1 Tropicana Dr, St. Petersburg, FL 33705",
    city: "St. Petersburg, FL",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/rays.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 35,
    espnId: 13,
    name: "Rangers",
    shortName: "Rangers",
    fullName: "Texas Rangers",
    code: "TEX",
    color: "#003278",
    secondaryColor: "#c0111f",
    logo: RangersLogo,
    logoLight: RangersLogoLight,
    established: 1961,
    latitude: 32.7473,
    longitude: -97.0842,
    venueName: "Globe Life Field",
    venueCapacity: "40,300",
    address: "734 Stadium Dr, Arlington, TX 76011",
    city: "Arlington, TX",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/rangers.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 36,
    espnId: 14,
    name: "Blue Jays",
    shortName: "Blue Jays",
    fullName: "Toronto Blue Jays",
    code: "TOR",
    color: "#134a8e",
    secondaryColor: "#6cace5",
    logo: BlueJaysLogo,
    logoLight: BlueJaysLogoLight,
    established: 1977,
    latitude: 43.6415,
    longitude: -79.3894,
    venueName: "Rogers Centre",
    venueCapacity: "49,282",
    address: "1 Blue Jays Way, Toronto, ON M5V 1J1",
    city: "Toronto, Ontario",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/bluejays.jpg",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 37,
    espnId: 20,
    name: "Nationals",
    shortName: "Nationals",
    fullName: "Washington Nationals",
    code: "WSH",
    color: "#ab0003",
    secondaryColor: "#11225b",
    logo: NationalsLogo,
    logoLight: NationalsLogoLight,
    established: 1969,
    latitude: 38.873,
    longitude: -77.0074,
    venueName: "Nationals Park",
    venueCapacity: "41,339",
    address: "1500 S Capitol St SE, Washington, DC 20003",
    city: "Washington, DC",
    venueImage:
      "https://res.cloudinary.com/dm3qtdhag/image/upload/v1774705671/stadiums/baseball/nationals.jpg",
    isAllStar: false,
    isActive: true,
  },
];

export const getMLBTeam = (id: number | string) =>
  mlbTeams.find((t) => String(t.id) === String(id));

export const getMLBTeamLogo = (id: number | string, isDark: boolean) => {
  const team = mlbTeams.find((t) => String(t.id) === String(id));
  if (!team) return PlaceholderLogo;
  return isDark ? team.logoLight || team.logo : team.logo;
};

export const getMLBTeamByEspnId = (id: number | string) =>
  mlbTeams.find((t) => String(t.espnId) === String(id));
