// Logos
import { Team } from "@/types/team";
import SixersLogo from "../assets/NBA/Logos/76ers.png";
import SixersLogoLight from "../assets/NBA/Logos/76ersLight.png";
import BucksLogo from "../assets/NBA/Logos/Bucks.png";
import BullsLogo from "../assets/NBA/Logos/Bulls.png";
import CavaliersLogo from "../assets/NBA/Logos/Cavaliers.png";
import CelticsLogo from "../assets/NBA/Logos/Celtics.png";
import ClippersLogo from "../assets/NBA/Logos/Clippers.png";
import GrizzliesLogo from "../assets/NBA/Logos/Grizzlies.png";
import HawksLogo from "../assets/NBA/Logos/Hawks.png";
import HeatLogo from "../assets/NBA/Logos/Heat.png";
import HornetsLogo from "../assets/NBA/Logos/Hornets.png";
import JazzLogo from "../assets/NBA/Logos/Jazz.png";
import JazzLogoLight from "../assets/NBA/Logos/JazzLight.png";
import KingsLogo from "../assets/NBA/Logos/Kings.png";
import KnicksLogo from "../assets/NBA/Logos/Knicks.png";
import LakersLogo from "../assets/NBA/Logos/Lakers.png";
import MagicLogo from "../assets/NBA/Logos/Magic.png";
import MavericksLogo from "../assets/NBA/Logos/Mavericks.png";
import NetsLogo from "../assets/NBA/Logos/Nets.png";
import NuggetsLogo from "../assets/NBA/Logos/Nuggets.png";
import PacersLogo from "../assets/NBA/Logos/Pacers.png";
import PelicansLogo from "../assets/NBA/Logos/Pelicans.png";
import PistonsLogo from "../assets/NBA/Logos/Pistons.png";
import RaptorsLogo from "../assets/NBA/Logos/Raptors.png";
import RaptorsLogoLight from "../assets/NBA/Logos/RaptorsLight.png";
import RocketsLogo from "../assets/NBA/Logos/Rockets.png";
import RocketsLogoLight from "../assets/NBA/Logos/RocketsLight.png";
import SpursLogo from "../assets/NBA/Logos/Spurs.png";
import SunsLogo from "../assets/NBA/Logos/Suns.png";
import ThunderLogo from "../assets/NBA/Logos/Thunder.png";
import TimberwolvesLogo from "../assets/NBA/Logos/Timberwolves.png";
import TrailBlazersLogo from "../assets/NBA/Logos/TrailBlazers.png";
import WarriorsLogo from "../assets/NBA/Logos/Warriors.png";
import WizardsLogo from "../assets/NBA/Logos/Wizards.png";
const placeholderLogo =
  "https://res.cloudinary.com/dm3qtdhag/image/upload/v1781619331/placeholder/team.png";

export const teams: Team[] = [
  {
    id: 1,
    espnId: 1,
    summerLeagueId: 1,
    name: "Hawks",
    shortName: "Hawks",
    fullName: "Atlanta Hawks",
    code: "ATL",
    location: "Atlanta, GA",
    city: "Atlanta",
    logo: HawksLogo,
    logoLight: HawksLogo,
    color: "#e03a3e",
    secondaryColor: "#c1d32f",
    established: 1949,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 2,
    espnId: 2,
    summerLeagueId: 2,
    name: "Celtics",
    shortName: "Celtics",
    fullName: "Boston Celtics",
    code: "BOS",
    location: "Boston, MA",
    city: "Boston",
    logo: CelticsLogo,
    logoLight: CelticsLogo,
    color: "#007a33",
    secondaryColor: "#ffffff",
    established: 1949,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 4,
    espnId: 17,
    summerLeagueId: 110732,
    name: "Nets",
    shortName: "Nets",
    fullName: "Brooklyn Nets",
    code: "BKN",
    location: "Brooklyn, NY",
    city: "Brooklyn",
    logo: NetsLogo,
    logoLight: NetsLogo,
    color: "#000000",
    secondaryColor: "#ffffff",
    established: 1976,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 5,
    espnId: 30,
    summerLeagueId: 5,
    name: "Hornets",
    shortName: "Hornets",
    fullName: "Charlotte Hornets",
    code: "CHA",
    location: "Charlotte, NC",
    city: "Charlotte",
    logo: HornetsLogo,
    logoLight: HornetsLogo,
    color: "#1d1160",
    secondaryColor: "#00788c",
    established: 1988,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 6,
    espnId: 4,
    summerLeagueId: 6,
    name: "Bulls",
    shortName: "Bulls",
    fullName: "Chicago Bulls",
    code: "CHI",
    location: "Chicago, IL",
    city: "Chicago",
    logo: BullsLogo,
    logoLight: BullsLogo,
    color: "#ce1141",
    secondaryColor: "#000000",
    established: 1966,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 7,
    espnId: 5,
    summerLeagueId: 7,
    name: "Cavaliers",
    shortName: "Cavaliers",
    fullName: "Cleveland Cavaliers",
    code: "CLE",
    location: "Cleveland, OH",
    city: "Cleveland",
    logo: CavaliersLogo,
    logoLight: CavaliersLogo,
    color: "#860038",
    secondaryColor: "#fdbb30",
    established: 1970,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 8,
    espnId: 6,
    summerLeagueId: 8,
    name: "Mavericks",
    shortName: "Mavericks",
    fullName: "Dallas Mavericks",
    code: "DAL",
    location: "Dallas, TX",
    city: "Dallas",
    logo: MavericksLogo,
    logoLight: MavericksLogo,
    color: "#0053bc",
    secondaryColor: "#ffffff",
    established: 1980,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 9,
    espnId: 7,
    summerLeagueId: 9,
    name: "Nuggets",
    shortName: "Nuggets",
    fullName: "Denver Nuggets",
    code: "DEN",
    location: "Denver, CO",
    city: "Denver",
    logo: NuggetsLogo,
    logoLight: NuggetsLogo,
    color: "#0d2240",
    secondaryColor: "#ffc627",
    established: 1976,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 10,
    espnId: 8,
    summerLeagueId: 10,
    name: "Pistons",
    shortName: "Pistons",
    fullName: "Detroit Pistons",
    code: "DET",
    location: "Detroit, MI",
    city: "Detroit",
    logo: PistonsLogo,
    logoLight: PistonsLogo,
    color: "#c8102e",
    secondaryColor: "#1d428a",
    established: 1948,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 11,
    espnId: 9,
    summerLeagueId: 11,
    name: "Warriors",
    shortName: "Warriors",
    fullName: "Golden State Warriors",
    code: "GSW",
    location: "San Francisco, CA",
    city: "San Francisco",
    logo: WarriorsLogo,
    logoLight: WarriorsLogo,
    color: "#1d428a",
    secondaryColor: "#ffc72c",
    established: 1946,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 132761,
    espnId: 132761,
    summerLeagueId: 132761,
    name: "Warriors",
    shortName: "Warriors Blue",
    fullName: "Golden State Warriors",
    code: "GSW",
    location: "San Francisco, CA",
    city: "San Francisco",
    logo: WarriorsLogo,
    logoLight: WarriorsLogo,
    color: "#1d428a",
    secondaryColor: "#ffc72c",
    established: 1946,
    conference: "Western",
    isAllStar: false,
    isActive: false,
    isNational: false,
   league: "nba",
  },
  {
    id: 14,
    espnId: 10,
    summerLeagueId: 14,
    name: "Rockets",
    shortName: "Rockets",
    fullName: "Houston Rockets",
    code: "HOU",
    location: "Houston, TX",
    city: "Houston",
    logo: RocketsLogo,
    logoLight: RocketsLogoLight,
    color: "#ce1141",
    secondaryColor: "#000000",
    established: 1967,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 15,
    espnId: 11,
    summerLeagueId: 15,
    name: "Pacers",
    shortName: "Pacers",
    fullName: "Indiana Pacers",
    code: "IND",
    location: "Indianapolis, IN",
    city: "Indianapolis",
    logo: PacersLogo,
    logoLight: PacersLogo,
    color: "#002d62",
    secondaryColor: "#ffc627",
    established: 1976,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 16,
    espnId: 12,
    summerLeagueId: 16,
    name: "Clippers",
    shortName: "Clippers",
    fullName: "Los Angeles Clippers",
    code: "LAC",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    logo: ClippersLogo,
    logoLight: ClippersLogo,
    color: "#c8102e",
    secondaryColor: "#1d4294",
    established: 1970,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 17,
    espnId: 13,
    summerLeagueId: 17,
    name: "Lakers",
    shortName: "Lakers",
    fullName: "Los Angeles Lakers",
    code: "LAL",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    logo: LakersLogo,
    logoLight: LakersLogo,
    color: "#552582",
    secondaryColor: "#fdb927",
    established: 1948,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 19,
    espnId: 29,
    summerLeagueId: 19,
    name: "Grizzlies",
    shortName: "Grizzlies",
    fullName: "Memphis Grizzlies",
    code: "MEM",
    location: "Memphis, TN",
    city: "Memphis",
    logo: GrizzliesLogo,
    logoLight: GrizzliesLogo,
    color: "#12173f",
    secondaryColor: "#5d76a9",
    established: 1995,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 20,
    espnId: 14,
    summerLeagueId: 20,
    name: "Heat",
    shortName: "Heat",
    fullName: "Miami Heat",
    code: "MIA",
    location: "Miami, FL",
    city: "Miami",
    logo: HeatLogo,
    logoLight: HeatLogo,
    color: "#98002e",
    secondaryColor: "#000000",
    established: 1988,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 21,
    espnId: 15,
    summerLeagueId: 110746,
    name: "Bucks",
    shortName: "Bucks",
    fullName: "Milwaukee Bucks",
    code: "MIL",
    location: "Milwaukee, WI",
    city: "Milwaukee",
    logo: BucksLogo,
    logoLight: BucksLogo,
    color: "#00471b",
    secondaryColor: "#f0ebd2",
    established: 1968,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 22,
    espnId: 16,
    summerLeagueId: 22,
    name: "Timberwolves",
    shortName: "Timberwolves",
    fullName: "Minnesota Timberwolves",
    code: "MIN",
    location: "Minneapolis, MN",
    city: "Minneapolis",
    logo: TimberwolvesLogo,
    logoLight: TimberwolvesLogo,
    color: "#0c2340",
    secondaryColor: "#78be20",
    established: 1989,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },

  {
    id: 23,
    espnId: 3,
    summerLeagueId: 23,
    name: "Pelicans",
    shortName: "Pelicans",
    fullName: "New Orleans Pelicans",
    code: "NOP",
    location: "New Orleans, LA",
    city: "New Orleans",
    logo: PelicansLogo,
    logoLight: PelicansLogo,
    color: "#001641",
    secondaryColor: "#e31837",
    established: 2002,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 24,
    espnId: 18,
    summerLeagueId: 24,
    name: "Knicks",
    shortName: "Knicks",
    fullName: "New York Knicks",
    code: "NYK",
    location: "New York, NY",
    city: "New York",
    logo: KnicksLogo,
    logoLight: KnicksLogo,
    color: "#0072ce",
    secondaryColor: "#f58426",
    established: 1946,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 25,
    espnId: 25,
    summerLeagueId: 25,
    name: "Thunder",
    shortName: "Thunder",
    fullName: "Oklahoma City Thunder",
    code: "OKC",
    location: "Oklahoma City, OK",
    city: "Oklahoma City",
    logo: ThunderLogo,
    logoLight: ThunderLogo,
    color: "#007cc3",
    secondaryColor: "#ef3b24",
    established: 1967,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },

  {
    id: 26,
    espnId: 19,
    summerLeagueId: 26,
    name: "Magic",
    shortName: "Magic",
    fullName: "Orlando Magic",
    code: "ORL",
    location: "Orlando, FL",
    city: "Orlando",
    logo: MagicLogo,
    logoLight: MagicLogo,
    color: "#2050af",
    secondaryColor: "#ffffff",
    established: 1989,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 27,
    espnId: 20,
    summerLeagueId: 27,
    name: "76ers",
    shortName: "76ers",
    fullName: "Philadelphia 76ers",
    code: "PHI",
    location: "Philadelphia, PA",
    city: "Philadelphia",
    logo: SixersLogo,
    logoLight: SixersLogoLight,
    color: "#006bb6",
    secondaryColor: "#ffffff",
    established: 1949,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 28,
    espnId: 21,
    summerLeagueId: 28,
    name: "Suns",
    shortName: "Suns",
    fullName: "Phoenix Suns",
    code: "PHX",
    location: "Phoenix, AZ",
    city: "Phoenix",
    logo: SunsLogo,
    logoLight: SunsLogo,
    color: "#1d1160",
    secondaryColor: "#e56020",
    established: 1968,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 29,
    espnId: 22,
    summerLeagueId: 29,
    name: "Trail Blazers",
    shortName: "Trail Blazers",
    fullName: "Portland Trail Blazers",
    code: "POR",
    location: "Portland, OR",
    city: "Portland",
    logo: TrailBlazersLogo,
    logoLight: TrailBlazersLogo,
    color: "#e03a3e",
    secondaryColor: "#000000",
    established: 1970,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 30,
    espnId: 23,
    summerLeagueId: 30,
    name: "Kings",
    shortName: "Kings",
    fullName: "Sacramento Kings",
    code: "SAC",
    location: "Sacramento, CA",
    city: "Sacramento",
    logo: KingsLogo,
    logoLight: KingsLogo,
    color: "#5b2b82",
    secondaryColor: "#63717a",
    established: 1948,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 31,
    espnId: 24,
    summerLeagueId: 31,
    name: "Spurs",
    shortName: "Spurs",
    fullName: "San Antonio Spurs",
    code: "SAS",
    location: "San Antonio, TX",
    city: "San Antonio",
    logo: SpursLogo,
    logoLight: SpursLogo,
    color: "#000000",
    secondaryColor: "#c4ced3",
    established: 1976,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 38,
    espnId: 28,
    summerLeagueId: 38,
    name: "Raptors",
    shortName: "Raptors",
    fullName: "Toronto Raptors",
    code: "TOR",
    location: "Toronto, ON",
    city: "Toronto",
    logo: RaptorsLogo,
    logoLight: RaptorsLogoLight,
    color: "#ce1140",
    secondaryColor: "#ffffff",
    established: 1995,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 40,
    espnId: 26,
    summerLeagueId: 40,
    name: "Jazz",
    shortName: "Jazz",
    fullName: "Utah Jazz",
    code: "UTA",
    location: "Salt Lake City, UT",
    city: "Salt Lake City",
    logo: JazzLogo,
    logoLight: JazzLogoLight,
    color: "#3e2680",
    secondaryColor: "#ffffff",
    established: 1974,
    conference: "Western",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
  {
    id: 41,
    espnId: 27,
    summerLeagueId: 41,
    name: "Wizards",
    shortName: "Wizards",
    fullName: "Washington Wizards",
    code: "WAS",
    location: "Washington, DC",
    city: "Washington DC",
    logo: WizardsLogo,
    logoLight: WizardsLogo,
    color: "#002b5c",
    secondaryColor: "#e31837",
    established: 1961,
    conference: "Eastern",
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "nba",
  },
];

export const getTeamByESPNId = (espnId: number | string) => {
  return teams.find((t) => t.espnId?.toString() === espnId?.toString());
};

export const getTeamBySummerId = (id?: number | string) =>
  teams.find((t) => String(t.summerLeagueId) === String(id));

export const getNBATeam = (id: number | string) => {
  if (id == null) return undefined;
  return teams.find((t) => String(t.id) === String(id));
};

export function getNBATeamLogo(
  id: number | string | undefined,
  isDark: boolean,
) {
  if (id === undefined || id === null || id === "") {
    return placeholderLogo;
  }

  const normalizedId = String(id);

  const team = teams.find(
    (team) =>
      String(team.id) === normalizedId ||
      String(team.summerLeagueId) === normalizedId,
  );

  if (!team) {
    return placeholderLogo;
  }

  return isDark
    ? (team.logoLight ?? team.logo ?? placeholderLogo)
    : (team.logo ?? placeholderLogo);
}
