import { Team } from "@/types/team";

// Logos
import PlaceholderLogo from "../assets/Placeholders/teamPlaceholder.png";
import AcesLogo from "../assets/WNBA/Logos/Aces.png";
import CoopLogo from "../assets/WNBA/Logos/Coop.png";
import DreamLogo from "../assets/WNBA/Logos/Dream.png";
import FeverLogo from "../assets/WNBA/Logos/Fever.png";
import FireLogo from "../assets/WNBA/Logos/Fire.png";
import FireLogoLight from "../assets/WNBA/Logos/FireLight.png";
import LibertyLogo from "../assets/WNBA/Logos/Liberty.png";
import LynxLogo from "../assets/WNBA/Logos/Lynx.png";
import MercuryLogo from "../assets/WNBA/Logos/Mercury.png";
import MysticsLogo from "../assets/WNBA/Logos/Mystics.png";
import SkyLogo from "../assets/WNBA/Logos/Sky.png";
import SparksLogo from "../assets/WNBA/Logos/Sparks.png";
import SpoonLogo from "../assets/WNBA/Logos/Spoon.png";
import StormLogo from "../assets/WNBA/Logos/Storm.png";
import SunLogo from "../assets/WNBA/Logos/Sun.png";
import TempoLogo from "../assets/WNBA/Logos/Tempo.png";
import TempoLogoLight from "../assets/WNBA/Logos/TempoLight.png";
import ValkyrieLogo from "../assets/WNBA/Logos/Valkyrie.png";
import WingsLogo from "../assets/WNBA/Logos/Wings.png";

export const wnbaTeams: Team[] = [
  {
    id: 162,
    espnId: 20,
    name: "Dream",
    shortName: "Dream",
    fullName: "Atlanta Dream",
    code: "ATL",
    color: "#e31837",
    secondaryColor: "#5091cc",
    logo: DreamLogo,
    logoLight: DreamLogo,
    location: "College Park, GA",
    city: "Atlanta",
    established: 2008,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 163,
    espnId: 19,
    name: "Sky",
    shortName: "Sky",
    fullName: "Chicago Sky",
    code: "CHI",
    color: "#5091cd",
    secondaryColor: "#ffd520",
    logo: SkyLogo,
    logoLight: SkyLogo,
    location: "Chicago, IL",
    city: "Chicago",
    established: 2006,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 164,
    espnId: 18,
    name: "Sun",
    shortName: "Sun",
    fullName: "Connecticut Sun",
    code: "CONN",
    color: "#f05023",
    secondaryColor: "#0a2240",
    logo: SunLogo,
    logoLight: SunLogo,
    location: "Uncasville, CT",
    city: "Uncasville",
    established: 1999,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 165,
    espnId: 3,
    name: "Wings",
    shortName: "Wings",
    fullName: "Dallas Wings",
    code: "DAL",
    color: "#002b5c",
    secondaryColor: "#c4d600",
    logo: WingsLogo,
    logoLight: WingsLogo,
    location: "Arlington, TX",
    city: "Arlington",
    established: 1998,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 7326,
    espnId: 129689,
    name: "Valkyries",
    shortName: "Valkyries",
    fullName: "Golden State Valkyries",
    code: "GS",
    color: "#b38fcf",
    secondaryColor: "#000000",
    logo: ValkyrieLogo,
    logoLight: ValkyrieLogo,
    location: "San Francisco, CA",
    city: "San Francisco",
    established: 2023,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 166,
    espnId: 5,
    name: "Fever",
    shortName: "Fever",
    fullName: "Indiana Fever",
    code: "IND",
    color: "#002d62",
    secondaryColor: "#e03a3e",
    logo: FeverLogo,
    logoLight: FeverLogo,
    location: "Indianapolis, IN",
    city: "Indianapolis",
    established: 2000,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 167,
    espnId: 17,
    name: "Aces",
    shortName: "Aces",
    fullName: "Las Vegas Aces",
    code: "LV",
    color: "#a7a8aa",
    secondaryColor: "#000000",
    logo: AcesLogo,
    logoLight: AcesLogo,
    location: "Las Vegas, NV",
    city: "Las Vegas",
    established: 1997,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 168,
    espnId: 6,
    name: "Sparks",
    shortName: "Sparks",
    fullName: "Los Angeles Sparks",
    code: "LA",
    color: "#552583",
    secondaryColor: "#fdb927",
    logo: SparksLogo,
    logoLight: SparksLogo,
    location: "Los Angeles, CA",
    city: "Los Angeles",
    established: 1997,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 169,
    espnId: 8,
    name: "Lynx",
    shortName: "Lynx",
    fullName: "Minnesota Lynx",
    code: "MIN",
    color: "#266092",
    secondaryColor: "#79bc43",
    logo: LynxLogo,
    logoLight: LynxLogo,
    location: "Minneapolis, MN",
    city: "Minneapolis",
    established: 1999,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 170,
    espnId: 9,
    name: "Liberty",
    shortName: "Liberty",
    fullName: "New York Liberty",
    code: "NY",
    color: "#86cebc",
    secondaryColor: "#000000",
    logo: LibertyLogo,
    logoLight: LibertyLogo,
    location: "Brooklyn, NY",
    city: "New York",
    established: 1997,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 171,
    espnId: 11,
    name: "Mercury",
    shortName: "Mercury",
    fullName: "Phoenix Mercury",
    code: "PHX",
    color: "#3c286e",
    secondaryColor: "#fa4b0a",
    logo: MercuryLogo,
    logoLight: MercuryLogo,
    location: "Phoenix, AZ",
    city: "Phoenix",
    established: 1997,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 7100,
    espnId: 132052,
    name: "Fire",
    shortName: "Fire",
    fullName: "Portland Fire",
    code: "POR",
    color: "#b22222",
    secondaryColor: "#a52a2a",
    logo: FireLogo,
    logoLight: FireLogoLight,
    location: "Portland, OR",
    city: "Portland",
    established: 2000,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 172,
    espnId: 14,
    name: "Storm",
    shortName: "Storm",
    fullName: "Seattle Storm",
    code: "SEA",
    color: "#2c5235",
    secondaryColor: "#fee11a",
    logo: StormLogo,
    logoLight: StormLogo,
    location: "Seattle, WA",
    city: "Seattle",
    established: 2000,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 7870,
    espnId: 131935,
    name: "Tempo",
    shortName: "Tempo",
    fullName: "Toronto Tempo",
    code: "TOR",
    color: "#33476D",
    secondaryColor: "#7B1B38",
    logo: TempoLogo,
    logoLight: TempoLogoLight,
    location: "Toronto, ON",
    city: "Toronto",
    established: 2023,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 175,
    espnId: 16,
    name: "Mystics",
    shortName: "Mystics",
    fullName: "Washington Mystics",
    code: "WSH",
    color: "#e03a3e",
    secondaryColor: "#002b5c",
    logo: MysticsLogo,
    logoLight: MysticsLogo,
    location: "Washington, D.C",
    city: "Washington, D.C",
    established: 1998,
    isAllStar: false,
    isActive: true,
    isNational: false,
   league: "wnba",
  },
  {
    id: 3807,
    espnId: 130927,
    name: "Antelopes",
    shortName: "Antelopes",
    fullName: "Toyota Antelopes",
    code: "TOY",
    color: "#000000",
    secondaryColor: "#FFC0CB",
    logo: PlaceholderLogo,
    logoLight: PlaceholderLogo,
    location: "Nagoya, Japan",
    city: "",
    established: 1961,
    isAllStar: false,
    isActive: false,
    isNational: false,
   league: "wnba",
  },
  {
    id: 133384,
    espnId: 133384,
    name: "Team Coop",
    shortName: "Coop",
    fullName: "Team Coop",
    code: "COOP",
    color: "#000000",
    secondaryColor: "#FFC0CB",
    logo: CoopLogo,
    logoLight: CoopLogo,
    location: null,
    city: null,
    established: 1961,
    isAllStar: true,
    isActive: false,
    isNational: false,
   league: "wnba",
  },
  {
    id: 133383,
    espnId: 133383,
    name: "Team Spoon",
    shortName: "Spoon",
    fullName: "Team Spoon",
    code: "SPOON",
    color: "#000000",
    secondaryColor: "#FFC0CB",
    logo: SpoonLogo,
    logoLight: SpoonLogo,
    location: null,
    city: null,
    established: 1961,
    isAllStar: true,
    isActive: false,
    isNational: false,
   league: "wnba",
  },
];

export const getWNBATeamByESPNId = (espnId: number | string) => {
  return wnbaTeams.find((t) => t.espnId?.toString() === espnId?.toString());
};

export const getWNBATeam = (id: number | string) => {
  if (id == null) return undefined;
  return wnbaTeams.find((t) => String(t.id) === String(id));
};

export function getWNBATeamLogo(
  id: number | string | undefined,
  isDark: boolean,
) {
  if (!id) return PlaceholderLogo;

  const team = wnbaTeams.find((t) => String(t.id) === String(id));

  return team
    ? isDark
      ? team.logoLight || team.logo
      : team.logo
    : PlaceholderLogo;
}
