// Logos
import { Team } from "@/types/team";
import AUSLogo from "../assets/GLeague/Logos/aus.png";
import AUSLogoLight from "../assets/GLeague/Logos/ausLight.png";
import BIRLogo from "../assets/GLeague/Logos/bir.png";
import BIRLogoLight from "../assets/GLeague/Logos/birLight.png";
import CAPLogo from "../assets/GLeague/Logos/cap.png";
import CAPLogoLight from "../assets/GLeague/Logos/capLight.png";
import CLCLogo from "../assets/GLeague/Logos/clc.png";
import CLCLogoLight from "../assets/GLeague/Logos/clcLight.png";
import CPSLogo from "../assets/GLeague/Logos/cps.png";
import CPSLogoLight from "../assets/GLeague/Logos/cpsLight.png";
import CVLLogo from "../assets/GLeague/Logos/cvl.png";
import CVLLogoLight from "../assets/GLeague/Logos/cvlLight.png";
import DELLogo from "../assets/GLeague/Logos/del.png";
import DELLogoLight from "../assets/GLeague/Logos/delLight.png";
import GBOLogo from "../assets/GLeague/Logos/gbo.png";
import GBOLogoLight from "../assets/GLeague/Logos/gboLight.png";
import GLILogo from "../assets/GLeague/Logos/gli.png";
import GLILogoLight from "../assets/GLeague/Logos/gliLight.png";
import GRDLogo from "../assets/GLeague/Logos/grd.png";
import GRDLogoLight from "../assets/GLeague/Logos/grdLight.png";
import IWALogo from "../assets/GLeague/Logos/iwa.png";
import IWALogoLight from "../assets/GLeague/Logos/iwaLight.png";
import LINLogo from "../assets/GLeague/Logos/lin.png";
import LINLogoLight from "../assets/GLeague/Logos/linLight.png";
import MCCLogo from "../assets/GLeague/Logos/mcc.png";
import MCCLogoLight from "../assets/GLeague/Logos/mccLight.png";
import MHULogo from "../assets/GLeague/Logos/mhu.png";
import MHULogoLight from "../assets/GLeague/Logos/mhuLight.png";
import MNELogo from "../assets/GLeague/Logos/mne.png";
import MNELogoLight from "../assets/GLeague/Logos/mneLight.png";
import MXCLogo from "../assets/GLeague/Logos/mxc.png";
import MXCLogoLight from "../assets/GLeague/Logos/mxcLight.png";
import NOBLogo from "../assets/GLeague/Logos/nob.png";
import NOBLogoLight from "../assets/GLeague/Logos/nobLight.png";
import OKLLogo from "../assets/GLeague/Logos/okl.png";
import OKLLogoLight from "../assets/GLeague/Logos/oklLight.png";
import OSCLogo from "../assets/GLeague/Logos/osc.png";
import OSCLogoLight from "../assets/GLeague/Logos/oscLight.png";
import RAPLogo from "../assets/GLeague/Logos/rap.png";
import RAPLogoLight from "../assets/GLeague/Logos/rapLight.png";
import RCITYLogo from "../assets/GLeague/Logos/rcity.png";
import RCITYLogoLight from "../assets/GLeague/Logos/rcityLight.png";
import RGVLogo from "../assets/GLeague/Logos/rgv.png";
import RGVLogoLight from "../assets/GLeague/Logos/rgvLight.png";
import SANLogo from "../assets/GLeague/Logos/san.png";
import SANLogoLight from "../assets/GLeague/Logos/sanLight.png";
import SCWLogo from "../assets/GLeague/Logos/scw.png";
import SCWLogoLight from "../assets/GLeague/Logos/scwLight.png";
import SLCLogo from "../assets/GLeague/Logos/slc.png";
import SLCLogoLight from "../assets/GLeague/Logos/slcLight.png";
import STOLogo from "../assets/GLeague/Logos/sto.png";
import STOLogoLight from "../assets/GLeague/Logos/stoLight.png";
import SXFLogo from "../assets/GLeague/Logos/sxf.png";
import SXFLogoLight from "../assets/GLeague/Logos/sxfLight.png";
import TEXLogo from "../assets/GLeague/Logos/tex.png";
import TEXLogoLight from "../assets/GLeague/Logos/texLight.png";
import VALLEYLogo from "../assets/GLeague/Logos/valley.png";
import VALLEYLogoLight from "../assets/GLeague/Logos/valleyLight.png";
import WCBLogo from "../assets/GLeague/Logos/wcb.png";
import WCBLogoLight from "../assets/GLeague/Logos/wcbLight.png";
import WESLogo from "../assets/GLeague/Logos/wes.png";
import WESLogoLight from "../assets/GLeague/Logos/wesLight.png";
import WISLogo from "../assets/GLeague/Logos/wis.png";
import WISLogoLight from "../assets/GLeague/Logos/wisLight.png";
const placeholderLogo =
  "https://res.cloudinary.com/dm3qtdhag/image/upload/v1781619331/placeholder/team.png";

export const gleagueTeams: Team[] = [
  {
    id: 1,
    espnId: 1,
    name: "Clippers",
    shortName: "Clippers",
    fullName: "San Diego Clippers",
    code: "SAN",
    color: "#C8102E",
    secondaryColor: "#1D428A",
    logo: SANLogo,
    logoLight: SANLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 2,
    espnId: 2,
    name: "Spurs",
    shortName: "Spurs",
    fullName: "Austin Spurs",
    code: "AUS",
    color: "#000000",
    secondaryColor: "#C4CED4",
    logo: AUSLogo,
    logoLight: AUSLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 3,
    espnId: 3,
    name: "Charge",
    shortName: "Charge",
    fullName: "Cleveland Charge",
    code: "CLC",
    color: "#061642",
    secondaryColor: "#fdbb30",
    logo: CLCLogo,
    logoLight: CLCLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 4,
    espnId: 4,
    name: "Go-Go",
    shortName: "Go-Go",
    fullName: "Capital City Go-Go",
    code: "CAP",
    color: "#002B5C",
    secondaryColor: "#E31837",
    logo: CAPLogo,
    logoLight: CAPLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 5,
    espnId: 5,
    name: "Blue Coats",
    shortName: "Blue Coats",
    fullName: "Delaware Blue Coats",
    code: "DEL",
    color: "#003DA6",
    secondaryColor: "#DD0031",
    logo: DELLogo,
    logoLight: DELLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 6,
    espnId: 6,
    name: "Squadron",
    shortName: "Squadron",
    fullName: "Birmingham Squadron",
    code: "BIR",
    color: "#002A5C",
    secondaryColor: "#b4975a",
    logo: BIRLogo,
    logoLight: BIRLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 7,
    espnId: 7,
    name: "Boom",
    shortName: "Boom",
    fullName: "Noblesville Boom",
    code: "NOB",
    color: "#002D62",
    secondaryColor: "#FDBB30",
    logo: NOBLogo,
    logoLight: NOBLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 8,
    espnId: 8,
    name: "Gold",
    shortName: "Gold",
    fullName: "Grand Rapids Gold",
    code: "GRD",
    color: "#C8102E",
    secondaryColor: "#1D428A",
    logo: GRDLogo,
    logoLight: GRDLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 9,
    espnId: 9,
    name: "Swarm",
    shortName: "Swarm",
    fullName: "Greensboro Swarm",
    code: "GBO",
    color: "#007BBC",
    secondaryColor: "#1D1160",
    logo: GBOLogo,
    logoLight: GBOLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 10,
    espnId: 10,
    name: "Wolves",
    shortName: "Wolves",
    fullName: "Iowa Wolves",
    code: "IWA",
    color: "#0C2340",
    secondaryColor: "#236192",
    logo: IWALogo,
    logoLight: IWALogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 11,
    espnId: 11,
    name: "Magic",
    shortName: "Magic",
    fullName: "Osceola Magic",
    code: "OSC",
    color: "#000000",
    secondaryColor: "#0077C0",
    logo: OSCLogo,
    logoLight: OSCLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 12,
    espnId: 12,
    name: "Nets",
    shortName: "Nets",
    fullName: "Long Island Nets",
    code: "LIN",
    color: "#006BB6",
    secondaryColor: "#ED174C",
    logo: LINLogo,
    logoLight: LINLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 13,
    espnId: 13,
    name: "Celtics",
    shortName: "Celtics",
    fullName: "Maine Celtics",
    code: "MNE",
    color: "#006532",
    secondaryColor: "#f1f2f3",
    logo: MNELogo,
    logoLight: MNELogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 14,
    espnId: 14,
    name: "Hustle",
    shortName: "Hustle",
    fullName: "Memphis Hustle",
    code: "MHU",
    color: "#E2231A",
    secondaryColor: "#717271",
    logo: MHULogo,
    logoLight: MHULogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 15,
    espnId: 15,
    name: "Cruise",
    shortName: "Cruise",
    fullName: "Motor City Cruise",
    code: "MCC",
    color: "#FA002C",
    secondaryColor: "#006bb6",
    logo: MCCLogo,
    logoLight: MCCLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 16,
    espnId: 16,
    name: "Blue",
    shortName: "Blue",
    fullName: "Oklahoma City Blue",
    code: "OKL",
    color: "#007AC1",
    secondaryColor: "#EF3B24",
    logo: OKLLogo,
    logoLight: OKLLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 17,
    espnId: 17,
    name: "905",
    shortName: "905",
    fullName: "Raptors 905",
    code: "RAP",
    color: "#CE1141",
    secondaryColor: "#000000",
    logo: RAPLogo,
    logoLight: RAPLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 18,
    espnId: 18,
    name: "Vipers",
    shortName: "Vipers",
    fullName: "Rio Grande Valley Vipers",
    code: "RGV",
    color: "#CE1141",
    secondaryColor: "#BEC0C2",
    logo: RGVLogo,
    logoLight: RGVLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 19,
    espnId: 19,
    name: "Stars",
    shortName: "Stars",
    fullName: "Salt Lake City Stars",
    code: "SLC",
    color: "#002B5C",
    secondaryColor: "#F9A01B",
    logo: SLCLogo,
    logoLight: SLCLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 20,
    espnId: 20,
    name: "Warriors",
    shortName: "Warriors",
    fullName: "Santa Cruz Warriors",
    code: "SCW",
    color: "#006BB6",
    secondaryColor: "#FDB927",
    logo: SCWLogo,
    logoLight: SCWLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 21,
    espnId: 21,
    name: "Skyforce",
    shortName: "Skyforce",
    fullName: "Sioux Falls Skyforce",
    code: "SXF",
    color: "#000000",
    secondaryColor: "#98002E",
    logo: SXFLogo,
    logoLight: SXFLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 22,
    espnId: 22,
    name: "Lakers",
    shortName: "Lakers",
    fullName: "Coachella Valley Lakers",
    code: "CVL",
    color: "#552583",
    secondaryColor: "#FDB927",
    logo: CVLLogo,
    logoLight: CVLLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 23,
    espnId: 23,
    name: "Kings",
    shortName: "Kings",
    fullName: "Stockton Kings",
    code: "STO",
    color: "#5A2D81",
    secondaryColor: "#000000",
    logo: STOLogo,
    logoLight: STOLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 24,
    espnId: 24,
    name: "Legends",
    shortName: "Legends",
    fullName: "Texas Legends",
    code: "TEX",
    color: "#0053BC",
    secondaryColor: "#00285E",
    logo: TEXLogo,
    logoLight: TEXLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 25,
    espnId: 25,
    name: "Knicks",
    shortName: "Knicks",
    fullName: "Westchester Knicks",
    code: "WES",
    color: "#006BB6",
    secondaryColor: "#F58426",
    logo: WESLogo,
    logoLight: WESLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 26,
    espnId: 26,
    name: "Bulls",
    shortName: "Bulls",
    fullName: "Windy City Bulls",
    code: "WCB",
    color: "#CE1141",
    secondaryColor: "#000000",
    logo: WCBLogo,
    logoLight: WCBLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 27,
    espnId: 27,
    name: "Herd",
    shortName: "Herd",
    fullName: "Wisconsin Herd",
    code: "WIS",
    color: "#00471B",
    secondaryColor: "#EEE1C6",
    logo: WISLogo,
    logoLight: WISLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 28,
    espnId: 28,
    name: "Skyhawks",
    shortName: "Skyhawks",
    fullName: "College Park Skyhawks",
    code: "CPS",
    color: "#000000",
    secondaryColor: "#b3042a",
    logo: CPSLogo,
    logoLight: CPSLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 123432,
    espnId: 123432,
    name: "Ignite",
    shortName: "Ignite",
    fullName: "G League Ignite",
    code: "GLI",
    color: null,
    secondaryColor: null,
    logo: GLILogo,
    logoLight: GLILogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 124612,
    espnId: 124612,
    name: "Capitanes",
    shortName: "Capitanes",
    fullName: "Mexico City Capitanes",
    code: "MXC",
    color: "#3A4C98",
    secondaryColor: null,
    logo: MXCLogo,
    logoLight: MXCLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 128019,
    espnId: 128019,
    name: "Remix",
    shortName: "Remix",
    fullName: "Rip City Remix",
    code: "RCITY",
    color: null,
    secondaryColor: null,
    logo: RCITYLogo,
    logoLight: RCITYLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 129713,
    espnId: 129713,
    name: "Suns",
    shortName: "Suns",
    fullName: "Valley Suns",
    code: "VALLEY",
    color: null,
    secondaryColor: null,
    logo: VALLEYLogo,
    logoLight: VALLEYLogoLight,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 129829,
    espnId: 129829,
    name: "United",
    shortName: "United",
    fullName: "G League United",
    code: "UTD",
    color: null,
    secondaryColor: null,
    logo: null,
    logoLight: null,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 129830,
    espnId: 129830,
    name: "MIS",
    shortName: "MIS",
    fullName: "MEGA MIS",
    code: "MEGA",
    color: null,
    secondaryColor: null,
    logo: null,
    logoLight: null,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
];

export const getGLeagueTeam = (id: number | string) => {
  if (id == null) return undefined;
  return gleagueTeams.find((t) => String(t.id) === String(id));
};

export function getGLeagueTeamLogo(
  id: number | string | undefined,
  isDark: boolean,
) {
  if (id === undefined || id === null || id === "") {
    return placeholderLogo;
  }

  const normalizedId = String(id);

  const team = gleagueTeams.find(
    (team) =>
      String(team.id) === normalizedId ||
      String(team.summerLeagueId) === normalizedId,
  );

  if (!team) {
    return placeholderLogo;
  }

  return isDark
    ? (team.logoLight ?? team.logo ?? placeholderLogo)
    : (team.logo ?? placeholderLogo);
}
