import { Team } from "@/types/football/football";
import PlaceholderLogo from "../assets/Placeholders/teamPlaceholder.png";
import AFCBournemouthLogo from "../assets/Soccer/Logos/AFCBournemouth.png";
import AFCBournemouthLogoLight from "../assets/Soccer/Logos/AFCBournemouthLight.png";
import AlavesLogo from "../assets/Soccer/Logos/Alaves.png";
import AlavesLogoLight from "../assets/Soccer/Logos/AlavesLight.png";
import AlgeriaLogo from "../assets/Soccer/Logos/Algeria.png";
import AlgeriaLogoLight from "../assets/Soccer/Logos/AlgeriaLight.png";
import ArgentinaLogo from "../assets/Soccer/Logos/Argentina.png";
import Argentina2750Logo from "../assets/Soccer/Logos/Argentina2750.png";
import Argentina2750LogoLight from "../assets/Soccer/Logos/Argentina2750Light.png";
import ArgentinaLogoLight from "../assets/Soccer/Logos/ArgentinaLight.png";
import ArsenalLogo from "../assets/Soccer/Logos/Arsenal.png";
import ArsenalLogoLight from "../assets/Soccer/Logos/ArsenalLight.png";
import AstonVillaLogo from "../assets/Soccer/Logos/AstonVilla.png";
import AstonVillaLogoLight from "../assets/Soccer/Logos/AstonVillaLight.png";
import AthleticClubLogo from "../assets/Soccer/Logos/AthleticClub.png";
import AthleticClubLogoLight from "../assets/Soccer/Logos/AthleticClubLight.png";
import AtlantaUnitedFCLogo from "../assets/Soccer/Logos/AtlantaUnitedFC.png";
import AtlantaUnitedFCLogoLight from "../assets/Soccer/Logos/AtlantaUnitedFCLight.png";
import AtleticoMadridLogo from "../assets/Soccer/Logos/AtleticoMadrid.png";
import AtleticoMadridLogoLight from "../assets/Soccer/Logos/AtleticoMadridLight.png";
import AustinFCLogo from "../assets/Soccer/Logos/AustinFC.png";
import AustinFCLogoLight from "../assets/Soccer/Logos/AustinFCLight.png";
import AustraliaLogo from "../assets/Soccer/Logos/Australia.png";
import Australia2751Logo from "../assets/Soccer/Logos/Australia2751.png";
import Australia2751LogoLight from "../assets/Soccer/Logos/Australia2751Light.png";
import AustraliaLogoLight from "../assets/Soccer/Logos/AustraliaLight.png";
import AustriaLogo from "../assets/Soccer/Logos/Austria.png";
import AustriaLogoLight from "../assets/Soccer/Logos/AustriaLight.png";
import BarcelonaLogo from "../assets/Soccer/Logos/Barcelona.png";
import BarcelonaLogoLight from "../assets/Soccer/Logos/BarcelonaLight.png";
import BayerLeverkusenLogo from "../assets/Soccer/Logos/BayerLeverkusen.png";
import BayerLeverkusenLogoLight from "../assets/Soccer/Logos/BayerLeverkusenLight.png";
import BayernMunichLogo from "../assets/Soccer/Logos/BayernMunich.png";
import BayernMunichLogoLight from "../assets/Soccer/Logos/BayernMunichLight.png";
import BelgiumLogo from "../assets/Soccer/Logos/Belgium.png";
import BelgiumLogoLight from "../assets/Soccer/Logos/BelgiumLight.png";
import BorussiaDortmundLogo from "../assets/Soccer/Logos/BorussiaDortmund.png";
import BorussiaDortmundLogoLight from "../assets/Soccer/Logos/BorussiaDortmundLight.png";
import BorussiaMonchengladbachLogo from "../assets/Soccer/Logos/BorussiaMonchengladbach.png";
import BorussiaMonchengladbachLogoLight from "../assets/Soccer/Logos/BorussiaMonchengladbachLight.png";
import BosniaHerzegovinaLogo from "../assets/Soccer/Logos/BosniaHerzegovina.png";
import BosniaHerzegovinaLogoLight from "../assets/Soccer/Logos/BosniaHerzegovinaLight.png";
import BrazilLogo from "../assets/Soccer/Logos/Brazil.png";
import Brazil2752Logo from "../assets/Soccer/Logos/Brazil2752.png";
import Brazil2752LogoLight from "../assets/Soccer/Logos/Brazil2752Light.png";
import BrazilLogoLight from "../assets/Soccer/Logos/BrazilLight.png";
import BrentfordLogo from "../assets/Soccer/Logos/Brentford.png";
import BrentfordLogoLight from "../assets/Soccer/Logos/BrentfordLight.png";
import BrightonHoveAlbionLogo from "../assets/Soccer/Logos/BrightonHoveAlbion.png";
import BrightonHoveAlbionLogoLight from "../assets/Soccer/Logos/BrightonHoveAlbionLight.png";
import BurnleyLogo from "../assets/Soccer/Logos/Burnley.png";
import BurnleyLogoLight from "../assets/Soccer/Logos/BurnleyLight.png";
import CanadaLogo from "../assets/Soccer/Logos/Canada.png";
import Canada2753Logo from "../assets/Soccer/Logos/Canada2753.png";
import Canada2753LogoLight from "../assets/Soccer/Logos/Canada2753Light.png";
import CanadaLogoLight from "../assets/Soccer/Logos/CanadaLight.png";
import CapeVerdeLogo from "../assets/Soccer/Logos/CapeVerde.png";
import CapeVerdeLogoLight from "../assets/Soccer/Logos/CapeVerdeLight.png";
import CeltaVigoLogo from "../assets/Soccer/Logos/CeltaVigo.png";
import CeltaVigoLogoLight from "../assets/Soccer/Logos/CeltaVigoLight.png";
import CFMontrealLogo from "../assets/Soccer/Logos/CFMontreal.png";
import CFMontrealLogoLight from "../assets/Soccer/Logos/CFMontrealLight.png";
import CharlotteFCLogo from "../assets/Soccer/Logos/CharlotteFC.png";
import CharlotteFCLogoLight from "../assets/Soccer/Logos/CharlotteFCLight.png";
import ChelseaLogo from "../assets/Soccer/Logos/Chelsea.png";
import ChelseaLogoLight from "../assets/Soccer/Logos/ChelseaLight.png";
import ChicagoFireFCLogo from "../assets/Soccer/Logos/ChicagoFireFC.png";
import ChicagoFireFCLogoLight from "../assets/Soccer/Logos/ChicagoFireFCLight.png";
import ChinaLogo from "../assets/Soccer/Logos/China.png";
import ChinaLogoLight from "../assets/Soccer/Logos/ChinaLight.png";
import ColombiaLogo from "../assets/Soccer/Logos/Colombia.png";
import Colombia11337Logo from "../assets/Soccer/Logos/Colombia11337.png";
import Colombia11337LogoLight from "../assets/Soccer/Logos/Colombia11337Light.png";
import ColombiaLogoLight from "../assets/Soccer/Logos/ColombiaLight.png";
import ColoradoRapidsLogo from "../assets/Soccer/Logos/ColoradoRapids.png";
import ColoradoRapidsLogoLight from "../assets/Soccer/Logos/ColoradoRapidsLight.png";
import ColumbusCrewLogo from "../assets/Soccer/Logos/ColumbusCrew.png";
import ColumbusCrewLogoLight from "../assets/Soccer/Logos/ColumbusCrewLight.png";
import CongoDRLogo from "../assets/Soccer/Logos/CongoDR.png";
import CongoDRLogoLight from "../assets/Soccer/Logos/CongoDRLight.png";
import CostaRicaLogo from "../assets/Soccer/Logos/CostaRica.png";
import CostaRicaLogoLight from "../assets/Soccer/Logos/CostaRicaLight.png";
import CroatiaLogo from "../assets/Soccer/Logos/Croatia.png";
import CroatiaLogoLight from "../assets/Soccer/Logos/CroatiaLight.png";
import CrystalPalaceLogo from "../assets/Soccer/Logos/CrystalPalace.png";
import CrystalPalaceLogoLight from "../assets/Soccer/Logos/CrystalPalaceLight.png";
import CuracaoLogo from "../assets/Soccer/Logos/Curacao.png";
import CzechiaLogo from "../assets/Soccer/Logos/Czechia.png";
import CzechiaLogoLight from "../assets/Soccer/Logos/CzechiaLight.png";
import DCUnitedLogo from "../assets/Soccer/Logos/DCUnited.png";
import DCUnitedLogoLight from "../assets/Soccer/Logos/DCUnitedLight.png";
import DenmarkLogo from "../assets/Soccer/Logos/Denmark.png";
import DenmarkLogoLight from "../assets/Soccer/Logos/DenmarkLight.png";
import EcuadorLogo from "../assets/Soccer/Logos/Ecuador.png";
import EcuadorLogoLight from "../assets/Soccer/Logos/EcuadorLight.png";
import EgyptLogo from "../assets/Soccer/Logos/Egypt.png";
import EgyptLogoLight from "../assets/Soccer/Logos/EgyptLight.png";
import EintrachtFrankfurtLogo from "../assets/Soccer/Logos/EintrachtFrankfurt.png";
import EintrachtFrankfurtLogoLight from "../assets/Soccer/Logos/EintrachtFrankfurtLight.png";
import ElcheLogo from "../assets/Soccer/Logos/Elche.png";
import ElcheLogoLight from "../assets/Soccer/Logos/ElcheLight.png";
import EnglandLogo from "../assets/Soccer/Logos/England.png";
import England5159Logo from "../assets/Soccer/Logos/England5159.png";
import England5159LogoLight from "../assets/Soccer/Logos/England5159Light.png";
import EnglandLogoLight from "../assets/Soccer/Logos/EnglandLight.png";
import EspanyolLogo from "../assets/Soccer/Logos/Espanyol.png";
import EspanyolLogoLight from "../assets/Soccer/Logos/EspanyolLight.png";
import EvertonLogo from "../assets/Soccer/Logos/Everton.png";
import EvertonLogoLight from "../assets/Soccer/Logos/EvertonLight.png";
import FCAugsburgLogo from "../assets/Soccer/Logos/FCAugsburg.png";
import FCAugsburgLogoLight from "../assets/Soccer/Logos/FCAugsburgLight.png";
import FCCincinnatiLogo from "../assets/Soccer/Logos/FCCincinnati.png";
import FCCincinnatiLogoLight from "../assets/Soccer/Logos/FCCincinnatiLight.png";
import FCCologneLogo from "../assets/Soccer/Logos/FCCologne.png";
import FCCologneLogoLight from "../assets/Soccer/Logos/FCCologneLight.png";
import FCDallasLogo from "../assets/Soccer/Logos/FCDallas.png";
import FCDallasLogoLight from "../assets/Soccer/Logos/FCDallasLight.png";
import FranceLogo from "../assets/Soccer/Logos/France.png";
import France2755Logo from "../assets/Soccer/Logos/France2755.png";
import France2755LogoLight from "../assets/Soccer/Logos/France2755Light.png";
import FranceLogoLight from "../assets/Soccer/Logos/FranceLight.png";
import FulhamLogo from "../assets/Soccer/Logos/Fulham.png";
import FulhamLogoLight from "../assets/Soccer/Logos/FulhamLight.png";
import GermanyLogo from "../assets/Soccer/Logos/Germany.png";
import Germany2756Logo from "../assets/Soccer/Logos/Germany2756.png";
import Germany2756LogoLight from "../assets/Soccer/Logos/Germany2756Light.png";
import GermanyLogoLight from "../assets/Soccer/Logos/GermanyLight.png";
import GetafeLogo from "../assets/Soccer/Logos/Getafe.png";
import GetafeLogoLight from "../assets/Soccer/Logos/GetafeLight.png";
import GhanaLogo from "../assets/Soccer/Logos/Ghana.png";
import GhanaLogoLight from "../assets/Soccer/Logos/GhanaLight.png";
import GironaLogo from "../assets/Soccer/Logos/Girona.png";
import GironaLogoLight from "../assets/Soccer/Logos/GironaLight.png";
import HaitiLogo from "../assets/Soccer/Logos/Haiti.png";
import Haiti2891Logo from "../assets/Soccer/Logos/Haiti2891.png";
import Haiti2891LogoLight from "../assets/Soccer/Logos/Haiti2891Light.png";
import HaitiLogoLight from "../assets/Soccer/Logos/HaitiLight.png";
import HamburgSVLogo from "../assets/Soccer/Logos/HamburgSV.png";
import HamburgSVLogoLight from "../assets/Soccer/Logos/HamburgSVLight.png";
import HoustonDynamoFCLogo from "../assets/Soccer/Logos/HoustonDynamoFC.png";
import HoustonDynamoFCLogoLight from "../assets/Soccer/Logos/HoustonDynamoFCLight.png";
import InterMiamiCFLogo from "../assets/Soccer/Logos/InterMiamiCF.png";
import InterMiamiCFLogoLight from "../assets/Soccer/Logos/InterMiamiCFLight.png";
import IranLogo from "../assets/Soccer/Logos/Iran.png";
import IranLogoLight from "../assets/Soccer/Logos/IranLight.png";
import IraqLogo from "../assets/Soccer/Logos/Iraq.png";
import IraqLogoLight from "../assets/Soccer/Logos/IraqLight.png";
import ItalyLogo from "../assets/Soccer/Logos/Italy.png";
import ItalyLogoLight from "../assets/Soccer/Logos/ItalyLight.png";
import IvoryCoastLogo from "../assets/Soccer/Logos/IvoryCoast.png";
import IvoryCoastLogoLight from "../assets/Soccer/Logos/IvoryCoastLight.png";
import JamaicaLogo from "../assets/Soccer/Logos/Jamaica.png";
import JamaicaLogoLight from "../assets/Soccer/Logos/JamaicaLight.png";
import JapanLogo from "../assets/Soccer/Logos/Japan.png";
import Japan2758Logo from "../assets/Soccer/Logos/Japan2758.png";
import Japan2758LogoLight from "../assets/Soccer/Logos/Japan2758Light.png";
import JapanLogoLight from "../assets/Soccer/Logos/JapanLight.png";
import JordanLogo from "../assets/Soccer/Logos/Jordan.png";
import JordanLogoLight from "../assets/Soccer/Logos/JordanLight.png";
import LAFCLogo from "../assets/Soccer/Logos/LAFC.png";
import LAFCLogoLight from "../assets/Soccer/Logos/LAFCLight.png";
import LAGalaxyLogo from "../assets/Soccer/Logos/LAGalaxy.png";
import LAGalaxyLogoLight from "../assets/Soccer/Logos/LAGalaxyLight.png";
import LeedsUnitedLogo from "../assets/Soccer/Logos/LeedsUnited.png";
import LeedsUnitedLogoLight from "../assets/Soccer/Logos/LeedsUnitedLight.png";
import LevanteLogo from "../assets/Soccer/Logos/Levante.png";
import LevanteLogoLight from "../assets/Soccer/Logos/LevanteLight.png";
import LiverpoolLogo from "../assets/Soccer/Logos/Liverpool.png";
import LiverpoolLogoLight from "../assets/Soccer/Logos/LiverpoolLight.png";
import MainzLogo from "../assets/Soccer/Logos/Mainz.png";
import MainzLogoLight from "../assets/Soccer/Logos/MainzLight.png";
import MallorcaLogo from "../assets/Soccer/Logos/Mallorca.png";
import MallorcaLogoLight from "../assets/Soccer/Logos/MallorcaLight.png";
import ManchesterCityLogo from "../assets/Soccer/Logos/ManchesterCity.png";
import ManchesterCityLogoLight from "../assets/Soccer/Logos/ManchesterCityLight.png";
import ManchesterUnitedLogo from "../assets/Soccer/Logos/ManchesterUnited.png";
import ManchesterUnitedLogoLight from "../assets/Soccer/Logos/ManchesterUnitedLight.png";
import MexicoLogo from "../assets/Soccer/Logos/Mexico.png";
import MexicoLogoLight from "../assets/Soccer/Logos/MexicoLight.png";
import MinnesotaUnitedFCLogo from "../assets/Soccer/Logos/MinnesotaUnitedFC.png";
import MinnesotaUnitedFCLogoLight from "../assets/Soccer/Logos/MinnesotaUnitedFCLight.png";
import MoroccoLogo from "../assets/Soccer/Logos/Morocco.png";
import Morocco18221Logo from "../assets/Soccer/Logos/Morocco18221.png";
import Morocco18221LogoLight from "../assets/Soccer/Logos/Morocco18221Light.png";
import MoroccoLogoLight from "../assets/Soccer/Logos/MoroccoLight.png";
import NashvilleSCLogo from "../assets/Soccer/Logos/NashvilleSC.png";
import NashvilleSCLogoLight from "../assets/Soccer/Logos/NashvilleSCLight.png";
import NetherlandsLogo from "../assets/Soccer/Logos/Netherlands.png";
import Netherlands7151Logo from "../assets/Soccer/Logos/Netherlands7151.png";
import Netherlands7151LogoLight from "../assets/Soccer/Logos/Netherlands7151Light.png";
import NetherlandsLogoLight from "../assets/Soccer/Logos/NetherlandsLight.png";
import NewcastleUnitedLogo from "../assets/Soccer/Logos/NewcastleUnited.png";
import NewcastleUnitedLogoLight from "../assets/Soccer/Logos/NewcastleUnitedLight.png";
import NewEnglandRevolutionLogo from "../assets/Soccer/Logos/NewEnglandRevolution.png";
import NewEnglandRevolutionLogoLight from "../assets/Soccer/Logos/NewEnglandRevolutionLight.png";
import NewYorkCityFCLogo from "../assets/Soccer/Logos/NewYorkCityFC.png";
import NewYorkCityFCLogoLight from "../assets/Soccer/Logos/NewYorkCityFCLight.png";
import NewZealandLogo from "../assets/Soccer/Logos/NewZealand.png";
import NewZealand4153Logo from "../assets/Soccer/Logos/NewZealand4153.png";
import NewZealand4153LogoLight from "../assets/Soccer/Logos/NewZealand4153Light.png";
import NewZealandLogoLight from "../assets/Soccer/Logos/NewZealandLight.png";
import NigeriaLogo from "../assets/Soccer/Logos/Nigeria.png";
import NigeriaLogoLight from "../assets/Soccer/Logos/NigeriaLight.png";
import NorwayLogo from "../assets/Soccer/Logos/Norway.png";
import Norway2762Logo from "../assets/Soccer/Logos/Norway2762.png";
import Norway2762LogoLight from "../assets/Soccer/Logos/Norway2762Light.png";
import NorwayLogoLight from "../assets/Soccer/Logos/NorwayLight.png";
import NottinghamForestLogo from "../assets/Soccer/Logos/NottinghamForest.png";
import NottinghamForestLogoLight from "../assets/Soccer/Logos/NottinghamForestLight.png";
import OrlandoCitySCLogo from "../assets/Soccer/Logos/OrlandoCitySC.png";
import OrlandoCitySCLogoLight from "../assets/Soccer/Logos/OrlandoCitySCLight.png";
import OsasunaLogo from "../assets/Soccer/Logos/Osasuna.png";
import OsasunaLogoLight from "../assets/Soccer/Logos/OsasunaLight.png";
import PanamaLogo from "../assets/Soccer/Logos/Panama.png";
import Panama2895Logo from "../assets/Soccer/Logos/Panama2895.png";
import Panama2895LogoLight from "../assets/Soccer/Logos/Panama2895Light.png";
import PanamaLogoLight from "../assets/Soccer/Logos/PanamaLight.png";
import ParaguayLogo from "../assets/Soccer/Logos/Paraguay.png";
import ParaguayLogoLight from "../assets/Soccer/Logos/ParaguayLight.png";
import PhiladelphiaUnionLogo from "../assets/Soccer/Logos/PhiladelphiaUnion.png";
import PhiladelphiaUnionLogoLight from "../assets/Soccer/Logos/PhiladelphiaUnionLight.png";
import PhilippinesLogo from "../assets/Soccer/Logos/Philippines.png";
import PhilippinesLogoLight from "../assets/Soccer/Logos/PhilippinesLight.png";
import PortlandTimbersLogo from "../assets/Soccer/Logos/PortlandTimbers.png";
import PortlandTimbersLogoLight from "../assets/Soccer/Logos/PortlandTimbersLight.png";
import PortugalLogo from "../assets/Soccer/Logos/Portugal.png";
import Portugal9531Logo from "../assets/Soccer/Logos/Portugal9531.png";
import Portugal9531LogoLight from "../assets/Soccer/Logos/Portugal9531Light.png";
import PortugalLogoLight from "../assets/Soccer/Logos/PortugalLight.png";
import QatarLogo from "../assets/Soccer/Logos/Qatar.png";
import QatarLogoLight from "../assets/Soccer/Logos/QatarLight.png";
import RayoVallecanoLogo from "../assets/Soccer/Logos/RayoVallecano.png";
import RayoVallecanoLogoLight from "../assets/Soccer/Logos/RayoVallecanoLight.png";
import RBLeipzigLogo from "../assets/Soccer/Logos/RBLeipzig.png";
import RBLeipzigLogoLight from "../assets/Soccer/Logos/RBLeipzigLight.png";
import RealBetisLogo from "../assets/Soccer/Logos/RealBetis.png";
import RealBetisLogoLight from "../assets/Soccer/Logos/RealBetisLight.png";
import RealMadridLogo from "../assets/Soccer/Logos/RealMadrid.png";
import RealMadridLogoLight from "../assets/Soccer/Logos/RealMadridLight.png";
import RealOviedoLogo from "../assets/Soccer/Logos/RealOviedo.png";
import RealSaltLakeLogo from "../assets/Soccer/Logos/RealSaltLake.png";
import RealSaltLakeLogoLight from "../assets/Soccer/Logos/RealSaltLakeLight.png";
import RealSociedadLogo from "../assets/Soccer/Logos/RealSociedad.png";
import RealSociedadLogoLight from "../assets/Soccer/Logos/RealSociedadLight.png";
import RedBullNewYorkLogo from "../assets/Soccer/Logos/RedBullNewYork.png";
import RedBullNewYorkLogoLight from "../assets/Soccer/Logos/RedBullNewYorkLight.png";
import RepublicOfIrelandLogo from "../assets/Soccer/Logos/RepublicOfIreland.png";
import RepublicOfIrelandLogoLight from "../assets/Soccer/Logos/RepublicOfIrelandLight.png";
import SanDiegoFCLogo from "../assets/Soccer/Logos/SanDiegoFC.png";
import SanDiegoFCLogoLight from "../assets/Soccer/Logos/SanDiegoFCLight.png";
import SanJoseEarthquakesLogo from "../assets/Soccer/Logos/SanJoseEarthquakes.png";
import SanJoseEarthquakesLogoLight from "../assets/Soccer/Logos/SanJoseEarthquakesLight.png";
import SaudiArabiaLogo from "../assets/Soccer/Logos/SaudiArabia.png";
import SaudiArabiaLogoLight from "../assets/Soccer/Logos/SaudiArabiaLight.png";
import SCFreiburgLogo from "../assets/Soccer/Logos/SCFreiburg.png";
import SCFreiburgLogoLight from "../assets/Soccer/Logos/SCFreiburgLight.png";
import ScotlandLogo from "../assets/Soccer/Logos/Scotland.png";
import ScotlandLogoLight from "../assets/Soccer/Logos/ScotlandLight.png";
import SeattleSoundersFCLogo from "../assets/Soccer/Logos/SeattleSoundersFC.png";
import SeattleSoundersFCLogoLight from "../assets/Soccer/Logos/SeattleSoundersFCLight.png";
import SenegalLogo from "../assets/Soccer/Logos/Senegal.png";
import SenegalLogoLight from "../assets/Soccer/Logos/SenegalLight.png";
import SevillaLogo from "../assets/Soccer/Logos/Sevilla.png";
import SevillaLogoLight from "../assets/Soccer/Logos/SevillaLight.png";
import SouthAfricaLogo from "../assets/Soccer/Logos/SouthAfrica.png";
import SouthAfrica13313Logo from "../assets/Soccer/Logos/SouthAfrica13313.png";
import SouthAfrica13313LogoLight from "../assets/Soccer/Logos/SouthAfrica13313Light.png";
import SouthAfricaLogoLight from "../assets/Soccer/Logos/SouthAfricaLight.png";
import SouthKoreaLogo from "../assets/Soccer/Logos/SouthKorea.png";
import SouthKorea17639Logo from "../assets/Soccer/Logos/SouthKorea17639.png";
import SouthKorea17639LogoLight from "../assets/Soccer/Logos/SouthKorea17639Light.png";
import SouthKoreaLogoLight from "../assets/Soccer/Logos/SouthKoreaLight.png";
import SpainLogo from "../assets/Soccer/Logos/Spain.png";
import Spain17640Logo from "../assets/Soccer/Logos/Spain17640.png";
import Spain17640LogoLight from "../assets/Soccer/Logos/Spain17640Light.png";
import SpainLogoLight from "../assets/Soccer/Logos/SpainLight.png";
import SportingKansasCityLogo from "../assets/Soccer/Logos/SportingKansasCity.png";
import SportingKansasCityLogoLight from "../assets/Soccer/Logos/SportingKansasCityLight.png";
import StLouisCITYSCLogo from "../assets/Soccer/Logos/StLouisCITYSC.png";
import StLouisCITYSCLogoLight from "../assets/Soccer/Logos/StLouisCITYSCLight.png";
import StPauliLogo from "../assets/Soccer/Logos/StPauli.png";
import StPauliLogoLight from "../assets/Soccer/Logos/StPauliLight.png";
import SunderlandLogo from "../assets/Soccer/Logos/Sunderland.png";
import SunderlandLogoLight from "../assets/Soccer/Logos/SunderlandLight.png";
import SwedenLogo from "../assets/Soccer/Logos/Sweden.png";
import Sweden2764Logo from "../assets/Soccer/Logos/Sweden2764.png";
import Sweden2764LogoLight from "../assets/Soccer/Logos/Sweden2764Light.png";
import SwedenLogoLight from "../assets/Soccer/Logos/SwedenLight.png";
import SwitzerlandLogo from "../assets/Soccer/Logos/Switzerland.png";
import Switzerland17641Logo from "../assets/Soccer/Logos/Switzerland17641.png";
import Switzerland17641LogoLight from "../assets/Soccer/Logos/Switzerland17641Light.png";
import SwitzerlandLogoLight from "../assets/Soccer/Logos/SwitzerlandLight.png";
import Team1FCHeidenheim1846Logo from "../assets/Soccer/Logos/Team1FCHeidenheim1846.png";
import Team1FCHeidenheim1846LogoLight from "../assets/Soccer/Logos/Team1FCHeidenheim1846Light.png";
import Team1FCUnionBerlinLogo from "../assets/Soccer/Logos/Team1FCUnionBerlin.png";
import Team1FCUnionBerlinLogoLight from "../assets/Soccer/Logos/Team1FCUnionBerlinLight.png";
import TorontoFCLogo from "../assets/Soccer/Logos/TorontoFC.png";
import TorontoFCLogoLight from "../assets/Soccer/Logos/TorontoFCLight.png";
import TottenhamHotspurLogo from "../assets/Soccer/Logos/TottenhamHotspur.png";
import TottenhamHotspurLogoLight from "../assets/Soccer/Logos/TottenhamHotspurLight.png";
import TSGHoffenheimLogo from "../assets/Soccer/Logos/TSGHoffenheim.png";
import TSGHoffenheimLogoLight from "../assets/Soccer/Logos/TSGHoffenheimLight.png";
import TunisiaLogo from "../assets/Soccer/Logos/Tunisia.png";
import TunisiaLogoLight from "../assets/Soccer/Logos/TunisiaLight.png";
import TurkiyeLogo from "../assets/Soccer/Logos/Turkiye.png";
import TurkiyeLogoLight from "../assets/Soccer/Logos/TurkiyeLight.png";
import UnitedStatesLogo from "../assets/Soccer/Logos/UnitedStates.png";
import UnitedStates2765Logo from "../assets/Soccer/Logos/UnitedStates2765.png";
import UnitedStates2765LogoLight from "../assets/Soccer/Logos/UnitedStates2765Light.png";
import UnitedStatesLogoLight from "../assets/Soccer/Logos/UnitedStatesLight.png";
import UruguayLogo from "../assets/Soccer/Logos/Uruguay.png";
import UruguayLogoLight from "../assets/Soccer/Logos/UruguayLight.png";
import UzbekistanLogo from "../assets/Soccer/Logos/Uzbekistan.png";
import UzbekistanLogoLight from "../assets/Soccer/Logos/UzbekistanLight.png";
import ValenciaLogo from "../assets/Soccer/Logos/Valencia.png";
import ValenciaLogoLight from "../assets/Soccer/Logos/ValenciaLight.png";
import VancouverWhitecapsLogo from "../assets/Soccer/Logos/VancouverWhitecaps.png";
import VancouverWhitecapsLogoLight from "../assets/Soccer/Logos/VancouverWhitecapsLight.png";
import VfBStuttgartLogo from "../assets/Soccer/Logos/VfBStuttgart.png";
import VfBStuttgartLogoLight from "../assets/Soccer/Logos/VfBStuttgartLight.png";
import VfLWolfsburgLogo from "../assets/Soccer/Logos/VfLWolfsburg.png";
import VfLWolfsburgLogoLight from "../assets/Soccer/Logos/VfLWolfsburgLight.png";
import VietnamLogo from "../assets/Soccer/Logos/Vietnam.png";
import VietnamLogoLight from "../assets/Soccer/Logos/VietnamLight.png";
import VillarrealLogo from "../assets/Soccer/Logos/Villarreal.png";
import VillarrealLogoLight from "../assets/Soccer/Logos/VillarrealLight.png";
import WerderBremenLogo from "../assets/Soccer/Logos/WerderBremen.png";
import WerderBremenLogoLight from "../assets/Soccer/Logos/WerderBremenLight.png";
import WestHamUnitedLogo from "../assets/Soccer/Logos/WestHamUnited.png";
import WestHamUnitedLogoLight from "../assets/Soccer/Logos/WestHamUnitedLight.png";
import WolverhamptonWanderersLogo from "../assets/Soccer/Logos/WolverhamptonWanderers.png";
import WolverhamptonWanderersLogoLight from "../assets/Soccer/Logos/WolverhamptonWanderersLight.png";
import ZambiaLogo from "../assets/Soccer/Logos/Zambia.png";
import ZambiaLogoLight from "../assets/Soccer/Logos/ZambiaLight.png";

export const soccerTeams: Team[] = [
  {
    id: 21812,
    espnId: 21812,
    fullName: "St. Louis CITY SC",
    code: "STL",
    city: "St. Louis",
    location: "St. Louis, MO",
    coach: "Yoann Damet",
    owner: "Carolyn Kindle",
    established: 2019,
    logo: StLouisCITYSCLogo,
    logoLight: StLouisCITYSCLogoLight,
    name: "St. Louis CITY SC",
    shortName: "St. Louis",
    color: "#ec1458",
    secondaryColor: "#001544",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7318,
    espnId: 7318,
    fullName: "Toronto FC",
    code: "TOR",
    city: "Toronto",
    location: "Toronto, ON",
    coach: "Robin Fraser",
    owner: "Maple Leaf Sports & Entertainment",
    established: 2005,
    logo: TorontoFCLogo,
    logoLight: TorontoFCLogoLight,
    name: "Toronto FC",
    shortName: "Toronto",
    color: "#aa182c",
    secondaryColor: "#a2a9ad",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9727,
    espnId: 9727,
    fullName: "Vancouver Whitecaps",
    code: "VAN",
    city: "Vancouver",
    location: "Vancouver, BC",
    coach: "Jesper Sørensen",
    owner: "Greg Kerfoot, Steve Luczo, Jeff Mallett, Steve Nash",
    established: 1974,
    logo: VancouverWhitecapsLogo,
    logoLight: VancouverWhitecapsLogoLight,
    name: "Vancouver Whitecaps",
    shortName: "Vancouver",
    color: "#ffffff",
    secondaryColor: "#12284c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 624,
    espnId: 624,
    fullName: "Algeria",
    code: "ALG",
    city: null,
    location: null,
    established: 0,
    logo: AlgeriaLogo,
    logoLight: AlgeriaLogoLight,
    name: "Algeria",
    shortName: "Algeria",
    color: "#5bbd19",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 202,
    espnId: 202,
    fullName: "Argentina",
    code: "ARG",
    city: null,
    location: null,
    established: 0,
    logo: ArgentinaLogo,
    logoLight: ArgentinaLogoLight,
    name: "Argentina",
    shortName: "Argentina",
    color: "#74acdf",
    secondaryColor: "#173e69",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 628,
    espnId: 628,
    fullName: "Australia",
    code: "AUS",
    city: null,
    location: null,
    established: 0,
    logo: AustraliaLogo,
    logoLight: AustraliaLogoLight,
    name: "Australia",
    shortName: "Australia",
    color: "#2a2d7c",
    secondaryColor: "#ed2f31",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 474,
    espnId: 474,
    fullName: "Austria",
    code: "AUT",
    city: "Vienna",
    location: "Vienna, Austria",
    established: 0,
    logo: AustriaLogo,
    logoLight: AustriaLogoLight,
    name: "Austria",
    shortName: "Austria",
    color: "#d72b2c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 459,
    espnId: 459,
    fullName: "Belgium",
    code: "BEL",
    city: "Brussels",
    location: "Brussels, Belgium",
    established: 0,
    logo: BelgiumLogo,
    logoLight: BelgiumLogoLight,
    name: "Belgium",
    shortName: "Belgium",
    color: "#ef3340",
    secondaryColor: "#d7e9f6",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 452,
    espnId: 452,
    fullName: "Bosnia-Herzegovina",
    code: "BIH",
    city: null,
    location: null,
    established: 0,
    logo: BosniaHerzegovinaLogo,
    logoLight: BosniaHerzegovinaLogoLight,
    name: "Bosnia-Herzegovina",
    shortName: "Bosnia-Herz",
    color: "#112855",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 205,
    espnId: 205,
    fullName: "Brazil",
    code: "BRA",
    city: null,
    location: null,
    established: 0,
    logo: BrazilLogo,
    logoLight: BrazilLogoLight,
    name: "Brazil",
    shortName: "Brazil",
    color: "#fee000",
    secondaryColor: "#009c37",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 206,
    espnId: 206,
    fullName: "Canada",
    code: "CAN",
    city: null,
    location: null,
    established: 0,
    logo: CanadaLogo,
    logoLight: CanadaLogoLight,
    name: "Canada",
    shortName: "Canada",
    color: "#ed2224",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2597,
    espnId: 2597,
    fullName: "Cape Verde",
    code: "CPV",
    city: "Praia",
    location: "Praia, Cape Verde",
    established: 0,
    logo: CapeVerdeLogo,
    logoLight: CapeVerdeLogoLight,
    name: "Cape Verde",
    shortName: "Cape Verde",
    color: "#0000ff",
    secondaryColor: "#EF3340",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 208,
    espnId: 208,
    fullName: "Colombia",
    code: "COL",
    city: "Barranquilla",
    location: "Barranquilla, Colombia",
    established: 0,
    logo: ColombiaLogo,
    logoLight: ColombiaLogoLight,
    name: "Colombia",
    shortName: "Colombia",
    color: "#fbd632",
    secondaryColor: "#21418c",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2850,
    espnId: 2850,
    fullName: "Congo DR",
    code: "COD",
    city: "Kinshasa",
    location: "Kinshasa, DR Congo",
    established: 0,
    logo: CongoDRLogo,
    logoLight: CongoDRLogoLight,
    name: "Congo DR",
    shortName: "Congo DR",
    color: "#418fde",
    secondaryColor: "#C60000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 477,
    espnId: 477,
    fullName: "Croatia",
    code: "CRO",
    city: null,
    location: null,
    established: 0,
    logo: CroatiaLogo,
    logoLight: CroatiaLogoLight,
    name: "Croatia",
    shortName: "Croatia",
    color: "#ff0000",
    secondaryColor: "#0c2fff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 11678,
    espnId: 11678,
    fullName: "Curaçao",
    code: "CUW",
    city: "Willemstad",
    location: "Willemstad, Curaçao",
    established: 0,
    logo: CuracaoLogo,
    logoLight: CuracaoLogo,
    name: "Curaçao",
    shortName: "Curaçao",
    color: "#0537e4",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 450,
    espnId: 450,
    fullName: "Czechia",
    code: "CZE",
    city: null,
    location: null,
    established: 0,
    logo: CzechiaLogo,
    logoLight: CzechiaLogoLight,
    name: "Czechia",
    shortName: "Czechia",
    color: "#d7141a",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 209,
    espnId: 209,
    fullName: "Ecuador",
    code: "ECU",
    city: null,
    location: null,
    established: 0,
    logo: EcuadorLogo,
    logoLight: EcuadorLogoLight,
    name: "Ecuador",
    shortName: "Ecuador",
    color: "#ffdd00",
    secondaryColor: "#034ea2",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2620,
    espnId: 2620,
    fullName: "Egypt",
    code: "EGY",
    city: "Cairo",
    location: "Cairo, Egypt",
    established: 0,
    logo: EgyptLogo,
    logoLight: EgyptLogoLight,
    name: "Egypt",
    shortName: "Egypt",
    color: "#D20300",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 448,
    espnId: 448,
    fullName: "England",
    code: "ENG",
    city: "London",
    location: "London, England",
    established: 0,
    logo: EnglandLogo,
    logoLight: EnglandLogoLight,
    name: "England",
    shortName: "England",
    color: "#ffffff",
    secondaryColor: "#EA1F29",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 478,
    espnId: 478,
    fullName: "France",
    code: "FRA",
    city: "Saint-Denis",
    location: "Saint-Denis, France",
    established: 0,
    logo: FranceLogo,
    logoLight: FranceLogoLight,
    name: "France",
    shortName: "France",
    color: "#0c2fff",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 481,
    espnId: 481,
    fullName: "Germany",
    code: "GER",
    city: null,
    location: null,
    established: 0,
    logo: GermanyLogo,
    logoLight: GermanyLogoLight,
    name: "Germany",
    shortName: "Germany",
    color: "#000000",
    secondaryColor: "#db41a9",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4469,
    espnId: 4469,
    fullName: "Ghana",
    code: "GHA",
    city: null,
    location: null,
    established: 0,
    logo: GhanaLogo,
    logoLight: GhanaLogoLight,
    name: "Ghana",
    shortName: "Ghana",
    color: "#ce2931",
    secondaryColor: "#fbd632",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2654,
    espnId: 2654,
    fullName: "Haiti",
    code: "HAI",
    city: null,
    location: null,
    established: 0,
    logo: HaitiLogo,
    logoLight: HaitiLogoLight,
    name: "Haiti",
    shortName: "Haiti",
    color: "#0033a0",
    secondaryColor: "#D20300",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 469,
    espnId: 469,
    fullName: "Iran",
    code: "IRN",
    city: "Tehran",
    location: "Tehran, Iran",
    established: 0,
    logo: IranLogo,
    logoLight: IranLogoLight,
    name: "Iran",
    shortName: "Iran",
    color: "#da0000",
    secondaryColor: "#239f40",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4375,
    espnId: 4375,
    fullName: "Iraq",
    code: "IRQ",
    city: null,
    location: null,
    established: 0,
    logo: IraqLogo,
    logoLight: IraqLogoLight,
    name: "Iraq",
    shortName: "Iraq",
    color: "#00843d",
    secondaryColor: "#CE1126",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4789,
    espnId: 4789,
    fullName: "Ivory Coast",
    code: "CIV",
    city: null,
    location: null,
    established: 0,
    logo: IvoryCoastLogo,
    logoLight: IvoryCoastLogoLight,
    name: "Ivory Coast",
    shortName: "Ivory Coast",
    color: "#d48c00",
    secondaryColor: "#5bbd19",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 627,
    espnId: 627,
    fullName: "Japan",
    code: "JPN",
    city: null,
    location: null,
    established: 0,
    logo: JapanLogo,
    logoLight: JapanLogoLight,
    name: "Japan",
    shortName: "Japan",
    color: "#ed1c24",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2917,
    espnId: 2917,
    fullName: "Jordan",
    code: "JOR",
    city: "Amman",
    location: "Amman, Jordan",
    established: 0,
    logo: JordanLogo,
    logoLight: JordanLogoLight,
    name: "Jordan",
    shortName: "Jordan",
    color: "#E70000",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 203,
    espnId: 203,
    fullName: "Mexico",
    code: "MEX",
    city: "Mexico City",
    location: "Mexico City, Mexico",
    established: 0,
    logo: MexicoLogo,
    logoLight: MexicoLogoLight,
    name: "Mexico",
    shortName: "Mexico",
    color: "#006847",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2869,
    espnId: 2869,
    fullName: "Morocco",
    code: "MAR",
    city: null,
    location: null,
    established: 0,
    logo: MoroccoLogo,
    logoLight: MoroccoLogoLight,
    name: "Morocco",
    shortName: "Morocco",
    color: "#009060",
    secondaryColor: "#df2027",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 449,
    espnId: 449,
    fullName: "Netherlands",
    code: "NED",
    city: null,
    location: null,
    established: 0,
    logo: NetherlandsLogo,
    logoLight: NetherlandsLogoLight,
    name: "Netherlands",
    shortName: "Netherlands",
    color: "#fb5d00",
    secondaryColor: "#010080",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2666,
    espnId: 2666,
    fullName: "New Zealand",
    code: "NZL",
    city: null,
    location: null,
    established: 0,
    logo: NewZealandLogo,
    logoLight: NewZealandLogoLight,
    name: "New Zealand",
    shortName: "New Zealand",
    color: "#273476",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 464,
    espnId: 464,
    fullName: "Norway",
    code: "NOR",
    city: "Oslo",
    location: "Oslo, Norway",
    established: 0,
    logo: NorwayLogo,
    logoLight: NorwayLogoLight,
    name: "Norway",
    shortName: "Norway",
    color: "#ef2b2d",
    secondaryColor: "#002868",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2659,
    espnId: 2659,
    fullName: "Panama",
    code: "PAN",
    city: "Panama City",
    location: "Panama City, Panama",
    established: 0,
    logo: PanamaLogo,
    logoLight: PanamaLogoLight,
    name: "Panama",
    shortName: "Panama",
    color: "#d21034",
    secondaryColor: "#005293",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 210,
    espnId: 210,
    fullName: "Paraguay",
    code: "PAR",
    city: "Asunción",
    location: "Asunción, Paraguay",
    established: 0,
    logo: ParaguayLogo,
    logoLight: ParaguayLogoLight,
    name: "Paraguay",
    shortName: "Paraguay",
    color: "#ea2300",
    secondaryColor: "#0c2fff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 482,
    espnId: 482,
    fullName: "Portugal",
    code: "POR",
    city: null,
    location: null,
    established: 0,
    logo: PortugalLogo,
    logoLight: PortugalLogoLight,
    name: "Portugal",
    shortName: "Portugal",
    color: "#da291c",
    secondaryColor: "#d7e9f6",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4398,
    espnId: 4398,
    fullName: "Qatar",
    code: "QAT",
    city: null,
    location: null,
    established: 0,
    logo: QatarLogo,
    logoLight: QatarLogoLight,
    name: "Qatar",
    shortName: "Qatar",
    color: "#691a40",
    secondaryColor: "#691a40",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 655,
    espnId: 655,
    fullName: "Saudi Arabia",
    code: "KSA",
    city: null,
    location: null,
    established: 0,
    logo: SaudiArabiaLogo,
    logoLight: SaudiArabiaLogoLight,
    name: "Saudi Arabia",
    shortName: "Saudi Arabia",
    color: "#dddddd",
    secondaryColor: "#006233",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 580,
    espnId: 580,
    fullName: "Scotland",
    code: "SCO",
    city: "Glasgow",
    location: "Glasgow, Scotland",
    established: 0,
    logo: ScotlandLogo,
    logoLight: ScotlandLogoLight,
    name: "Scotland",
    shortName: "Scotland",
    color: "#1a2d69",
    secondaryColor: "#dcf5f7",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 654,
    espnId: 654,
    fullName: "Senegal",
    code: "SEN",
    city: "Diamniadio",
    location: "Diamniadio, Senegal",
    established: 0,
    logo: SenegalLogo,
    logoLight: SenegalLogoLight,
    name: "Senegal",
    shortName: "Senegal",
    color: "#00853f",
    secondaryColor: "#fdef42",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 467,
    espnId: 467,
    fullName: "South Africa",
    code: "RSA",
    city: "Johannesburg",
    location: "Johannesburg, South Africa",
    established: 0,
    logo: SouthAfricaLogo,
    logoLight: SouthAfricaLogoLight,
    name: "South Africa",
    shortName: "South Africa",
    color: "#087d5a",
    secondaryColor: "#fbb516",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 451,
    espnId: 451,
    fullName: "South Korea",
    code: "KOR",
    city: "Seoul",
    location: "Seoul, South Korea",
    established: 0,
    logo: SouthKoreaLogo,
    logoLight: SouthKoreaLogoLight,
    name: "South Korea",
    shortName: "South Korea",
    color: "#ce2028",
    secondaryColor: "#1e4384",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 164,
    espnId: 164,
    fullName: "Spain",
    code: "ESP",
    city: null,
    location: null,
    established: 0,
    logo: SpainLogo,
    logoLight: SpainLogoLight,
    name: "Spain",
    shortName: "Spain",
    color: "#c60b1e",
    secondaryColor: "#f1ff91",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 466,
    espnId: 466,
    fullName: "Sweden",
    code: "SWE",
    city: "Solna",
    location: "Solna, Sweden",
    established: 0,
    logo: SwedenLogo,
    logoLight: SwedenLogoLight,
    name: "Sweden",
    shortName: "Sweden",
    color: "#fecb00",
    secondaryColor: "#006aa7",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 475,
    espnId: 475,
    fullName: "Switzerland",
    code: "SUI",
    city: null,
    location: null,
    established: 0,
    logo: SwitzerlandLogo,
    logoLight: SwitzerlandLogoLight,
    name: "Switzerland",
    shortName: "Switzerland",
    color: "#d72b2c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 659,
    espnId: 659,
    fullName: "Tunisia",
    code: "TUN",
    city: "Radès",
    location: "Radès, Tunisia",
    established: 0,
    logo: TunisiaLogo,
    logoLight: TunisiaLogoLight,
    name: "Tunisia",
    shortName: "Tunisia",
    color: "#D20300",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 465,
    espnId: 465,
    fullName: "Türkiye",
    code: "TUR",
    city: null,
    location: null,
    established: 0,
    logo: TurkiyeLogo,
    logoLight: TurkiyeLogoLight,
    name: "Türkiye",
    shortName: "Türkiye",
    color: "#ffffff",
    secondaryColor: "#ef3340",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 660,
    espnId: 660,
    fullName: "United States",
    code: "USA",
    city: null,
    location: null,
    established: 0,
    logo: UnitedStatesLogo,
    logoLight: UnitedStatesLogoLight,
    name: "United States",
    shortName: "USA",
    color: "#213065",
    secondaryColor: "#d42339",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 212,
    espnId: 212,
    fullName: "Uruguay",
    code: "URU",
    city: "Montevideo",
    location: "Montevideo, Uruguay",
    established: 0,
    logo: UruguayLogo,
    logoLight: UruguayLogoLight,
    name: "Uruguay",
    shortName: "Uruguay",
    color: "#003da5",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2570,
    espnId: 2570,
    fullName: "Uzbekistan",
    code: "UZB",
    city: "Tashkent",
    location: "Tashkent, Uzbekistan",
    established: 0,
    logo: UzbekistanLogo,
    logoLight: UzbekistanLogoLight,
    name: "Uzbekistan",
    shortName: "Uzbekistan",
    color: "#0081d6",
    secondaryColor: "#1EB53A",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 18418,
    espnId: 18418,
    fullName: "Atlanta United FC",
    code: "ATL",
    city: "Atlanta",
    location: "Atlanta, GA",
    coach: "Gerardo Martino",
    owner: "Arthur Blank",
    established: 2014,
    logo: AtlantaUnitedFCLogo,
    logoLight: AtlantaUnitedFCLogoLight,
    name: "Atlanta United FC",
    shortName: "Atlanta",
    color: "#9d2235",
    secondaryColor: "#aa9767",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 20906,
    espnId: 20906,
    fullName: "Austin FC",
    code: "ATX",
    city: "Austin",
    location: "Austin, TX",
    coach: "Davy Arnaud (interim)",
    owner: "Two Oak Ventures",
    established: 2018,
    logo: AustinFCLogo,
    logoLight: AustinFCLogoLight,
    name: "Austin FC",
    shortName: "Austin",
    color: "#00b140",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9720,
    espnId: 9720,
    fullName: "CF Montréal",
    code: "MTL",
    city: "Montreal",
    location: "Montreal, QC",
    coach: "Philippe Eullaffroy (interim)",
    owner: "Joey Saputo",
    established: 1992,
    logo: CFMontrealLogo,
    logoLight: CFMontrealLogoLight,
    name: "CF Montréal",
    shortName: "CF Montréal",
    color: "#003da6",
    secondaryColor: "#c1c5c8",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 21300,
    espnId: 21300,
    fullName: "Charlotte FC",
    code: "CLT",
    city: "Charlotte",
    location: "Charlotte, NC",
    coach: "Dean Smith",
    owner: "David Tepper",
    established: 2019,
    logo: CharlotteFCLogo,
    logoLight: CharlotteFCLogoLight,
    name: "Charlotte FC",
    shortName: "Charlotte",
    color: "#0085ca",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 182,
    espnId: 182,
    fullName: "Chicago Fire FC",
    code: "CHI",
    city: "Chicago",
    location: "Chicago, IL",
    coach: "Gregg Berhalter",
    owner: "Joe Mansueto",
    established: 1997,
    logo: ChicagoFireFCLogo,
    logoLight: ChicagoFireFCLogoLight,
    name: "Chicago Fire FC",
    shortName: "Chicago",
    color: "#7ccdef",
    secondaryColor: "#ff0000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 184,
    espnId: 184,
    fullName: "Colorado Rapids",
    code: "COL",
    city: "Commerce City",
    location: "Commerce City, CO",
    coach: "Matt Wells",
    owner: "Kroenke Sports & Entertainment",
    established: 1995,
    logo: ColoradoRapidsLogo,
    logoLight: ColoradoRapidsLogoLight,
    name: "Colorado Rapids",
    shortName: "Colorado",
    color: "#8a2432",
    secondaryColor: "#8ab7e9",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 183,
    espnId: 183,
    fullName: "Columbus Crew",
    code: "CLB",
    city: "Columbus",
    location: "Columbus, OH",
    coach: "Henrik Rydström",
    owner: "Haslam Sports Group",
    established: 1994,
    logo: ColumbusCrewLogo,
    logoLight: ColumbusCrewLogoLight,
    name: "Columbus Crew",
    shortName: "Columbus",
    color: "#000000",
    secondaryColor: "#fedd00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 193,
    espnId: 193,
    fullName: "D.C. United",
    code: "DC",
    city: "Washington",
    location: "Washington, DC",
    coach: "René Weiler",
    owner: "D.C. United Holdings",
    established: 1994,
    logo: DCUnitedLogo,
    logoLight: DCUnitedLogoLight,
    name: "D.C. United",
    shortName: "D.C. United",
    color: "#000000",
    secondaryColor: "#d61018",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18267,
    espnId: 18267,
    fullName: "FC Cincinnati",
    code: "CIN",
    city: "Cincinnati",
    location: "Cincinnati, OH",
    coach: "Pat Noonan",
    owner: "Carl Lindner III",
    established: 2015,
    logo: FCCincinnatiLogo,
    logoLight: FCCincinnatiLogoLight,
    name: "FC Cincinnati",
    shortName: "Cincinnati",
    color: "#003087",
    secondaryColor: "#fe5000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 185,
    espnId: 185,
    fullName: "FC Dallas",
    code: "DAL",
    city: "Frisco",
    location: "Frisco, TX",
    coach: "Eric Quill",
    owner: "Hunt Sports Group",
    established: 1995,
    logo: FCDallasLogo,
    logoLight: FCDallasLogoLight,
    name: "FC Dallas",
    shortName: "Dallas",
    color: "#c6093b",
    secondaryColor: "#001f5b",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 6077,
    espnId: 6077,
    fullName: "Houston Dynamo FC",
    code: "HOU",
    city: "Houston",
    location: "Houston, TX",
    coach: "Ben Olsen",
    owner: "Ted Segal",
    established: 2005,
    logo: HoustonDynamoFCLogo,
    logoLight: HoustonDynamoFCLogoLight,
    name: "Houston Dynamo FC",
    shortName: "Houston",
    color: "#ff6b00",
    secondaryColor: "#101820",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 20232,
    espnId: 20232,
    fullName: "Inter Miami CF",
    code: "MIA",
    city: "Miami",
    location: "Miami, FL",
    coach: "Guillermo Hoyos",
    owner: "David Beckham, Jorge Mas, Jose Mas",
    established: 2018,
    logo: InterMiamiCFLogo,
    logoLight: InterMiamiCFLogoLight,
    name: "Inter Miami CF",
    shortName: "Miami",
    color: "#231f20",
    secondaryColor: "#f7b5cd",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 187,
    espnId: 187,
    fullName: "LA Galaxy",
    code: "LA",
    city: "Carson",
    location: "Carson, CA",
    coach: "Greg Vanney",
    owner: "Anschutz Entertainment Group",
    established: 1994,
    logo: LAGalaxyLogo,
    logoLight: LAGalaxyLogoLight,
    name: "LA Galaxy",
    shortName: "LA Galaxy",
    color: "#00235d",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18966,
    espnId: 18966,
    fullName: "LAFC",
    code: "LAFC",
    city: "Los Angeles",
    location: "Los Angeles, CA",
    coach: "Marc Dos Santos",
    owner: "Bennett Rosenthal, Brandon Beck, Larry Berg",
    established: 2014,
    logo: LAFCLogo,
    logoLight: LAFCLogoLight,
    name: "LAFC",
    shortName: "LAFC",
    color: "#000000",
    secondaryColor: "#c7a36f",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17362,
    espnId: 17362,
    fullName: "Minnesota United FC",
    code: "MIN",
    city: "Saint Paul",
    location: "Saint Paul, MN",
    coach: "Cameron Knowles",
    owner: "Bill McGuire",
    established: 2015,
    logo: MinnesotaUnitedFCLogo,
    logoLight: MinnesotaUnitedFCLogoLight,
    name: "Minnesota United FC",
    shortName: "Minnesota",
    color: "#000000",
    secondaryColor: "#9bcde4",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18986,
    espnId: 18986,
    fullName: "Nashville SC",
    code: "NSH",
    city: "Nashville",
    location: "Nashville, TN",
    coach: "B. J. Callaghan",
    owner: "John R. Ingram",
    established: 2016,
    logo: NashvilleSCLogo,
    logoLight: NashvilleSCLogoLight,
    name: "Nashville SC",
    shortName: "Nashville",
    color: "#ece83a",
    secondaryColor: "#1f1646",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 189,
    espnId: 189,
    fullName: "New England Revolution",
    code: "NE",
    city: "Foxborough",
    location: "Foxborough, MA",
    coach: "Marko Mitrović",
    owner: "Robert Kraft",
    established: 1994,
    logo: NewEnglandRevolutionLogo,
    logoLight: NewEnglandRevolutionLogoLight,
    name: "New England Revolution",
    shortName: "New England",
    color: "#022166",
    secondaryColor: "#ce0e2d",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17606,
    espnId: 17606,
    fullName: "New York City FC",
    code: "NYC",
    city: "New York",
    location: "New York, NY",
    coach: "Pascal Jansen",
    owner: "City Football Group, Yankee Global Enterprises",
    established: 2013,
    logo: NewYorkCityFCLogo,
    logoLight: NewYorkCityFCLogoLight,
    name: "New York City FC",
    shortName: "NYCFC",
    color: "#9fd2ff",
    secondaryColor: "#000229",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 12011,
    espnId: 12011,
    fullName: "Orlando City SC",
    code: "ORL",
    city: "Orlando",
    location: "Orlando, FL",
    coach: "Martín Perelman (interim)",
    owner: "Zygi Wilf, Mark Wilf, Lise Wilf",
    established: 2010,
    logo: OrlandoCitySCLogo,
    logoLight: OrlandoCitySCLogoLight,
    name: "Orlando City SC",
    shortName: "Orlando",
    color: "#60269e",
    secondaryColor: "#f0d283",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 10739,
    espnId: 10739,
    fullName: "Philadelphia Union",
    code: "PHI",
    city: "Chester",
    location: "Chester, PA",
    coach: "Ryan Richter (interim)",
    owner: "Jay Sugarman",
    established: 2008,
    logo: PhiladelphiaUnionLogo,
    logoLight: PhiladelphiaUnionLogoLight,
    name: "Philadelphia Union",
    shortName: "Philadelphia",
    color: "#051f31",
    secondaryColor: "#e0d0a6",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9723,
    espnId: 9723,
    fullName: "Portland Timbers",
    code: "POR",
    city: "Portland",
    location: "Portland, OR",
    coach: "Phil Neville",
    owner: "Peregrine Sports",
    established: 2009,
    logo: PortlandTimbersLogo,
    logoLight: PortlandTimbersLogoLight,
    name: "Portland Timbers",
    shortName: "Portland",
    color: "#2c5234",
    secondaryColor: "#c99700",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 4771,
    espnId: 4771,
    fullName: "Real Salt Lake",
    code: "RSL",
    city: "Sandy",
    location: "Sandy, UT",
    coach: "Pablo Mastroeni",
    owner: "David Blitzer, Ryan Smith",
    established: 2004,
    logo: RealSaltLakeLogo,
    logoLight: RealSaltLakeLogoLight,
    name: "Real Salt Lake",
    shortName: "Salt Lake",
    color: "#a32035",
    secondaryColor: "#daa900",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 190,
    espnId: 190,
    fullName: "Red Bull New York",
    code: "RBNY",
    city: "Harrison",
    location: "Harrison, NJ",
    coach: "Michael Bradley",
    owner: "Red Bull GmbH",
    established: 1994,
    logo: RedBullNewYorkLogo,
    logoLight: RedBullNewYorkLogoLight,
    name: "Red Bull New York",
    shortName: "Red Bull NY",
    color: "#ba0c2f",
    secondaryColor: "#ffc72c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 22529,
    espnId: 22529,
    fullName: "San Diego FC",
    code: "SD",
    city: "San Diego",
    location: "San Diego, CA",
    coach: "Mikey Varas",
    owner: "Mohamed Mansour, Sycuan Band of the Kumeyaay Nation",
    established: 2023,
    logo: SanDiegoFCLogo,
    logoLight: SanDiegoFCLogoLight,
    name: "San Diego FC",
    shortName: "San Diego",
    color: "#697a7C",
    secondaryColor: "#F89E1A",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 191,
    espnId: 191,
    fullName: "San Jose Earthquakes",
    code: "SJ",
    city: "San Jose",
    location: "San Jose, CA",
    coach: "Bruce Arena",
    owner: "John Fisher",
    established: 1994,
    logo: SanJoseEarthquakesLogo,
    logoLight: SanJoseEarthquakesLogoLight,
    name: "San Jose Earthquakes",
    shortName: "San Jose",
    color: "#003da6",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9726,
    espnId: 9726,
    fullName: "Seattle Sounders FC",
    code: "SEA",
    city: "Seattle",
    location: "Seattle, WA",
    coach: "Brian Schmetzer",
    owner: "Adrian Hanauer",
    established: 2007,
    logo: SeattleSoundersFCLogo,
    logoLight: SeattleSoundersFCLogoLight,
    name: "Seattle Sounders FC",
    shortName: "Seattle",
    color: "#2dc84d",
    secondaryColor: "#0033a0",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 186,
    espnId: 186,
    fullName: "Sporting Kansas City",
    code: "SKC",
    city: "Kansas City",
    location: "Kansas City, KS",
    coach: "Raphaël Wicky",
    owner: "Sporting Club",
    established: 1995,
    logo: SportingKansasCityLogo,
    logoLight: SportingKansasCityLogoLight,
    name: "Sporting Kansas City",
    shortName: "Kansas City",
    color: "#a7c6ed",
    secondaryColor: "#0a2240",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 21812,
    espnId: 21812,
    fullName: "St. Louis CITY SC",
    code: "STL",
    city: "St. Louis",
    location: "St. Louis, MO",
    coach: "Yoann Damet",
    owner: "Carolyn Kindle",
    established: 2019,
    logo: StLouisCITYSCLogo,
    logoLight: StLouisCITYSCLogoLight,
    name: "St. Louis CITY SC",
    shortName: "St. Louis",
    color: "#ec1458",
    secondaryColor: "#001544",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7318,
    espnId: 7318,
    fullName: "Toronto FC",
    code: "TOR",
    city: "Toronto",
    location: "Toronto, ON",
    coach: "Robin Fraser",
    owner: "Maple Leaf Sports & Entertainment",
    established: 2005,
    logo: TorontoFCLogo,
    logoLight: TorontoFCLogoLight,
    name: "Toronto FC",
    shortName: "Toronto",
    color: "#aa182c",
    secondaryColor: "#a2a9ad",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9727,
    espnId: 9727,
    fullName: "Vancouver Whitecaps",
    code: "VAN",
    city: "Vancouver",
    location: "Vancouver, BC",
    coach: "Jesper Sørensen",
    owner: "Greg Kerfoot, Steve Luczo, Jeff Mallett, Steve Nash",
    established: 1974,
    logo: VancouverWhitecapsLogo,
    logoLight: VancouverWhitecapsLogoLight,
    name: "Vancouver Whitecaps",
    shortName: "Vancouver",
    color: "#ffffff",
    secondaryColor: "#12284c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 349,
    espnId: 349,
    fullName: "AFC Bournemouth",
    code: "BOU",
    city: "Bournemouth",
    location: "Bournemouth, England",
    coach: "Marco Rose",
    owner: "Black Knight Football Club UK Limited",
    established: 1899,
    logo: AFCBournemouthLogo,
    logoLight: AFCBournemouthLogoLight,
    name: "AFC Bournemouth",
    shortName: "Bournemouth",
    color: "#f42727",
    secondaryColor: "#0000CC",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 359,
    espnId: 359,
    fullName: "Arsenal",
    code: "ARS",
    city: "London",
    location: "London, England",
    coach: "Mikel Arteta",
    owner: "Kroenke Sports & Entertainment",
    established: 1886,
    logo: ArsenalLogo,
    logoLight: ArsenalLogoLight,
    name: "Arsenal",
    shortName: "Arsenal",
    color: "#e20520",
    secondaryColor: "#003399",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 362,
    espnId: 362,
    fullName: "Aston Villa",
    code: "AVL",
    city: "Birmingham",
    location: "Birmingham, England",
    coach: "Unai Emery",
    owner: "Nassef Sawiris, Wes Edens",
    established: 1874,
    logo: AstonVillaLogo,
    logoLight: AstonVillaLogoLight,
    name: "Aston Villa",
    shortName: "Aston Villa",
    color: "#660e36",
    secondaryColor: "#333333",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 337,
    espnId: 337,
    fullName: "Brentford",
    code: "BRE",
    city: "London",
    location: "London, England",
    coach: "Keith Andrews",
    owner: "Matthew Benham",
    established: 1889,
    logo: BrentfordLogo,
    logoLight: BrentfordLogoLight,
    name: "Brentford",
    shortName: "Brentford",
    color: "#f42727",
    secondaryColor: "#f8ced9",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 331,
    espnId: 331,
    fullName: "Brighton & Hove Albion",
    code: "BHA",
    city: "Brighton and Hove",
    location: "Brighton and Hove, England",
    coach: "Fabian Hürzeler",
    owner: "Tony Bloom",
    established: 1901,
    logo: BrightonHoveAlbionLogo,
    logoLight: BrightonHoveAlbionLogoLight,
    name: "Brighton & Hove Albion",
    shortName: "Brighton",
    color: "#0606fa",
    secondaryColor: "#ffdd00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 379,
    espnId: 379,
    fullName: "Burnley",
    code: "BUR",
    city: "Burnley",
    location: "Burnley, England",
    coach: "Mike Jackson (interim)",
    owner: "ALK Capital LLC",
    established: 1882,
    logo: BurnleyLogo,
    logoLight: BurnleyLogoLight,
    name: "Burnley",
    shortName: "Burnley",
    color: "#6C1D45",
    secondaryColor: "#00FFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 363,
    espnId: 363,
    fullName: "Chelsea",
    code: "CHE",
    city: "London",
    location: "London, England",
    coach: "Xabi Alonso",
    owner: "BlueCo",
    established: 1905,
    logo: ChelseaLogo,
    logoLight: ChelseaLogoLight,
    name: "Chelsea",
    shortName: "Chelsea",
    color: "#144992",
    secondaryColor: "#FFFFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 384,
    espnId: 384,
    fullName: "Crystal Palace",
    code: "CRY",
    city: "London",
    location: "London, England",
    owner: "Steve Parish",
    established: 1905,
    logo: CrystalPalaceLogo,
    logoLight: CrystalPalaceLogoLight,
    name: "Crystal Palace",
    shortName: "C Palace",
    color: "#0202fb",
    secondaryColor: "#ffdd00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 368,
    espnId: 368,
    fullName: "Everton",
    code: "EVE",
    city: "Liverpool",
    location: "Liverpool, England",
    coach: "David Moyes",
    owner: "The Friedkin Group",
    established: 1878,
    logo: EvertonLogo,
    logoLight: EvertonLogoLight,
    name: "Everton",
    shortName: "Everton",
    color: "#0606fa",
    secondaryColor: "#132257",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 370,
    espnId: 370,
    fullName: "Fulham",
    code: "FUL",
    city: "London",
    location: "London, England",
    owner: "Shahid Khan",
    established: 1879,
    logo: FulhamLogo,
    logoLight: FulhamLogoLight,
    name: "Fulham",
    shortName: "Fulham",
    color: "#ffffff",
    secondaryColor: "#00CC00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 357,
    espnId: 357,
    fullName: "Leeds United",
    code: "LEE",
    city: "Leeds",
    location: "Leeds, England",
    coach: "Daniel Farke",
    owner: "49ers Enterprises",
    established: 1919,
    logo: LeedsUnitedLogo,
    logoLight: LeedsUnitedLogoLight,
    name: "Leeds United",
    shortName: "Leeds",
    color: "#ffffff",
    secondaryColor: "#0000FF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 364,
    espnId: 364,
    fullName: "Liverpool",
    code: "LIV",
    city: "Liverpool",
    location: "Liverpool, England",
    coach: "Andoni Iraola",
    owner: "Fenway Sports Group",
    established: 1892,
    logo: LiverpoolLogo,
    logoLight: LiverpoolLogoLight,
    name: "Liverpool",
    shortName: "Liverpool",
    color: "#d11317",
    secondaryColor: "#FFFFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 382,
    espnId: 382,
    fullName: "Manchester City",
    code: "MNC",
    city: "Manchester",
    location: "Manchester, England",
    owner: "City Football Group Limited",
    established: 1880,
    logo: ManchesterCityLogo,
    logoLight: ManchesterCityLogoLight,
    name: "Manchester City",
    shortName: "Man City",
    color: "#99c5ea",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 360,
    espnId: 360,
    fullName: "Manchester United",
    code: "MAN",
    city: "Manchester",
    location: "Manchester, England",
    coach: "Michael Carrick",
    owner: "Manchester United plc",
    established: 1878,
    logo: ManchesterUnitedLogo,
    logoLight: ManchesterUnitedLogoLight,
    name: "Manchester United",
    shortName: "Man United",
    color: "#da020e",
    secondaryColor: "#FFFFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 361,
    espnId: 361,
    fullName: "Newcastle United",
    code: "NEW",
    city: "Newcastle upon Tyne",
    location: "Newcastle upon Tyne, England",
    coach: "Eddie Howe",
    owner: "Public Investment Fund, RB Sports & Media, PCP Capital Partners",
    established: 1892,
    logo: NewcastleUnitedLogo,
    logoLight: NewcastleUnitedLogoLight,
    name: "Newcastle United",
    shortName: "Newcastle",
    color: "#000000",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 393,
    espnId: 393,
    fullName: "Nottingham Forest",
    code: "NFO",
    city: "Nottingham",
    location: "Nottingham, England",
    coach: "Vítor Pereira",
    owner: "Evangelos Marinakis",
    established: 1865,
    logo: NottinghamForestLogo,
    logoLight: NottinghamForestLogoLight,
    name: "Nottingham Forest",
    shortName: "Nottm Forest",
    color: "#c8102e",
    secondaryColor: "#132257",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 366,
    espnId: 366,
    fullName: "Sunderland",
    code: "SUN",
    city: "Sunderland",
    location: "Sunderland, England",
    coach: "Régis Le Bris",
    owner: "Kyril Louis-Dreyfus",
    established: 1879,
    logo: SunderlandLogo,
    logoLight: SunderlandLogoLight,
    name: "Sunderland",
    shortName: "Sunderland",
    color: "#EB172B",
    secondaryColor: "#87cced",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 367,
    espnId: 367,
    fullName: "Tottenham Hotspur",
    code: "TOT",
    city: "London",
    location: "London, England",
    coach: "Roberto De Zerbi",
    owner: "ENIC International Ltd.",
    established: 1882,
    logo: TottenhamHotspurLogo,
    logoLight: TottenhamHotspurLogoLight,
    name: "Tottenham Hotspur",
    shortName: "Spurs",
    color: "#ffffff",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 371,
    espnId: 371,
    fullName: "West Ham United",
    code: "WHU",
    city: "London",
    location: "London, England",
    coach: "Nuno Espírito Santo",
    owner: "David Sullivan, Daniel Křetínský, Vanessa Gold",
    established: 1895,
    logo: WestHamUnitedLogo,
    logoLight: WestHamUnitedLogoLight,
    name: "West Ham United",
    shortName: "West Ham",
    color: "#7c2c3b",
    secondaryColor: "#F1E7E0",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 380,
    espnId: 380,
    fullName: "Wolverhampton Wanderers",
    code: "WOL",
    city: "Wolverhampton",
    location: "Wolverhampton, England",
    owner: "Fosun International",
    established: 1877,
    logo: WolverhamptonWanderersLogo,
    logoLight: WolverhamptonWanderersLogoLight,
    name: "Wolverhampton Wanderers",
    shortName: "Wolves",
    color: "#fdb913",
    secondaryColor: "#32A8DD",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2750,
    espnId: 2750,
    fullName: "Argentina",
    code: "ARG",
    city: null,
    location: null,
    established: 0,
    logo: Argentina2750Logo,
    logoLight: Argentina2750LogoLight,
    name: "Argentina",
    shortName: "Argentina",
    color: "#74acdf",
    secondaryColor: "#173e69",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2751,
    espnId: 2751,
    fullName: "Australia",
    code: "AUS",
    city: null,
    location: null,
    established: 0,
    logo: Australia2751Logo,
    logoLight: Australia2751LogoLight,
    name: "Australia",
    shortName: "Australia",
    color: "#2a2d7c",
    secondaryColor: "#ed2f31",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2752,
    espnId: 2752,
    fullName: "Brazil",
    code: "BRA",
    city: null,
    location: null,
    established: 0,
    logo: Brazil2752Logo,
    logoLight: Brazil2752LogoLight,
    name: "Brazil",
    shortName: "Brazil",
    color: "#fee000",
    secondaryColor: "#009c37",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2753,
    espnId: 2753,
    fullName: "Canada",
    code: "CAN",
    city: null,
    location: null,
    established: 0,
    logo: Canada2753Logo,
    logoLight: Canada2753LogoLight,
    name: "Canada",
    shortName: "Canada ",
    color: "#ed2224",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2754,
    espnId: 2754,
    fullName: "China",
    code: "CHN",
    city: null,
    location: null,
    established: 0,
    logo: ChinaLogo,
    logoLight: ChinaLogoLight,
    name: "China",
    shortName: "China",
    color: "#dd342c",
    secondaryColor: "#ffe533",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 11337,
    espnId: 11337,
    fullName: "Colombia",
    code: "COL",
    city: null,
    location: null,
    established: 0,
    logo: Colombia11337Logo,
    logoLight: Colombia11337LogoLight,
    name: "Colombia",
    shortName: "Colombia",
    color: "#fbd632",
    secondaryColor: "#21418c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2894,
    espnId: 2894,
    fullName: "Costa Rica",
    code: "CRC",
    city: null,
    location: null,
    established: 0,
    logo: CostaRicaLogo,
    logoLight: CostaRicaLogoLight,
    name: "Costa Rica",
    shortName: "Costa Rica",
    color: "#ce1126",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2896,
    espnId: 2896,
    fullName: "Denmark",
    code: "DEN",
    city: null,
    location: null,
    established: 0,
    logo: DenmarkLogo,
    logoLight: DenmarkLogoLight,
    name: "Denmark",
    shortName: "Denmark",
    color: "#d02a3e",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 5159,
    espnId: 5159,
    fullName: "England",
    code: "ENG",
    city: null,
    location: null,
    established: 0,
    logo: England5159Logo,
    logoLight: England5159LogoLight,
    name: "England",
    shortName: "England",
    color: "#ce1124",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2755,
    espnId: 2755,
    fullName: "France",
    code: "FRA",
    city: null,
    location: null,
    established: 0,
    logo: France2755Logo,
    logoLight: France2755LogoLight,
    name: "France",
    shortName: "France",
    color: "#002f79",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2756,
    espnId: 2756,
    fullName: "Germany",
    code: "GER",
    city: null,
    location: null,
    established: 0,
    logo: Germany2756Logo,
    logoLight: Germany2756LogoLight,
    name: "Germany",
    shortName: "Germany",
    color: "#000000",
    secondaryColor: "#db2c32",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2891,
    espnId: 2891,
    fullName: "Haiti",
    code: "HAI",
    city: null,
    location: null,
    established: 0,
    logo: Haiti2891Logo,
    logoLight: Haiti2891LogoLight,
    name: "Haiti",
    shortName: "Haiti",
    color: "#0033a0",
    secondaryColor: "#EF0000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2792,
    espnId: 2792,
    fullName: "Italy",
    code: "ITA",
    city: null,
    location: null,
    established: 0,
    logo: ItalyLogo,
    logoLight: ItalyLogoLight,
    name: "Italy",
    shortName: "Italy",
    color: "#24923c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2893,
    espnId: 2893,
    fullName: "Jamaica",
    code: "JAM",
    city: null,
    location: null,
    established: 0,
    logo: JamaicaLogo,
    logoLight: JamaicaLogoLight,
    name: "Jamaica",
    shortName: "Jamaica",
    color: "#348b42",
    secondaryColor: "#f9e032",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2758,
    espnId: 2758,
    fullName: "Japan",
    code: "JPN",
    city: null,
    location: null,
    established: 0,
    logo: Japan2758Logo,
    logoLight: Japan2758LogoLight,
    name: "Japan",
    shortName: "Japan",
    color: "#ed1c24",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18221,
    espnId: 18221,
    fullName: "Morocco",
    code: "MAR",
    city: null,
    location: null,
    established: 0,
    logo: Morocco18221Logo,
    logoLight: Morocco18221LogoLight,
    name: "Morocco",
    shortName: "Morocco",
    color: "#df2027",
    secondaryColor: "#009060",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7151,
    espnId: 7151,
    fullName: "Netherlands",
    code: "NED",
    city: null,
    location: null,
    established: 0,
    logo: Netherlands7151Logo,
    logoLight: Netherlands7151LogoLight,
    name: "Netherlands",
    shortName: "Netherlands",
    color: "#ec2f00",
    secondaryColor: "#003da5",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 4153,
    espnId: 4153,
    fullName: "New Zealand",
    code: "NZL",
    city: null,
    location: null,
    established: 0,
    logo: NewZealand4153Logo,
    logoLight: NewZealand4153LogoLight,
    name: "New Zealand",
    shortName: "New Zealand",
    color: "#273476",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2761,
    espnId: 2761,
    fullName: "Nigeria",
    code: "NGA",
    city: null,
    location: null,
    established: 0,
    logo: NigeriaLogo,
    logoLight: NigeriaLogoLight,
    name: "Nigeria",
    shortName: "Nigeria",
    color: "#008751",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2762,
    espnId: 2762,
    fullName: "Norway",
    code: "NOR",
    city: null,
    location: null,
    established: 0,
    logo: Norway2762Logo,
    logoLight: Norway2762LogoLight,
    name: "Norway",
    shortName: "Norway",
    color: "#ef2b2d",
    secondaryColor: "#002868",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2895,
    espnId: 2895,
    fullName: "Panama",
    code: "PAN",
    city: null,
    location: null,
    established: 0,
    logo: Panama2895Logo,
    logoLight: Panama2895LogoLight,
    name: "Panama",
    shortName: "Panama",
    color: "#d60a14",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 21546,
    espnId: 21546,
    fullName: "Philippines",
    code: "PHI",
    city: null,
    location: null,
    established: 0,
    logo: PhilippinesLogo,
    logoLight: PhilippinesLogoLight,
    name: "Philippines",
    shortName: "Philippines",
    color: "#1f449b",
    secondaryColor: "#ce2931",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9531,
    espnId: 9531,
    fullName: "Portugal",
    code: "POR",
    city: null,
    location: null,
    established: 0,
    logo: Portugal9531Logo,
    logoLight: Portugal9531LogoLight,
    name: "Portugal",
    shortName: "Portugal",
    color: "#006600",
    secondaryColor: "#da291c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 4178,
    espnId: 4178,
    fullName: "Republic of Ireland",
    code: "IRL",
    city: null,
    location: null,
    established: 0,
    logo: RepublicOfIrelandLogo,
    logoLight: RepublicOfIrelandLogoLight,
    name: "Republic of Ireland",
    shortName: "Rep Ireland",
    color: "#049a64",
    secondaryColor: "#f58241",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 13313,
    espnId: 13313,
    fullName: "South Africa",
    code: "RSA",
    city: null,
    location: null,
    established: 0,
    logo: SouthAfrica13313Logo,
    logoLight: SouthAfrica13313LogoLight,
    name: "South Africa",
    shortName: "South Africa",
    color: "#ffef00",
    secondaryColor: "#002f00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17639,
    espnId: 17639,
    fullName: "South Korea",
    code: "KOR",
    city: null,
    location: null,
    established: 0,
    logo: SouthKorea17639Logo,
    logoLight: SouthKorea17639LogoLight,
    name: "South Korea",
    shortName: "South Korea",
    color: "#ce2028",
    secondaryColor: "#1e4384",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17640,
    espnId: 17640,
    fullName: "Spain",
    code: "ESP",
    city: null,
    location: null,
    established: 0,
    logo: Spain17640Logo,
    logoLight: Spain17640LogoLight,
    name: "Spain",
    shortName: "Spain",
    color: "#c60b1e",
    secondaryColor: "#ffc400",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2764,
    espnId: 2764,
    fullName: "Sweden",
    code: "SWE",
    city: null,
    location: null,
    established: 0,
    logo: Sweden2764Logo,
    logoLight: Sweden2764LogoLight,
    name: "Sweden",
    shortName: "Sweden",
    color: "#fecb00",
    secondaryColor: "#006aa7",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17641,
    espnId: 17641,
    fullName: "Switzerland",
    code: "SUI",
    city: null,
    location: null,
    established: 0,
    logo: Switzerland17641Logo,
    logoLight: Switzerland17641LogoLight,
    name: "Switzerland",
    shortName: "Switzerland",
    color: "#d72b2c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2765,
    espnId: 2765,
    fullName: "United States",
    code: "USA",
    city: null,
    location: null,
    established: 0,
    logo: UnitedStates2765Logo,
    logoLight: UnitedStates2765LogoLight,
    name: "United States",
    shortName: "USA",
    color: "#213065",
    secondaryColor: "#d42339",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17815,
    espnId: 17815,
    fullName: "Vietnam",
    code: "VIE",
    city: null,
    location: null,
    established: 0,
    logo: VietnamLogo,
    logoLight: VietnamLogoLight,
    name: "Vietnam",
    shortName: "Vietnam",
    color: "#DA251D",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 20795,
    espnId: 20795,
    fullName: "Zambia",
    code: "ZAM",
    city: null,
    location: null,
    established: 0,
    logo: ZambiaLogo,
    logoLight: ZambiaLogoLight,
    name: "Zambia",
    shortName: "Zambia",
    color: "#00843d",
    secondaryColor: "#FFCD00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 6418,
    espnId: 6418,
    fullName: "1. FC Heidenheim 1846",
    code: "HDH",
    city: "Heidenheim an der Brenz",
    location: "Heidenheim an der Brenz, Germany",
    coach: "Frank Schmidt",
    established: 1846,
    logo: Team1FCHeidenheim1846Logo,
    logoLight: Team1FCHeidenheim1846LogoLight,
    name: "1. FC Heidenheim 1846",
    shortName: "Heidenheim",
    color: "#DA0308",
    secondaryColor: "#003399",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 598,
    espnId: 598,
    fullName: "1. FC Union Berlin",
    code: "FCU",
    city: "Berlin",
    location: "Berlin, Germany",
    coach: "Mauro Lustrinelli",
    established: 1966,
    logo: Team1FCUnionBerlinLogo,
    logoLight: Team1FCUnionBerlinLogoLight,
    name: "1. FC Union Berlin",
    shortName: "Union Berlin",
    color: "#DA0308",
    secondaryColor: "#d4d4d4",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 131,
    espnId: 131,
    fullName: "Bayer Leverkusen",
    code: "B04",
    city: "Leverkusen",
    location: "Leverkusen, Germany",
    coach: "Carles Martínez Novell",
    owner: "Bayer AG",
    established: 1904,
    logo: BayerLeverkusenLogo,
    logoLight: BayerLeverkusenLogoLight,
    name: "Bayer Leverkusen",
    shortName: "Leverkusen",
    color: "#DA0308",
    secondaryColor: "#f9fbfc",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 132,
    espnId: 132,
    fullName: "Bayern Munich",
    code: "MUN",
    city: "Munich",
    location: "Munich, Germany",
    coach: "Vincent Kompany",
    owner: "FC Bayern München e.V.",
    established: 1900,
    logo: BayernMunichLogo,
    logoLight: BayernMunichLogoLight,
    name: "Bayern Munich",
    shortName: "Bayern",
    color: "#dc052d",
    secondaryColor: "#1a1a1a",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 124,
    espnId: 124,
    fullName: "Borussia Dortmund",
    code: "DOR",
    city: "Dortmund",
    location: "Dortmund, Germany",
    coach: "Niko Kovač",
    owner: "Borussia Dortmund GmbH & Co. KGaA",
    established: 1909,
    logo: BorussiaDortmundLogo,
    logoLight: BorussiaDortmundLogoLight,
    name: "Borussia Dortmund",
    shortName: "Dortmund",
    color: "#ffee00",
    secondaryColor: "#272726",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 268,
    espnId: 268,
    fullName: "Borussia Mönchengladbach",
    code: "BMG",
    city: "Mönchengladbach",
    location: "Mönchengladbach, Germany",
    coach: "Eugen Polański",
    established: 1900,
    logo: BorussiaMonchengladbachLogo,
    logoLight: BorussiaMonchengladbachLogoLight,
    name: "Borussia Mönchengladbach",
    shortName: "Gladbach",
    color: "#ffffff",
    secondaryColor: "#03915c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 125,
    espnId: 125,
    fullName: "Eintracht Frankfurt",
    code: "SGE",
    city: "Frankfurt",
    location: "Frankfurt, Germany",
    coach: "Adi Hütter",
    established: 1899,
    logo: EintrachtFrankfurtLogo,
    logoLight: EintrachtFrankfurtLogoLight,
    name: "Eintracht Frankfurt",
    shortName: "Frankfurt",
    color: "#ffffff",
    secondaryColor: "#272726",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 3841,
    espnId: 3841,
    fullName: "FC Augsburg",
    code: "FCA",
    city: "Augsburg",
    location: "Augsburg, Germany",
    coach: "Manuel Baum",
    owner: "FC Augsburg 1907 GmbH & Co. KGaA",
    established: 1907,
    logo: FCAugsburgLogo,
    logoLight: FCAugsburgLogoLight,
    name: "FC Augsburg",
    shortName: "Augsburg",
    color: "#ffffff",
    secondaryColor: "#03915c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 122,
    espnId: 122,
    fullName: "FC Cologne",
    code: "KOE",
    city: "Cologne",
    location: "Cologne, Germany",
    coach: "René Wagner",
    established: 1948,
    logo: FCCologneLogo,
    logoLight: FCCologneLogoLight,
    name: "FC Cologne",
    shortName: "Cologne",
    color: "#ffffff",
    secondaryColor: "#DA0308",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 127,
    espnId: 127,
    fullName: "Hamburg SV",
    code: "HSV",
    city: "Hamburg",
    location: "Hamburg, Germany",
    coach: "Merlin Polzin",
    established: 1887,
    logo: HamburgSVLogo,
    logoLight: HamburgSVLogoLight,
    name: "Hamburg SV",
    shortName: "Hamburg",
    color: "#1a26af",
    secondaryColor: "#1a1a1a",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2950,
    espnId: 2950,
    fullName: "Mainz",
    code: "M05",
    city: "Mainz",
    location: "Mainz, Germany",
    coach: "Urs Fischer",
    established: 1905,
    logo: MainzLogo,
    logoLight: MainzLogoLight,
    name: "Mainz",
    shortName: "Mainz",
    color: "#DA0308",
    secondaryColor: "#000055",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 11420,
    espnId: 11420,
    fullName: "RB Leipzig",
    code: "RBL",
    city: "Leipzig",
    location: "Leipzig, Germany",
    coach: "Ole Werner",
    owner: "Red Bull GmbH",
    established: 2009,
    logo: RBLeipzigLogo,
    logoLight: RBLeipzigLogoLight,
    name: "RB Leipzig",
    shortName: "RB Leipzig",
    color: "#ffffff",
    secondaryColor: "#740c14",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 126,
    espnId: 126,
    fullName: "SC Freiburg",
    code: "SCF",
    city: "Freiburg",
    location: "Freiburg, Germany",
    coach: "Julian Schuster",
    established: 1904,
    logo: SCFreiburgLogo,
    logoLight: SCFreiburgLogoLight,
    name: "SC Freiburg",
    shortName: "Freiburg",
    color: "#DA0308",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 270,
    espnId: 270,
    fullName: "St. Pauli",
    code: "STP",
    city: "Hamburg",
    location: "Hamburg, Germany",
    established: 1910,
    logo: StPauliLogo,
    logoLight: StPauliLogoLight,
    name: "St. Pauli",
    shortName: "St. Pauli",
    color: "#442e23",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7911,
    espnId: 7911,
    fullName: "TSG Hoffenheim",
    code: "TSG",
    city: "Sinsheim",
    location: "Sinsheim, Germany",
    coach: "Christian Ilzer",
    owner: "Dietmar Hopp",
    established: 1899,
    logo: TSGHoffenheimLogo,
    logoLight: TSGHoffenheimLogoLight,
    name: "TSG Hoffenheim",
    shortName: "Hoffenheim",
    color: "#003399",
    secondaryColor: "#000055",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 134,
    espnId: 134,
    fullName: "VfB Stuttgart",
    code: "VFB",
    city: "Stuttgart",
    location: "Stuttgart, Germany",
    coach: "Sebastian Hoeneß",
    owner: "VfB Stuttgart 1893 AG",
    established: 1893,
    logo: VfBStuttgartLogo,
    logoLight: VfBStuttgartLogoLight,
    name: "VfB Stuttgart",
    shortName: "Stuttgart",
    color: "#ffffff",
    secondaryColor: "#DA0308",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 138,
    espnId: 138,
    fullName: "VfL Wolfsburg",
    code: "WOB",
    city: "Wolfsburg",
    location: "Wolfsburg, Germany",
    coach: "Tobias Strobl",
    owner: "Volkswagen AG",
    established: 1945,
    logo: VfLWolfsburgLogo,
    logoLight: VfLWolfsburgLogoLight,
    name: "VfL Wolfsburg",
    shortName: "Wolfsburg",
    color: "#81f733",
    secondaryColor: "#1a1a1a",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 137,
    espnId: 137,
    fullName: "Werder Bremen",
    code: "SVW",
    city: "Bremen",
    location: "Bremen, Germany",
    coach: "Daniel Thioune",
    owner: "SV Werder Bremen GmbH & Co. KG aA",
    established: 1899,
    logo: WerderBremenLogo,
    logoLight: WerderBremenLogoLight,
    name: "Werder Bremen",
    shortName: "Bremen",
    color: "#03915c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 96,
    espnId: 96,
    name: "Alavés",
    fullName: "Alavés",
    shortName: "Alavés",
    code: "ALA",
    color: "#0000ff",
    secondaryColor: "#c3c3c3",
    logo: AlavesLogo,
    logoLight: AlavesLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 93,
    espnId: 93,
    name: "Athletic Club",
    fullName: "Athletic Club",
    shortName: "Athletic",
    code: "ATH",
    color: "#C8142F",
    secondaryColor: "#0000ff",
    logo: AthleticClubLogo,
    logoLight: AthleticClubLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 1068,
    espnId: 1068,
    name: "Atlético Madrid",
    fullName: "Atlético Madrid",
    shortName: "Atlético",
    code: "ATM",
    color: "#ca3624",
    secondaryColor: "#000099",
    logo: AtleticoMadridLogo,
    logoLight: AtleticoMadridLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 83,
    espnId: 83,
    name: "Barcelona",
    fullName: "Barcelona",
    shortName: "Barcelona",
    code: "BAR",
    color: "#990000",
    secondaryColor: "#FCE38A",
    logo: BarcelonaLogo,
    logoLight: BarcelonaLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 85,
    espnId: 85,
    name: "Celta Vigo",
    fullName: "Celta Vigo",
    shortName: "Celta Vigo",
    code: "CEL",
    color: "#6cace4",
    secondaryColor: "#004996",
    logo: CeltaVigoLogo,
    logoLight: CeltaVigoLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 3751,
    espnId: 3751,
    name: "Elche",
    fullName: "Elche",
    shortName: "Elche",
    code: "ELC",
    color: "#ffffff",
    secondaryColor: "#288A00",
    logo: ElcheLogo,
    logoLight: ElcheLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 88,
    espnId: 88,
    name: "Espanyol",
    fullName: "Espanyol",
    shortName: "Espanyol",
    code: "ESP",
    color: "#3366CC",
    secondaryColor: "#C8142F",
    logo: EspanyolLogo,
    logoLight: EspanyolLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 2922,
    espnId: 2922,
    name: "Getafe",
    fullName: "Getafe",
    shortName: "Getafe",
    code: "GET",
    color: "#0000ff",
    secondaryColor: "#C8142F",
    logo: GetafeLogo,
    logoLight: GetafeLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 9812,
    espnId: 9812,
    name: "Girona",
    fullName: "Girona",
    shortName: "Girona",
    code: "GIR",
    color: "#C60000",
    secondaryColor: "#004996",
    logo: GironaLogo,
    logoLight: GironaLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 1538,
    espnId: 1538,
    name: "Levante",
    fullName: "Levante",
    shortName: "Levante",
    code: "LEV",
    color: "#C8142F",
    secondaryColor: "#000000",
    logo: LevanteLogo,
    logoLight: LevanteLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 84,
    espnId: 84,
    name: "Mallorca",
    fullName: "Mallorca",
    shortName: "Mallorca",
    code: "MLL",
    color: "#C8142F",
    secondaryColor: "#ccff00",
    logo: MallorcaLogo,
    logoLight: MallorcaLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 97,
    espnId: 97,
    name: "Osasuna",
    fullName: "Osasuna",
    shortName: "Osasuna",
    code: "OSA",
    color: "#cd0000",
    secondaryColor: "#ffffff",
    logo: OsasunaLogo,
    logoLight: OsasunaLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 101,
    espnId: 101,
    name: "Rayo Vallecano",
    fullName: "Rayo Vallecano",
    shortName: "Rayo",
    code: "RAY",
    color: "#ffffff",
    secondaryColor: "#cd0000",
    logo: RayoVallecanoLogo,
    logoLight: RayoVallecanoLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 244,
    espnId: 244,
    name: "Real Betis",
    fullName: "Real Betis",
    shortName: "Betis",
    code: "BET",
    color: "#288A00",
    secondaryColor: "#ccff00",
    logo: RealBetisLogo,
    logoLight: RealBetisLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 86,
    espnId: 86,
    name: "Real Madrid",
    fullName: "Real Madrid",
    shortName: "Real Madrid",
    code: "RMA",
    color: "#ffffff",
    secondaryColor: "#00529F",
    logo: RealMadridLogo,
    logoLight: RealMadridLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 92,
    espnId: 92,
    name: "Real Oviedo",
    fullName: "Real Oviedo",
    shortName: "Real Oviedo",
    code: "OVI",
    color: "#e23627",
    secondaryColor: "#ffd200",
    logo: RealOviedoLogo,
    logoLight: RealOviedoLogo,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 89,
    espnId: 89,
    name: "Real Sociedad",
    fullName: "Real Sociedad",
    shortName: "Real Sociedad",
    code: "RSO",
    color: "#3366CC",
    secondaryColor: "#ffdd00",
    logo: RealSociedadLogo,
    logoLight: RealSociedadLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 243,
    espnId: 243,
    name: "Sevilla",
    fullName: "Sevilla",
    shortName: "Sevilla",
    code: "SEV",
    color: "#ffffff",
    secondaryColor: "#d81022",
    logo: SevillaLogo,
    logoLight: SevillaLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 94,
    espnId: 94,
    name: "Valencia",
    fullName: "Valencia",
    shortName: "Valencia",
    code: "VAL",
    color: "#ffffff",
    secondaryColor: "#004996",
    logo: ValenciaLogo,
    logoLight: ValenciaLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 102,
    espnId: 102,
    name: "Villarreal",
    fullName: "Villarreal",
    shortName: "Villarreal",
    code: "VIL",
    color: "#ffff00",
    secondaryColor: "#6cace4",
    logo: VillarrealLogo,
    logoLight: VillarrealLogoLight,
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: null,
    location: null,
    established: 0,
  },
];

export const getSOCCTeam = (id: number | string) => {
  if (id == null) return undefined;
  return soccerTeams.find((t) => String(t.id) === String(id));
};

export function getSOCCTeamLogo(
  id: number | string | undefined,
  isDark: boolean,
) {
  const team = soccerTeams.find((t) => String(t.id) === String(id));
  if (!id || !team || team.logo === null) return PlaceholderLogo;

  return team
    ? isDark
      ? team.logoLight || team.logo || PlaceholderLogo
      : team.logo || PlaceholderLogo
    : PlaceholderLogo;
}
