//Logos
import { Team } from "@/types/team";
import NinersLogo from "assets/Football/NFL_Logos/49ers.png";
import AFCLogo from "assets/Football/NFL_Logos/AFC.png";
import BearsLogo from "assets/Football/NFL_Logos/Bears.png";
import BengalsLogo from "assets/Football/NFL_Logos/Bengals.png";
import BillsLogo from "assets/Football/NFL_Logos/Bills.png";
import BroncosLogo from "assets/Football/NFL_Logos/Broncos.png";
import BrownsLogo from "assets/Football/NFL_Logos/Browns.png";
import BuccaneersLogo from "assets/Football/NFL_Logos/Buccaneers.png";
import CardinalsLogo from "assets/Football/NFL_Logos/Cardinals.png";
import ChargersLogo from "assets/Football/NFL_Logos/Chargers.png";
import ChiefsLogo from "assets/Football/NFL_Logos/Chiefs.png";
import ColtsLogo from "assets/Football/NFL_Logos/Colts.png";
import CommandersLogo from "assets/Football/NFL_Logos/Commanders.png";
import CowboysLogo from "assets/Football/NFL_Logos/Cowboys.png";
import DolphinsLogo from "assets/Football/NFL_Logos/Dolphins.png";
import EaglesLogo from "assets/Football/NFL_Logos/Eagles.png";
import FalconsLogo from "assets/Football/NFL_Logos/Falcons.png";
import GiantsLogo from "assets/Football/NFL_Logos/Giants.png";
import GiantsLogoLight from "assets/Football/NFL_Logos/GiantsLight.png";
import JaguarsLogo from "assets/Football/NFL_Logos/Jaguars.png";
import JetsLogo from "assets/Football/NFL_Logos/Jets.png";
import JetsLogoLight from "assets/Football/NFL_Logos/JetsLight.png";
import LionsLogo from "assets/Football/NFL_Logos/Lions.png";
import NFCLogo from "assets/Football/NFL_Logos/NFC.png";
import PackersLogo from "assets/Football/NFL_Logos/Packers.png";
import PanthersLogo from "assets/Football/NFL_Logos/Panthers.png";
import PatriotsLogo from "assets/Football/NFL_Logos/Patriots.png";
import RaidersLogo from "assets/Football/NFL_Logos/Raiders.png";
import RamsLogo from "assets/Football/NFL_Logos/Rams.png";
import RavensLogo from "assets/Football/NFL_Logos/Ravens.png";
import SaintsLogo from "assets/Football/NFL_Logos/Saints.png";
import SeahawksLogo from "assets/Football/NFL_Logos/Seahawks.png";
import SteelersLogo from "assets/Football/NFL_Logos/Steelers.png";
import TexansLogo from "assets/Football/NFL_Logos/Texans.png";
import TitansLogo from "assets/Football/NFL_Logos/Titans.png";
import VikingsLogo from "assets/Football/NFL_Logos/Vikings.png";
const placeholderLogo =
  "https://res.cloudinary.com/dm3qtdhag/image/upload/v1781619331/placeholder/team.png";

export const nflTeams: Team[] = [
  {
    id: 1,
    espnId: 13,
    fullName: "Las Vegas Raiders",
    code: "LV",
    city: "Las Vegas",
    location: "Las Vegas, NV",
    coach: "Pete Carroll",
    owner: "Carol and Mark Davis",
    established: 1960,
    logo: RaidersLogo,
    logoLight: RaidersLogo,
    name: "Raiders",
    color: "#000000",
    secondaryColor: "#a5acaf",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 2,
    espnId: 30,
    fullName: "Jacksonville Jaguars",
    code: "JAX",
    city: "Jacksonville",
    location: "Jacksonville, FL",
    coach: "Liam Coen",
    owner: "Shahid Khan",
    established: 1995,
    logo: JaguarsLogo,
    logoLight: JaguarsLogo,
    name: "Jaguars",
    color: "#006778",
    secondaryColor: "#d7a22a",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 3,
    espnId: 17,
    fullName: "New England Patriots",
    code: "NE",
    city: "Foxborough",
    location: "Foxborough, MA",
    coach: "Mike Vrabel",
    owner: "Robert Kraft",
    established: 1960,
    logo: PatriotsLogo,
    logoLight: PatriotsLogo,
    name: "Patriots",
    color: "#002a5c",
    secondaryColor: "#c60c30",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 4,
    espnId: 19,
    fullName: "New York Giants",
    code: "NYG",
    city: "New York",
    location: "New York, NY",
    coach: "Brian Daboll",
    owner: "John Mara, Steve Tisch",
    established: 1925,
    logo: GiantsLogo,
    logoLight: GiantsLogoLight,
    name: "Giants",
    color: "#003c7f",
    secondaryColor: "#c9243f",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 5,
    espnId: 33,
    fullName: "Baltimore Ravens",
    code: "BAL",
    city: "Baltimore",
    location: "Baltimore, MD",
    coach: "John Harbaugh",
    owner: "Steve Bisciotti",
    established: 1996,
    logo: RavensLogo,
    logoLight: RavensLogo,
    name: "Ravens",
    color: "#29126f",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 6,
    espnId: 10,
    fullName: "Tennessee Titans",
    code: "TEN",
    city: "Nashville",
    location: "Nashville, TN",
    coach: "Brian Callahan",
    owner: "Amy Adams Strunk",
    established: 1960,
    logo: TitansLogo,
    logoLight: TitansLogo,
    name: "Titans",
    color: "#4b92db",
    secondaryColor: "#002a5c",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 7,
    espnId: 8,
    fullName: "Detroit Lions",
    code: "DET",
    city: "Detroit",
    location: "Detroit, MI",
    coach: "Dan Campbell",
    owner: "Sheila Ford Hamp",
    established: 1930,
    logo: LionsLogo,
    logoLight: LionsLogo,
    name: "Lions",
    color: "#0076b6",
    secondaryColor: "#bbbbbb",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },

  {
    id: 8,
    espnId: 1,
    fullName: "Atlanta Falcons",
    code: "ATL",
    city: "Atlanta",
    location: "Atlanta, GA",
    coach: "Raheem Morris",
    owner: "Arthur Blank",
    established: 1966,
    logo: FalconsLogo,
    logoLight: FalconsLogo,
    name: "Falcons",
    color: "#a71930",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 9,
    espnId: 5,
    fullName: "Cleveland Browns",
    code: "CLE",
    city: "Cleveland",
    location: "Cleveland, OH",
    coach: "Kevin Stefanski",
    owner: "Dee and Jimmy Haslam",
    established: 1946,
    logo: BrownsLogo,
    logoLight: BrownsLogo,
    name: "Browns",
    color: "#311d00",
    secondaryColor: "#ff3c00",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 10,
    espnId: 4,
    fullName: "Cincinnati Bengals",
    code: "CIN",
    city: "Cincinnati",
    location: "Cincinnati, OH",
    coach: "Zac Taylor",
    owner: "Mike Brown",
    established: 1968,
    logo: BengalsLogo,
    logoLight: BengalsLogo,
    name: "Bengals",
    color: "#fb4f14",
    secondaryColor: "000000",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 11,
    espnId: 22,
    fullName: "Arizona Cardinals",
    code: "ARI",
    city: "Glendale",
    location: "Glendale, AZ",
    coach: "Jonathan Gannon",
    owner: "Michael Bidwill",
    established: 1920,
    logo: CardinalsLogo,
    logoLight: CardinalsLogo,
    name: "Cardinals",
    color: "#a40227",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 12,
    espnId: 21,
    fullName: "Philadelphia Eagles",
    code: "PHI",
    city: "Philadelphia",
    location: "Philadelphia, PA",
    coach: "Nick Sirianni",
    owner: "Jeffrey Lurie",
    established: 1933,
    logo: EaglesLogo,
    logoLight: EaglesLogo,
    name: "Eagles",
    color: "#06424d",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 13,
    espnId: 20,
    fullName: "New York Jets",
    code: "NYJ",
    city: "New York",
    location: "New York, NY",
    coach: "Aaron Glenn",
    owner: "Robert Wood Johnson IV",
    established: 1960,
    logo: JetsLogo,
    logoLight: JetsLogoLight,
    name: "Jets",
    color: "#115740",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 14,
    espnId: 25,
    fullName: "San Francisco 49ers",
    code: "SF",
    city: "San Francisco",
    location: "San Francisco, CA",
    coach: "Kyle Shanahan",
    owner: "Jed York",
    established: 1946,
    logo: NinersLogo,
    logoLight: NinersLogo,
    name: "49ers",
    color: "#aa0000",
    secondaryColor: "#b3995d",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 15,
    espnId: 9,

    fullName: "Green Bay Packers",
    code: "GB",
    city: "Green Bay",
    location: "Green Bay, WI",
    coach: "Matt LaFleur",
    owner: "Green Bay Packers, Inc.",
    established: 1921,
    logo: PackersLogo,
    logoLight: PackersLogo,

    name: "Packers",
    color: "#203731",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 16,
    espnId: 3,
    fullName: "Chicago Bears",
    code: "CHI",
    city: "Chicago",
    location: "Chicago, IL",
    coach: "Ben Johnson",
    owner: "Virginia Halas McCaskey",
    established: 1920,
    logo: BearsLogo,
    logoLight: BearsLogo,
    name: "Bears",
    color: "#0B162A",
    secondaryColor: "#e64100",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 17,
    espnId: 12,
    fullName: "Kansas City Chiefs",
    code: "KC",
    city: "Kansas City",
    location: "Kansas City, MO",
    coach: "Andy Reid",
    owner: "Clark Hunt",
    established: 1960,
    logo: ChiefsLogo,
    logoLight: ChiefsLogo,
    name: "Chiefs",
    color: "#E31837",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 18,
    espnId: 28,
    fullName: "Washington Commanders",
    code: "WSH",
    city: "Washington",
    location: "Washington, DC",
    coach: "Dan Quinn",
    owner: "Josh Harris",
    established: 1932,
    logo: CommandersLogo,
    logoLight: CommandersLogo,
    name: "Commanders",
    color: "#5a1414",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 19,
    espnId: 29,
    fullName: "Carolina Panthers",
    code: "CAR",
    city: "Charlotte",
    location: "Charlotte, NC",
    coach: "David Canales",
    owner: "David Tepper",
    established: 1995,
    logo: PanthersLogo,
    logoLight: PanthersLogo,
    name: "Panthers",
    color: "#0085ca",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 20,
    espnId: 2,
    fullName: "Buffalo Bills",
    code: "BUF",
    city: "Buffalo",
    location: "Buffalo, NY",
    coach: "Sean McDermott",
    owner: "Kim and Terry Pegula",
    established: 1960,
    logo: BillsLogo,
    logoLight: BillsLogo,
    name: "Bills",
    color: "#00338d",
    secondaryColor: "#d50a0a",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 21,
    espnId: 11,
    fullName: "Indianapolis Colts",
    code: "IND",
    city: "Indianapolis",
    location: "Indianapolis, IN",
    coach: "Shane Steichen",
    owner: "Jim Irsay",
    established: 1944,
    logo: ColtsLogo,
    logoLight: ColtsLogo,
    name: "Colts",
    color: "#002C5F",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 22,
    espnId: 23,
    fullName: "Pittsburgh Steelers",
    code: "PIT",
    city: "Pittsburgh",
    location: "Pittsburgh, PA",
    coach: "Mike Tomlin",
    owner: "Art Rooney II and Family",
    established: 1933,
    logo: SteelersLogo,
    logoLight: SteelersLogo,
    name: "Steelers",
    color: "#000000",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 23,
    espnId: 26,
    fullName: "Seattle Seahawks",
    code: "SEA",
    city: "Seattle",
    location: "Seattle, WA",
    coach: "Mike Macdonald",
    owner: "Seattle Seahawks Ownership Trust",
    established: 1976,
    logo: SeahawksLogo,
    logoLight: SeahawksLogo,
    name: "Seahawks",
    color: "#002244",
    secondaryColor: "#69be28",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 24,
    espnId: 27,
    fullName: "Tampa Bay Buccaneers",
    code: "TB",
    city: "Tampa",
    location: "Tampa, FL",
    coach: "Todd Bowles",
    owner: "Bryan Glazer, Edward Glazer, Joel Glazer",
    established: 1976,
    logo: BuccaneersLogo,
    logoLight: BuccaneersLogo,
    name: "Buccaneers",
    color: "#bd1c36",
    secondaryColor: "#3e3a35",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 25,
    espnId: 15,
    fullName: "Miami Dolphins",
    code: "MIA",
    city: "Miami",
    location: "Miami, FL",
    coach: "Mike McDaniel",
    owner: "Stephen M. Ross",
    established: 1966,
    logo: DolphinsLogo,
    logoLight: DolphinsLogo,
    name: "Dolphins",
    color: "#008e97",
    secondaryColor: "#fc4c02",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 26,
    espnId: 34,
    fullName: "Houston Texans",
    code: "HOU",
    city: "Houston",
    location: "Houston, TX",
    coach: "DeMeco Ryans",
    owner: "Janice S. McNair",
    established: 2002,
    logo: TexansLogo,
    logoLight: TexansLogo,
    name: "Texans",
    color: "#03202f",
    secondaryColor: "#c41230",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 27,
    espnId: 18,
    fullName: "New Orleans Saints",
    code: "NO",
    city: "New Orleans",
    location: "New Orleans, LA",
    coach: "Dennis Allen",
    owner: "Gayle Benson",
    established: 1967,
    logo: SaintsLogo,
    logoLight: SaintsLogo,
    name: "Saints",
    color: "#d3bc8d",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 28,
    espnId: 7,
    fullName: "Denver Broncos",
    code: "DEN",
    city: "Denver",
    location: "Denver, CO",
    coach: "Sean Payton",
    owner: "Walton-Penner Family Ownership Group",
    established: 1960,
    logo: BroncosLogo,
    logoLight: BroncosLogo,
    name: "Broncos",
    color: "#0a2343",
    secondaryColor: "#fc4c02",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 29,
    espnId: 6,
    fullName: "Dallas Cowboys",
    code: "DAL",
    city: "Dallas",
    location: "Dallas, TX",
    coach: "Brian Schottenheimer",
    owner: "Jerry Jones",
    established: 1960,
    logo: CowboysLogo,
    logoLight: CowboysLogo,
    name: "Cowboys",
    color: "#041E42",
    secondaryColor: "#b0b7bc",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 30,
    espnId: 24,
    fullName: "Los Angeles Chargers",
    code: "LAC",
    city: "Los Angeles",
    location: "Los Angeles, CA",
    coach: "Giff Smith (interim)",
    owner: "Alex Spanos and Family",
    established: 1960,
    logo: ChargersLogo,
    logoLight: ChargersLogo,
    name: "Chargers",
    color: "#0080C6",
    secondaryColor: "#ffc20e",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 31,
    espnId: 14,
    fullName: "Los Angeles Rams",
    code: "LAR",
    city: "Los Angeles",
    location: "Los Angeles, CA",
    coach: "Sean McVay",
    owner: "Stan Kroenke",
    established: 1937,
    logo: RamsLogo,
    logoLight: RamsLogo,
    name: "Rams",
    color: "#003594",
    secondaryColor: "#ffd100",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 32,
    espnId: 16,
    fullName: "Minnesota Vikings",
    code: "MIN",
    city: "Minneapolis",
    location: "Minneapolis, MN",
    coach: "Kevin O'Connell",
    owner: "Zygi Wilf",
    established: 1961,
    logo: VikingsLogo,
    logoLight: VikingsLogo,
    name: "Vikings",
    color: "#4f2683",
    secondaryColor: "#ffc62f",
    isAllStar: false,
    isActive: true,
    isNational: false,
    league: "nfl",
  },
  {
    id: 34,
    espnId: 31,
    fullName: "AFC All-Stars",
    code: "AFC",
    city: "American Football Conference",
    location: "AFC",
    coach: "null",
    established: 1950,
    logo: AFCLogo,
    logoLight: AFCLogo,
    name: "AFC",
    color: "#D71920", // AFC red
    secondaryColor: "#002A5C",
    isAllStar: true,
    isActive: false,
    isNational: false,
    league: "nfl",
  },

  {
    id: 33,
    espnId: 32,
    fullName: "NFC All-Stars",
    code: "NFC",
    city: "National Football Conference",
    location: "NFC",
    established: 1950,
    logo: NFCLogo,
    logoLight: NFCLogo,
    name: "NFC",
    color: "#013369", // NFC blue
    secondaryColor: "#A5ACAF",
    coach: "null",
    isAllStar: true,
    isActive: false,
    isNational: false,
    league: "nfl",
  },
];

export const getNFLTeam = (id: number | string) =>
  nflTeams.find((t) => String(t.id) === String(id));

export function getNFLTeamLogo(
  id: number | string | undefined,
  isDark: boolean,
) {
  if (id === undefined || id === null || id === "") {
    return placeholderLogo;
  }

  const normalizedId = String(id);

  const team = nflTeams.find(
    (team) =>
      String(team.id) === normalizedId ||
      String(team.summerLeagueId) === normalizedId,
  );

  if (!team) {
    return placeholderLogo;
  }

  return isDark
    ? (team.logoLight ?? team.logo ?? placeholderLogo)
    : (team.logo ?? placeholderLogo);
}
export const getNFLTeamByESPNId = (espnId: number | string) => {
  return nflTeams.find((t) => t.espnId?.toString() === espnId?.toString());
};

export type NFLRivalryGroup = "division" | "national";
export type NFLRivalry = {
  id: string;
  name: string;
  teamIds: readonly [number, number];
  group: NFLRivalryGroup;
};

export const NFL_RIVALRIES = [
  {
    id: "packers-bears",
    name: "Packers–Bears",
    teamIds: [15, 16],
    group: "division",
  },
  {
    id: "packers-vikings",
    name: "Packers–Vikings",
    teamIds: [15, 32],
    group: "division",
  },
  {
    id: "bears-lions",
    name: "Bears–Lions",
    teamIds: [16, 7],
    group: "division",
  },
  {
    id: "bears-vikings",
    name: "Bears–Vikings",
    teamIds: [16, 32],
    group: "division",
  },
  {
    id: "packers-lions",
    name: "Packers–Lions",
    teamIds: [15, 7],
    group: "division",
  },
  {
    id: "lions-vikings",
    name: "Lions–Vikings",
    teamIds: [7, 32],
    group: "division",
  },
  {
    id: "steelers-ravens",
    name: "Steelers–Ravens",
    teamIds: [22, 5],
    group: "division",
  },
  {
    id: "steelers-browns",
    name: "Steelers–Browns",
    teamIds: [22, 9],
    group: "division",
  },
  {
    id: "steelers-bengals",
    name: "Steelers–Bengals",
    teamIds: [22, 10],
    group: "division",
  },
  {
    id: "bengals-browns",
    name: "Battle of Ohio",
    teamIds: [10, 9],
    group: "division",
  },
  {
    id: "ravens-bengals",
    name: "Ravens–Bengals",
    teamIds: [5, 10],
    group: "division",
  },
  {
    id: "ravens-browns",
    name: "Ravens–Browns",
    teamIds: [5, 9],
    group: "division",
  },
  {
    id: "cowboys-eagles",
    name: "Cowboys–Eagles",
    teamIds: [29, 12],
    group: "division",
  },
  {
    id: "cowboys-commanders",
    name: "Cowboys–Commanders",
    teamIds: [29, 18],
    group: "division",
  },
  {
    id: "cowboys-giants",
    name: "Cowboys–Giants",
    teamIds: [29, 4],
    group: "division",
  },
  {
    id: "eagles-giants",
    name: "Eagles–Giants",
    teamIds: [12, 4],
    group: "division",
  },
  {
    id: "eagles-commanders",
    name: "Eagles–Commanders",
    teamIds: [12, 18],
    group: "division",
  },
  {
    id: "giants-commanders",
    name: "Giants–Commanders",
    teamIds: [4, 18],
    group: "division",
  },
  {
    id: "chiefs-raiders",
    name: "Chiefs–Raiders",
    teamIds: [17, 1],
    group: "division",
  },
  {
    id: "chiefs-broncos",
    name: "Chiefs–Broncos",
    teamIds: [17, 28],
    group: "division",
  },
  {
    id: "raiders-broncos",
    name: "Raiders–Broncos",
    teamIds: [1, 28],
    group: "division",
  },
  {
    id: "raiders-chargers",
    name: "Raiders–Chargers",
    teamIds: [1, 30],
    group: "division",
  },
  {
    id: "chiefs-chargers",
    name: "Chiefs–Chargers",
    teamIds: [17, 30],
    group: "division",
  },
  {
    id: "broncos-chargers",
    name: "Broncos–Chargers",
    teamIds: [28, 30],
    group: "division",
  },
  {
    id: "patriots-jets",
    name: "Patriots–Jets",
    teamIds: [3, 13],
    group: "division",
  },
  {
    id: "bills-dolphins",
    name: "Bills–Dolphins",
    teamIds: [20, 25],
    group: "division",
  },
  {
    id: "patriots-bills",
    name: "Patriots–Bills",
    teamIds: [3, 20],
    group: "division",
  },
  {
    id: "patriots-dolphins",
    name: "Patriots–Dolphins",
    teamIds: [3, 25],
    group: "division",
  },
  {
    id: "jets-dolphins",
    name: "Jets–Dolphins",
    teamIds: [13, 25],
    group: "division",
  },
  {
    id: "bills-jets",
    name: "Bills–Jets",
    teamIds: [20, 13],
    group: "division",
  },
  {
    id: "saints-falcons",
    name: "Saints–Falcons",
    teamIds: [27, 8],
    group: "division",
  },
  {
    id: "saints-buccaneers",
    name: "Saints–Buccaneers",
    teamIds: [27, 24],
    group: "division",
  },
  {
    id: "saints-panthers",
    name: "Saints–Panthers",
    teamIds: [27, 19],
    group: "division",
  },
  {
    id: "falcons-panthers",
    name: "Falcons–Panthers",
    teamIds: [8, 19],
    group: "division",
  },
  {
    id: "falcons-buccaneers",
    name: "Falcons–Buccaneers",
    teamIds: [8, 24],
    group: "division",
  },
  {
    id: "panthers-buccaneers",
    name: "Panthers–Buccaneers",
    teamIds: [19, 24],
    group: "division",
  },
  {
    id: "49ers-seahawks",
    name: "49ers–Seahawks",
    teamIds: [14, 23],
    group: "division",
  },
  {
    id: "49ers-rams",
    name: "49ers–Rams",
    teamIds: [14, 31],
    group: "division",
  },
  {
    id: "49ers-cardinals",
    name: "49ers–Cardinals",
    teamIds: [14, 11],
    group: "division",
  },
  {
    id: "rams-seahawks",
    name: "Rams–Seahawks",
    teamIds: [31, 23],
    group: "division",
  },
  {
    id: "rams-cardinals",
    name: "Rams–Cardinals",
    teamIds: [31, 11],
    group: "division",
  },
  {
    id: "seahawks-cardinals",
    name: "Seahawks–Cardinals",
    teamIds: [23, 11],
    group: "division",
  },
  {
    id: "texans-titans",
    name: "Texans–Titans",
    teamIds: [26, 6],
    group: "division",
  },
  {
    id: "colts-titans",
    name: "Colts–Titans",
    teamIds: [21, 6],
    group: "division",
  },
  {
    id: "colts-texans",
    name: "Colts–Texans",
    teamIds: [21, 26],
    group: "division",
  },
  {
    id: "colts-jaguars",
    name: "Colts–Jaguars",
    teamIds: [21, 2],
    group: "division",
  },
  {
    id: "jaguars-titans",
    name: "Jaguars–Titans",
    teamIds: [2, 6],
    group: "division",
  },
  {
    id: "jaguars-texans",
    name: "Jaguars–Texans",
    teamIds: [2, 26],
    group: "division",
  },
  {
    id: "cowboys-49ers",
    name: "Cowboys–49ers",
    teamIds: [29, 14],
    group: "national",
  },
  {
    id: "patriots-colts",
    name: "Patriots–Colts",
    teamIds: [3, 21],
    group: "national",
  },
] as const satisfies readonly NFLRivalry[];

function createRivalryKey(teamA: number, teamB: number): string {
  return teamA < teamB ? `${teamA}:${teamB}` : `${teamB}:${teamA}`;
}

const NFL_RIVALRY_MAP = new Map<string, NFLRivalry>(
  NFL_RIVALRIES.map((rivalry) => [
    createRivalryKey(rivalry.teamIds[0], rivalry.teamIds[1]),
    rivalry,
  ]),
);

export function getNFLRivalry(
  homeTeamId: number | string | null | undefined,
  awayTeamId: number | string | null | undefined,
): NFLRivalry | undefined {
  if (homeTeamId == null || awayTeamId == null) return undefined;
  const homeId = Number(homeTeamId);
  const awayId = Number(awayTeamId);
  if (!Number.isFinite(homeId) || !Number.isFinite(awayId)) return undefined;
  return NFL_RIVALRY_MAP.get(createRivalryKey(homeId, awayId));
}

export function isNFLRivalry(
  homeTeamId: number | string | null | undefined,
  awayTeamId: number | string | null | undefined,
): boolean {
  return getNFLRivalry(homeTeamId, awayTeamId) !== undefined;
}
