// Logos
import { Team } from "@/types/team";
const placeholderLogo =
  "https://res.cloudinary.com/dm3qtdhag/image/upload/v1781619331/placeholder/team.png";

export const gleagueTeams: Team[] = [
  {
    id: 1,
    espnId: 1,
    name: "Clippers",
    shortName: "Clippers",
    fullName: "San Diego Clippers",
    code: "SAN",
    color: "#C8102E",
    secondaryColor: "#1D428A",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/san.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/san.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 2,
    espnId: 2,
    name: "Spurs",
    shortName: "Spurs",
    fullName: "Austin Spurs",
    code: "AUS",
    color: "#000000",
    secondaryColor: "#C4CED4",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/aus.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/aus.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 3,
    espnId: 3,
    name: "Charge",
    shortName: "Charge",
    fullName: "Cleveland Charge",
    code: "CLC",
    color: "#061642",
    secondaryColor: "#fdbb30",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/clc.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/clc.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 4,
    espnId: 4,
    name: "Go-Go",
    shortName: "Go-Go",
    fullName: "Capital City Go-Go",
    code: "CAP",
    color: "#002B5C",
    secondaryColor: "#E31837",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/cap.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/cap.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 5,
    espnId: 5,
    name: "Blue Coats",
    shortName: "Blue Coats",
    fullName: "Delaware Blue Coats",
    code: "DEL",
    color: "#003DA6",
    secondaryColor: "#DD0031",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/del.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/del.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 6,
    espnId: 6,
    name: "Squadron",
    shortName: "Squadron",
    fullName: "Birmingham Squadron",
    code: "BIR",
    color: "#002A5C",
    secondaryColor: "#b4975a",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/bir.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/bir.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 7,
    espnId: 7,
    name: "Boom",
    shortName: "Boom",
    fullName: "Noblesville Boom",
    code: "NOB",
    color: "#002D62",
    secondaryColor: "#FDBB30",
    logo: "https://a.espncdn.com/guid/373d77e0-4edd-aaeb-ec83-eefc2ca511cb/logos/default.png",
    logoLight:
      "https://a.espncdn.com/guid/373d77e0-4edd-aaeb-ec83-eefc2ca511cb/logos/default-dark.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 8,
    espnId: 8,
    name: "Gold",
    shortName: "Gold",
    fullName: "Grand Rapids Gold",
    code: "GRD",
    color: "#C8102E",
    secondaryColor: "#1D428A",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/grd.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/grd.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 9,
    espnId: 9,
    name: "Swarm",
    shortName: "Swarm",
    fullName: "Greensboro Swarm",
    code: "GBO",
    color: "#007BBC",
    secondaryColor: "#1D1160",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/gbo.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/gbo.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 10,
    espnId: 10,
    name: "Wolves",
    shortName: "Wolves",
    fullName: "Iowa Wolves",
    code: "IWA",
    color: "#0C2340",
    secondaryColor: "#236192",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/iwa.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/iwa.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 11,
    espnId: 11,
    name: "Magic",
    shortName: "Magic",
    fullName: "Osceola Magic",
    code: "OSC",
    color: "#000000",
    secondaryColor: "#0077C0",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/osc.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/osc.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 12,
    espnId: 12,
    name: "Nets",
    shortName: "Nets",
    fullName: "Long Island Nets",
    code: "LIN",
    color: "#006BB6",
    secondaryColor: "#ED174C",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/lin.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/lin.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 13,
    espnId: 13,
    name: "Celtics",
    shortName: "Celtics",
    fullName: "Maine Celtics",
    code: "MNE",
    color: "#006532",
    secondaryColor: "#f1f2f3",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/mne.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/mne.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 14,
    espnId: 14,
    name: "Hustle",
    shortName: "Hustle",
    fullName: "Memphis Hustle",
    code: "MHU",
    color: "#E2231A",
    secondaryColor: "#717271",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/mhu.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/mhu.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 15,
    espnId: 15,
    name: "Cruise",
    shortName: "Cruise",
    fullName: "Motor City Cruise",
    code: "MCC",
    color: "#FA002C",
    secondaryColor: "#006bb6",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/mcc.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/mcc.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 16,
    espnId: 16,
    name: "Blue",
    shortName: "Blue",
    fullName: "Oklahoma City Blue",
    code: "OKL",
    color: "#007AC1",
    secondaryColor: "#EF3B24",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/okl.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/okl.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 17,
    espnId: 17,
    name: "905",
    shortName: "905",
    fullName: "Raptors 905",
    code: "RAP",
    color: "#CE1141",
    secondaryColor: "#000000",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/rap.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/rap.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 18,
    espnId: 18,
    name: "Vipers",
    shortName: "Vipers",
    fullName: "Rio Grande Valley Vipers",
    code: "RGV",
    color: "#CE1141",
    secondaryColor: "#BEC0C2",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/rgv.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/rgv.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 19,
    espnId: 19,
    name: "Stars",
    shortName: "Stars",
    fullName: "Salt Lake City Stars",
    code: "SLC",
    color: "#002B5C",
    secondaryColor: "#F9A01B",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/slc.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/slc.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 20,
    espnId: 20,
    name: "Warriors",
    shortName: "Warriors",
    fullName: "Santa Cruz Warriors",
    code: "SCW",
    color: "#006BB6",
    secondaryColor: "#FDB927",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/scw.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/scw.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 21,
    espnId: 21,
    name: "Skyforce",
    shortName: "Skyforce",
    fullName: "Sioux Falls Skyforce",
    code: "SXF",
    color: "#000000",
    secondaryColor: "#98002E",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/sxf.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/sxf.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 22,
    espnId: 22,
    name: "Lakers",
    shortName: "Lakers",
    fullName: "Coachella Valley Lakers",
    code: "CVL",
    color: "#552583",
    secondaryColor: "#FDB927",
    logo: "https://a.espncdn.com/guid/ed81f2d5-eaa5-343d-5b76-c685a731f733/logos/default.png",
    logoLight:
      "https://a.espncdn.com/guid/ed81f2d5-eaa5-343d-5b76-c685a731f733/logos/default-dark.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 23,
    espnId: 23,
    name: "Kings",
    shortName: "Kings",
    fullName: "Stockton Kings",
    code: "STO",
    color: "#5A2D81",
    secondaryColor: "#000000",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/sto.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/sto.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 24,
    espnId: 24,
    name: "Legends",
    shortName: "Legends",
    fullName: "Texas Legends",
    code: "TEX",
    color: "#0053BC",
    secondaryColor: "#00285E",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/tex.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/tex.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 25,
    espnId: 25,
    name: "Knicks",
    shortName: "Knicks",
    fullName: "Westchester Knicks",
    code: "WES",
    color: "#006BB6",
    secondaryColor: "#F58426",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/wes.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/wes.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 26,
    espnId: 26,
    name: "Bulls",
    shortName: "Bulls",
    fullName: "Windy City Bulls",
    code: "WCB",
    color: "#CE1141",
    secondaryColor: "#000000",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/wcb.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/wcb.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 27,
    espnId: 27,
    name: "Herd",
    shortName: "Herd",
    fullName: "Wisconsin Herd",
    code: "WIS",
    color: "#00471B",
    secondaryColor: "#EEE1C6",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/wis.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/wis.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 28,
    espnId: 28,
    name: "Skyhawks",
    shortName: "Skyhawks",
    fullName: "College Park Skyhawks",
    code: "CPS",
    color: "#000000",
    secondaryColor: "#b3042a",
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/cps.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/cps.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 123432,
    espnId: 123432,
    name: "Ignite",
    shortName: "Ignite",
    fullName: "G League Ignite",
    code: "GLI",
    color: null,
    secondaryColor: null,
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/gli.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/gli.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 124612,
    espnId: 124612,
    name: "Capitanes",
    shortName: "Capitanes",
    fullName: "Mexico City Capitanes",
    code: "MXC",
    color: "#3A4C98",
    secondaryColor: null,
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/mxc.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/mxc.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 128019,
    espnId: 128019,
    name: "Remix",
    shortName: "Remix",
    fullName: "Rip City Remix",
    code: "RCITY",
    color: null,
    secondaryColor: null,
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/rcity.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/rcity.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 129713,
    espnId: 129713,
    name: "Suns",
    shortName: "Suns",
    fullName: "Valley Suns",
    code: "VALLEY",
    color: null,
    secondaryColor: null,
    logo: "https://a.espncdn.com/i/teamlogos/nba-development/500/valley.png",
    logoLight:
      "https://a.espncdn.com/i/teamlogos/nba-development/500-dark/valley.png",
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 129829,
    espnId: 129829,
    name: "United",
    shortName: "United",
    fullName: "G League United",
    code: "UTD",
    color: null,
    secondaryColor: null,
    logo: null,
    logoLight: null,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
  {
    id: 129830,
    espnId: 129830,
    name: "MIS",
    shortName: "MIS",
    fullName: "MEGA MIS",
    code: "MEGA",
    color: null,
    secondaryColor: null,
    logo: null,
    logoLight: null,
    isActive: false,
    isAllStar: false,
    isNational: false,
    league: "gleague",
    city: null,
    location: null,
    established: 0,
  },
];

export const getGLeagueTeam = (id: number | string) => {
  if (id == null) return undefined;
  return gleagueTeams.find((t) => String(t.id) === String(id));
};

export function getGLeagueTeamLogo(
  id: number | string | undefined,
  isDark: boolean,
) {
  if (id === undefined || id === null || id === "") {
    return placeholderLogo;
  }

  const normalizedId = String(id);

  const team = gleagueTeams.find(
    (team) =>
      String(team.id) === normalizedId ||
      String(team.summerLeagueId) === normalizedId,
  );

  if (!team) {
    return placeholderLogo;
  }

  return isDark
    ? (team.logoLight ?? team.logo ?? placeholderLogo)
    : (team.logo ?? placeholderLogo);
}
