import { Team } from "@/types/football/football";
const placeholderLogo =
  "https://res.cloudinary.com/dm3qtdhag/image/upload/v1781619331/placeholder/team.png";

export const soccerTeams: Team[] = [
  {
    id: 21812,
    espnId: 21812,
    fullName: "St. Louis CITY SC",
    code: "STL",
    city: "St. Louis",
    location: "St. Louis, MO",
    coach: "Yoann Damet",
    owner: "Carolyn Kindle",
    established: 2019,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/21812.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/21812.png",
    name: "St. Louis CITY SC",
    shortName: "St. Louis",
    color: "#ec1458",
    secondaryColor: "#001544",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7318,
    espnId: 7318,
    fullName: "Toronto FC",
    code: "TOR",
    city: "Toronto",
    location: "Toronto, ON",
    coach: "Robin Fraser",
    owner: "Maple Leaf Sports & Entertainment",
    established: 2005,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/7318.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/7318.png",
    name: "Toronto FC",
    shortName: "Toronto",
    color: "#aa182c",
    secondaryColor: "#a2a9ad",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9727,
    espnId: 9727,
    fullName: "Vancouver Whitecaps",
    code: "VAN",
    city: "Vancouver",
    location: "Vancouver, BC",
    coach: "Jesper Sørensen",
    owner: "Greg Kerfoot, Steve Luczo, Jeff Mallett, Steve Nash",
    established: 1974,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9727.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/9727.png",
    name: "Vancouver Whitecaps",
    shortName: "Vancouver",
    color: "#ffffff",
    secondaryColor: "#12284c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 624,
    espnId: 624,
    fullName: "Algeria",
    code: "ALG",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/alg.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/alg.png",
    name: "Algeria",
    shortName: "Algeria",
    color: "#5bbd19",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 202,
    espnId: 202,
    fullName: "Argentina",
    code: "ARG",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/arg.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/arg.png",
    name: "Argentina",
    shortName: "Argentina",
    color: "#74acdf",
    secondaryColor: "#173e69",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 628,
    espnId: 628,
    fullName: "Australia",
    code: "AUS",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/aus.png",
    name: "Australia",
    shortName: "Australia",
    color: "#2a2d7c",
    secondaryColor: "#ed2f31",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 474,
    espnId: 474,
    fullName: "Austria",
    code: "AUT",
    city: "Vienna",
    location: "Vienna, Austria",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/aut.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/aut.png",
    name: "Austria",
    shortName: "Austria",
    color: "#d72b2c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 459,
    espnId: 459,
    fullName: "Belgium",
    code: "BEL",
    city: "Brussels",
    location: "Brussels, Belgium",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/bel.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/bel.png",
    name: "Belgium",
    shortName: "Belgium",
    color: "#ef3340",
    secondaryColor: "#d7e9f6",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 452,
    espnId: 452,
    fullName: "Bosnia-Herzegovina",
    code: "BIH",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/bih.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/bih.png",
    name: "Bosnia-Herzegovina",
    shortName: "Bosnia-Herz",
    color: "#112855",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 205,
    espnId: 205,
    fullName: "Brazil",
    code: "BRA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/bra.png",
    name: "Brazil",
    shortName: "Brazil",
    color: "#fee000",
    secondaryColor: "#009c37",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 206,
    espnId: 206,
    fullName: "Canada",
    code: "CAN",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/can.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/can.png",
    name: "Canada",
    shortName: "Canada",
    color: "#ed2224",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2597,
    espnId: 2597,
    fullName: "Cape Verde",
    code: "CPV",
    city: "Praia",
    location: "Praia, Cape Verde",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/cpv.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/cpv.png",
    name: "Cape Verde",
    shortName: "Cape Verde",
    color: "#0000ff",
    secondaryColor: "#EF3340",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 208,
    espnId: 208,
    fullName: "Colombia",
    code: "COL",
    city: "Barranquilla",
    location: "Barranquilla, Colombia",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/col.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/col.png",
    name: "Colombia",
    shortName: "Colombia",
    color: "#fbd632",
    secondaryColor: "#21418c",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2850,
    espnId: 2850,
    fullName: "Congo DR",
    code: "COD",
    city: "Kinshasa",
    location: "Kinshasa, DR Congo",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/rdc.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/rdc.png",
    name: "Congo DR",
    shortName: "Congo DR",
    color: "#418fde",
    secondaryColor: "#C60000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 477,
    espnId: 477,
    fullName: "Croatia",
    code: "CRO",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/cro.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/cro.png",
    name: "Croatia",
    shortName: "Croatia",
    color: "#ff0000",
    secondaryColor: "#0c2fff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 11678,
    espnId: 11678,
    fullName: "Curaçao",
    code: "CUW",
    city: "Willemstad",
    location: "Willemstad, Curaçao",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/11678.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500/11678.png",
    name: "Curaçao",
    shortName: "Curaçao",
    color: "#0537e4",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 450,
    espnId: 450,
    fullName: "Czechia",
    code: "CZE",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/cze.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/cze.png",
    name: "Czechia",
    shortName: "Czechia",
    color: "#d7141a",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 209,
    espnId: 209,
    fullName: "Ecuador",
    code: "ECU",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/ecu.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/ecu.png",
    name: "Ecuador",
    shortName: "Ecuador",
    color: "#ffdd00",
    secondaryColor: "#034ea2",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2620,
    espnId: 2620,
    fullName: "Egypt",
    code: "EGY",
    city: "Cairo",
    location: "Cairo, Egypt",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/egy.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/egy.png",
    name: "Egypt",
    shortName: "Egypt",
    color: "#D20300",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 448,
    espnId: 448,
    fullName: "England",
    code: "ENG",
    city: "London",
    location: "London, England",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/eng.png",
    name: "England",
    shortName: "England",
    color: "#ffffff",
    secondaryColor: "#EA1F29",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 478,
    espnId: 478,
    fullName: "France",
    code: "FRA",
    city: "Saint-Denis",
    location: "Saint-Denis, France",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/fra.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/fra.png",
    name: "France",
    shortName: "France",
    color: "#0c2fff",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 481,
    espnId: 481,
    fullName: "Germany",
    code: "GER",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/ger.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/ger.png",
    name: "Germany",
    shortName: "Germany",
    color: "#000000",
    secondaryColor: "#db41a9",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4469,
    espnId: 4469,
    fullName: "Ghana",
    code: "GHA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/gha.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/gha.png",
    name: "Ghana",
    shortName: "Ghana",
    color: "#ce2931",
    secondaryColor: "#fbd632",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2654,
    espnId: 2654,
    fullName: "Haiti",
    code: "HAI",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/hai.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/hai.png",
    name: "Haiti",
    shortName: "Haiti",
    color: "#0033a0",
    secondaryColor: "#D20300",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 469,
    espnId: 469,
    fullName: "Iran",
    code: "IRN",
    city: "Tehran",
    location: "Tehran, Iran",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/irn.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/irn.png",
    name: "Iran",
    shortName: "Iran",
    color: "#da0000",
    secondaryColor: "#239f40",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4375,
    espnId: 4375,
    fullName: "Iraq",
    code: "IRQ",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/irq.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/irq.png",
    name: "Iraq",
    shortName: "Iraq",
    color: "#00843d",
    secondaryColor: "#CE1126",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4789,
    espnId: 4789,
    fullName: "Ivory Coast",
    code: "CIV",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/civ.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/civ.png",
    name: "Ivory Coast",
    shortName: "Ivory Coast",
    color: "#d48c00",
    secondaryColor: "#5bbd19",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 627,
    espnId: 627,
    fullName: "Japan",
    code: "JPN",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/jpn.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/jpn.png",
    name: "Japan",
    shortName: "Japan",
    color: "#ed1c24",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2917,
    espnId: 2917,
    fullName: "Jordan",
    code: "JOR",
    city: "Amman",
    location: "Amman, Jordan",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/jor.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/jor.png",
    name: "Jordan",
    shortName: "Jordan",
    color: "#E70000",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 203,
    espnId: 203,
    fullName: "Mexico",
    code: "MEX",
    city: "Mexico City",
    location: "Mexico City, Mexico",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/mex.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/mex.png",
    name: "Mexico",
    shortName: "Mexico",
    color: "#006847",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2869,
    espnId: 2869,
    fullName: "Morocco",
    code: "MAR",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/mar.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/mar.png",
    name: "Morocco",
    shortName: "Morocco",
    color: "#009060",
    secondaryColor: "#df2027",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 449,
    espnId: 449,
    fullName: "Netherlands",
    code: "NED",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/ned.png",
    name: "Netherlands",
    shortName: "Netherlands",
    color: "#fb5d00",
    secondaryColor: "#010080",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2666,
    espnId: 2666,
    fullName: "New Zealand",
    code: "NZL",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/nzl.png",
    name: "New Zealand",
    shortName: "New Zealand",
    color: "#273476",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 464,
    espnId: 464,
    fullName: "Norway",
    code: "NOR",
    city: "Oslo",
    location: "Oslo, Norway",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/nor.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/nor.png",
    name: "Norway",
    shortName: "Norway",
    color: "#ef2b2d",
    secondaryColor: "#002868",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2659,
    espnId: 2659,
    fullName: "Panama",
    code: "PAN",
    city: "Panama City",
    location: "Panama City, Panama",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/pan.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/pan.png",
    name: "Panama",
    shortName: "Panama",
    color: "#d21034",
    secondaryColor: "#005293",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 210,
    espnId: 210,
    fullName: "Paraguay",
    code: "PAR",
    city: "Asunción",
    location: "Asunción, Paraguay",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/par.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/par.png",
    name: "Paraguay",
    shortName: "Paraguay",
    color: "#ea2300",
    secondaryColor: "#0c2fff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 482,
    espnId: 482,
    fullName: "Portugal",
    code: "POR",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/por.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/por.png",
    name: "Portugal",
    shortName: "Portugal",
    color: "#da291c",
    secondaryColor: "#d7e9f6",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 4398,
    espnId: 4398,
    fullName: "Qatar",
    code: "QAT",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/qat.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/qat.png",
    name: "Qatar",
    shortName: "Qatar",
    color: "#691a40",
    secondaryColor: "#691a40",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 655,
    espnId: 655,
    fullName: "Saudi Arabia",
    code: "KSA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/ksa.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/ksa.png",
    name: "Saudi Arabia",
    shortName: "Saudi Arabia",
    color: "#dddddd",
    secondaryColor: "#006233",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 580,
    espnId: 580,
    fullName: "Scotland",
    code: "SCO",
    city: "Glasgow",
    location: "Glasgow, Scotland",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/sco.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/sco.png",
    name: "Scotland",
    shortName: "Scotland",
    color: "#1a2d69",
    secondaryColor: "#dcf5f7",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 654,
    espnId: 654,
    fullName: "Senegal",
    code: "SEN",
    city: "Diamniadio",
    location: "Diamniadio, Senegal",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/sen.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/sen.png",
    name: "Senegal",
    shortName: "Senegal",
    color: "#00853f",
    secondaryColor: "#fdef42",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 467,
    espnId: 467,
    fullName: "South Africa",
    code: "RSA",
    city: "Johannesburg",
    location: "Johannesburg, South Africa",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/rsa.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/rsa.png",
    name: "South Africa",
    shortName: "South Africa",
    color: "#087d5a",
    secondaryColor: "#fbb516",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 451,
    espnId: 451,
    fullName: "South Korea",
    code: "KOR",
    city: "Seoul",
    location: "Seoul, South Korea",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/kors.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/kors.png",
    name: "South Korea",
    shortName: "South Korea",
    color: "#ce2028",
    secondaryColor: "#1e4384",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 164,
    espnId: 164,
    fullName: "Spain",
    code: "ESP",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/esp.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/esp.png",
    name: "Spain",
    shortName: "Spain",
    color: "#c60b1e",
    secondaryColor: "#f1ff91",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 466,
    espnId: 466,
    fullName: "Sweden",
    code: "SWE",
    city: "Solna",
    location: "Solna, Sweden",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/swe.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/swe.png",
    name: "Sweden",
    shortName: "Sweden",
    color: "#fecb00",
    secondaryColor: "#006aa7",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 475,
    espnId: 475,
    fullName: "Switzerland",
    code: "SUI",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/sui.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/sui.png",
    name: "Switzerland",
    shortName: "Switzerland",
    color: "#d72b2c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 659,
    espnId: 659,
    fullName: "Tunisia",
    code: "TUN",
    city: "Radès",
    location: "Radès, Tunisia",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/tun.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/tun.png",
    name: "Tunisia",
    shortName: "Tunisia",
    color: "#D20300",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 465,
    espnId: 465,
    fullName: "Türkiye",
    code: "TUR",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/tur.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/tur.png",
    name: "Türkiye",
    shortName: "Türkiye",
    color: "#ffffff",
    secondaryColor: "#ef3340",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 660,
    espnId: 660,
    fullName: "United States",
    code: "USA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/usa.png",
    name: "United States",
    shortName: "USA",
    color: "#213065",
    secondaryColor: "#d42339",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 212,
    espnId: 212,
    fullName: "Uruguay",
    code: "URU",
    city: "Montevideo",
    location: "Montevideo, Uruguay",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/uru.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/uru.png",
    name: "Uruguay",
    shortName: "Uruguay",
    color: "#003da5",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 2570,
    espnId: 2570,
    fullName: "Uzbekistan",
    code: "UZB",
    city: "Tashkent",
    location: "Tashkent, Uzbekistan",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/uzb.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/uzb.png",
    name: "Uzbekistan",
    shortName: "Uzbekistan",
    color: "#0081d6",
    secondaryColor: "#1EB53A",
    isAllStar: false,
    isActive: false,
    isNational: true,
  },
  {
    id: 18418,
    espnId: 18418,
    fullName: "Atlanta United FC",
    code: "ATL",
    city: "Atlanta",
    location: "Atlanta, GA",
    coach: "Gerardo Martino",
    owner: "Arthur Blank",
    established: 2014,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18418.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/18418.png",
    name: "Atlanta United FC",
    shortName: "Atlanta",
    color: "#9d2235",
    secondaryColor: "#aa9767",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 20906,
    espnId: 20906,
    fullName: "Austin FC",
    code: "ATX",
    city: "Austin",
    location: "Austin, TX",
    coach: "Davy Arnaud (interim)",
    owner: "Two Oak Ventures",
    established: 2018,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/20906.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/20906.png",
    name: "Austin FC",
    shortName: "Austin",
    color: "#00b140",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9720,
    espnId: 9720,
    fullName: "CF Montréal",
    code: "MTL",
    city: "Montreal",
    location: "Montreal, QC",
    coach: "Philippe Eullaffroy (interim)",
    owner: "Joey Saputo",
    established: 1992,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9720.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/9720.png",
    name: "CF Montréal",
    shortName: "CF Montréal",
    color: "#003da6",
    secondaryColor: "#c1c5c8",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 21300,
    espnId: 21300,
    fullName: "Charlotte FC",
    code: "CLT",
    city: "Charlotte",
    location: "Charlotte, NC",
    coach: "Dean Smith",
    owner: "David Tepper",
    established: 2019,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/21300.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/21300.png",
    name: "Charlotte FC",
    shortName: "Charlotte",
    color: "#0085ca",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 182,
    espnId: 182,
    fullName: "Chicago Fire FC",
    code: "CHI",
    city: "Chicago",
    location: "Chicago, IL",
    coach: "Gregg Berhalter",
    owner: "Joe Mansueto",
    established: 1997,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/182.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/182.png",
    name: "Chicago Fire FC",
    shortName: "Chicago",
    color: "#7ccdef",
    secondaryColor: "#ff0000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 184,
    espnId: 184,
    fullName: "Colorado Rapids",
    code: "COL",
    city: "Commerce City",
    location: "Commerce City, CO",
    coach: "Matt Wells",
    owner: "Kroenke Sports & Entertainment",
    established: 1995,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/184.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/184.png",
    name: "Colorado Rapids",
    shortName: "Colorado",
    color: "#8a2432",
    secondaryColor: "#8ab7e9",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 183,
    espnId: 183,
    fullName: "Columbus Crew",
    code: "CLB",
    city: "Columbus",
    location: "Columbus, OH",
    coach: "Henrik Rydström",
    owner: "Haslam Sports Group",
    established: 1994,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/183.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/183.png",
    name: "Columbus Crew",
    shortName: "Columbus",
    color: "#000000",
    secondaryColor: "#fedd00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 193,
    espnId: 193,
    fullName: "D.C. United",
    code: "DC",
    city: "Washington",
    location: "Washington, DC",
    coach: "René Weiler",
    owner: "D.C. United Holdings",
    established: 1994,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/193.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/193.png",
    name: "D.C. United",
    shortName: "D.C. United",
    color: "#000000",
    secondaryColor: "#d61018",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18267,
    espnId: 18267,
    fullName: "FC Cincinnati",
    code: "CIN",
    city: "Cincinnati",
    location: "Cincinnati, OH",
    coach: "Pat Noonan",
    owner: "Carl Lindner III",
    established: 2015,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18267.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/18267.png",
    name: "FC Cincinnati",
    shortName: "Cincinnati",
    color: "#003087",
    secondaryColor: "#fe5000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 185,
    espnId: 185,
    fullName: "FC Dallas",
    code: "DAL",
    city: "Frisco",
    location: "Frisco, TX",
    coach: "Eric Quill",
    owner: "Hunt Sports Group",
    established: 1995,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/185.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/185.png",
    name: "FC Dallas",
    shortName: "Dallas",
    color: "#c6093b",
    secondaryColor: "#001f5b",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 6077,
    espnId: 6077,
    fullName: "Houston Dynamo FC",
    code: "HOU",
    city: "Houston",
    location: "Houston, TX",
    coach: "Ben Olsen",
    owner: "Ted Segal",
    established: 2005,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/6077.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/6077.png",
    name: "Houston Dynamo FC",
    shortName: "Houston",
    color: "#ff6b00",
    secondaryColor: "#101820",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 20232,
    espnId: 20232,
    fullName: "Inter Miami CF",
    code: "MIA",
    city: "Miami",
    location: "Miami, FL",
    coach: "Guillermo Hoyos",
    owner: "David Beckham, Jorge Mas, Jose Mas",
    established: 2018,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/20232.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/20232.png",
    name: "Inter Miami CF",
    shortName: "Miami",
    color: "#231f20",
    secondaryColor: "#f7b5cd",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 187,
    espnId: 187,
    fullName: "LA Galaxy",
    code: "LA",
    city: "Carson",
    location: "Carson, CA",
    coach: "Greg Vanney",
    owner: "Anschutz Entertainment Group",
    established: 1994,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/187.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/187.png",
    name: "LA Galaxy",
    shortName: "LA Galaxy",
    color: "#00235d",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18966,
    espnId: 18966,
    fullName: "LAFC",
    code: "LAFC",
    city: "Los Angeles",
    location: "Los Angeles, CA",
    coach: "Marc Dos Santos",
    owner: "Bennett Rosenthal, Brandon Beck, Larry Berg",
    established: 2014,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18966.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/18966.png",
    name: "LAFC",
    shortName: "LAFC",
    color: "#000000",
    secondaryColor: "#c7a36f",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17362,
    espnId: 17362,
    fullName: "Minnesota United FC",
    code: "MIN",
    city: "Saint Paul",
    location: "Saint Paul, MN",
    coach: "Cameron Knowles",
    owner: "Bill McGuire",
    established: 2015,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/17362.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/17362.png",
    name: "Minnesota United FC",
    shortName: "Minnesota",
    color: "#000000",
    secondaryColor: "#9bcde4",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18986,
    espnId: 18986,
    fullName: "Nashville SC",
    code: "NSH",
    city: "Nashville",
    location: "Nashville, TN",
    coach: "B. J. Callaghan",
    owner: "John R. Ingram",
    established: 2016,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18986.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/18986.png",
    name: "Nashville SC",
    shortName: "Nashville",
    color: "#ece83a",
    secondaryColor: "#1f1646",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 189,
    espnId: 189,
    fullName: "New England Revolution",
    code: "NE",
    city: "Foxborough",
    location: "Foxborough, MA",
    coach: "Marko Mitrović",
    owner: "Robert Kraft",
    established: 1994,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/189.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/189.png",
    name: "New England Revolution",
    shortName: "New England",
    color: "#022166",
    secondaryColor: "#ce0e2d",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17606,
    espnId: 17606,
    fullName: "New York City FC",
    code: "NYC",
    city: "New York",
    location: "New York, NY",
    coach: "Pascal Jansen",
    owner: "City Football Group, Yankee Global Enterprises",
    established: 2013,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/17606.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/17606.png",
    name: "New York City FC",
    shortName: "NYCFC",
    color: "#9fd2ff",
    secondaryColor: "#000229",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 12011,
    espnId: 12011,
    fullName: "Orlando City SC",
    code: "ORL",
    city: "Orlando",
    location: "Orlando, FL",
    coach: "Martín Perelman (interim)",
    owner: "Zygi Wilf, Mark Wilf, Lise Wilf",
    established: 2010,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/12011.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/12011.png",
    name: "Orlando City SC",
    shortName: "Orlando",
    color: "#60269e",
    secondaryColor: "#f0d283",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 10739,
    espnId: 10739,
    fullName: "Philadelphia Union",
    code: "PHI",
    city: "Chester",
    location: "Chester, PA",
    coach: "Ryan Richter (interim)",
    owner: "Jay Sugarman",
    established: 2008,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/10739.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/10739.png",
    name: "Philadelphia Union",
    shortName: "Philadelphia",
    color: "#051f31",
    secondaryColor: "#e0d0a6",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9723,
    espnId: 9723,
    fullName: "Portland Timbers",
    code: "POR",
    city: "Portland",
    location: "Portland, OR",
    coach: "Phil Neville",
    owner: "Peregrine Sports",
    established: 2009,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9723.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/9723.png",
    name: "Portland Timbers",
    shortName: "Portland",
    color: "#2c5234",
    secondaryColor: "#c99700",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 4771,
    espnId: 4771,
    fullName: "Real Salt Lake",
    code: "RSL",
    city: "Sandy",
    location: "Sandy, UT",
    coach: "Pablo Mastroeni",
    owner: "David Blitzer, Ryan Smith",
    established: 2004,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/4771.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/4771.png",
    name: "Real Salt Lake",
    shortName: "Salt Lake",
    color: "#a32035",
    secondaryColor: "#daa900",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 190,
    espnId: 190,
    fullName: "Red Bull New York",
    code: "RBNY",
    city: "Harrison",
    location: "Harrison, NJ",
    coach: "Michael Bradley",
    owner: "Red Bull GmbH",
    established: 1994,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/190.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/190.png",
    name: "Red Bull New York",
    shortName: "Red Bull NY",
    color: "#ba0c2f",
    secondaryColor: "#ffc72c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 22529,
    espnId: 22529,
    fullName: "San Diego FC",
    code: "SD",
    city: "San Diego",
    location: "San Diego, CA",
    coach: "Mikey Varas",
    owner: "Mohamed Mansour, Sycuan Band of the Kumeyaay Nation",
    established: 2023,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/22529.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/22529.png",
    name: "San Diego FC",
    shortName: "San Diego",
    color: "#697a7C",
    secondaryColor: "#F89E1A",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 191,
    espnId: 191,
    fullName: "San Jose Earthquakes",
    code: "SJ",
    city: "San Jose",
    location: "San Jose, CA",
    coach: "Bruce Arena",
    owner: "John Fisher",
    established: 1994,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/191.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/191.png",
    name: "San Jose Earthquakes",
    shortName: "San Jose",
    color: "#003da6",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9726,
    espnId: 9726,
    fullName: "Seattle Sounders FC",
    code: "SEA",
    city: "Seattle",
    location: "Seattle, WA",
    coach: "Brian Schmetzer",
    owner: "Adrian Hanauer",
    established: 2007,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9726.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/9726.png",
    name: "Seattle Sounders FC",
    shortName: "Seattle",
    color: "#2dc84d",
    secondaryColor: "#0033a0",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 186,
    espnId: 186,
    fullName: "Sporting Kansas City",
    code: "SKC",
    city: "Kansas City",
    location: "Kansas City, KS",
    coach: "Raphaël Wicky",
    owner: "Sporting Club",
    established: 1995,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/186.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/186.png",
    name: "Sporting Kansas City",
    shortName: "Kansas City",
    color: "#a7c6ed",
    secondaryColor: "#0a2240",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 21812,
    espnId: 21812,
    fullName: "St. Louis CITY SC",
    code: "STL",
    city: "St. Louis",
    location: "St. Louis, MO",
    coach: "Yoann Damet",
    owner: "Carolyn Kindle",
    established: 2019,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/21812.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/21812.png",
    name: "St. Louis CITY SC",
    shortName: "St. Louis",
    color: "#ec1458",
    secondaryColor: "#001544",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7318,
    espnId: 7318,
    fullName: "Toronto FC",
    code: "TOR",
    city: "Toronto",
    location: "Toronto, ON",
    coach: "Robin Fraser",
    owner: "Maple Leaf Sports & Entertainment",
    established: 2005,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/7318.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/7318.png",
    name: "Toronto FC",
    shortName: "Toronto",
    color: "#aa182c",
    secondaryColor: "#a2a9ad",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9727,
    espnId: 9727,
    fullName: "Vancouver Whitecaps",
    code: "VAN",
    city: "Vancouver",
    location: "Vancouver, BC",
    coach: "Jesper Sørensen",
    owner: "Greg Kerfoot, Steve Luczo, Jeff Mallett, Steve Nash",
    established: 1974,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9727.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/9727.png",
    name: "Vancouver Whitecaps",
    shortName: "Vancouver",
    color: "#ffffff",
    secondaryColor: "#12284c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 349,
    espnId: 349,
    fullName: "AFC Bournemouth",
    code: "BOU",
    city: "Bournemouth",
    location: "Bournemouth, England",
    coach: "Marco Rose",
    owner: "Black Knight Football Club UK Limited",
    established: 1899,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/349.png",
    name: "AFC Bournemouth",
    shortName: "Bournemouth",
    color: "#f42727",
    secondaryColor: "#0000CC",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 359,
    espnId: 359,
    fullName: "Arsenal",
    code: "ARS",
    city: "London",
    location: "London, England",
    coach: "Mikel Arteta",
    owner: "Kroenke Sports & Entertainment",
    established: 1886,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/359.png",
    name: "Arsenal",
    shortName: "Arsenal",
    color: "#e20520",
    secondaryColor: "#003399",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 362,
    espnId: 362,
    fullName: "Aston Villa",
    code: "AVL",
    city: "Birmingham",
    location: "Birmingham, England",
    coach: "Unai Emery",
    owner: "Nassef Sawiris, Wes Edens",
    established: 1874,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/362.png",
    name: "Aston Villa",
    shortName: "Aston Villa",
    color: "#660e36",
    secondaryColor: "#333333",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 337,
    espnId: 337,
    fullName: "Brentford",
    code: "BRE",
    city: "London",
    location: "London, England",
    coach: "Keith Andrews",
    owner: "Matthew Benham",
    established: 1889,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/337.png",
    name: "Brentford",
    shortName: "Brentford",
    color: "#f42727",
    secondaryColor: "#f8ced9",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 331,
    espnId: 331,
    fullName: "Brighton & Hove Albion",
    code: "BHA",
    city: "Brighton and Hove",
    location: "Brighton and Hove, England",
    coach: "Fabian Hürzeler",
    owner: "Tony Bloom",
    established: 1901,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/331.png",
    name: "Brighton & Hove Albion",
    shortName: "Brighton",
    color: "#0606fa",
    secondaryColor: "#ffdd00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 379,
    espnId: 379,
    fullName: "Burnley",
    code: "BUR",
    city: "Burnley",
    location: "Burnley, England",
    coach: "Mike Jackson (interim)",
    owner: "ALK Capital LLC",
    established: 1882,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/379.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/379.png",
    name: "Burnley",
    shortName: "Burnley",
    color: "#6C1D45",
    secondaryColor: "#00FFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 363,
    espnId: 363,
    fullName: "Chelsea",
    code: "CHE",
    city: "London",
    location: "London, England",
    coach: "Xabi Alonso",
    owner: "BlueCo",
    established: 1905,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/363.png",
    name: "Chelsea",
    shortName: "Chelsea",
    color: "#144992",
    secondaryColor: "#FFFFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 384,
    espnId: 384,
    fullName: "Crystal Palace",
    code: "CRY",
    city: "London",
    location: "London, England",
    owner: "Steve Parish",
    established: 1905,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/384.png",
    name: "Crystal Palace",
    shortName: "C Palace",
    color: "#0202fb",
    secondaryColor: "#ffdd00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 368,
    espnId: 368,
    fullName: "Everton",
    code: "EVE",
    city: "Liverpool",
    location: "Liverpool, England",
    coach: "David Moyes",
    owner: "The Friedkin Group",
    established: 1878,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/368.png",
    name: "Everton",
    shortName: "Everton",
    color: "#0606fa",
    secondaryColor: "#132257",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 370,
    espnId: 370,
    fullName: "Fulham",
    code: "FUL",
    city: "London",
    location: "London, England",
    owner: "Shahid Khan",
    established: 1879,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/370.png",
    name: "Fulham",
    shortName: "Fulham",
    color: "#ffffff",
    secondaryColor: "#00CC00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 357,
    espnId: 357,
    fullName: "Leeds United",
    code: "LEE",
    city: "Leeds",
    location: "Leeds, England",
    coach: "Daniel Farke",
    owner: "49ers Enterprises",
    established: 1919,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/357.png",
    name: "Leeds United",
    shortName: "Leeds",
    color: "#ffffff",
    secondaryColor: "#0000FF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 364,
    espnId: 364,
    fullName: "Liverpool",
    code: "LIV",
    city: "Liverpool",
    location: "Liverpool, England",
    coach: "Andoni Iraola",
    owner: "Fenway Sports Group",
    established: 1892,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/364.png",
    name: "Liverpool",
    shortName: "Liverpool",
    color: "#d11317",
    secondaryColor: "#FFFFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 382,
    espnId: 382,
    fullName: "Manchester City",
    code: "MNC",
    city: "Manchester",
    location: "Manchester, England",
    owner: "City Football Group Limited",
    established: 1880,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/382.png",
    name: "Manchester City",
    shortName: "Man City",
    color: "#99c5ea",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 360,
    espnId: 360,
    fullName: "Manchester United",
    code: "MAN",
    city: "Manchester",
    location: "Manchester, England",
    coach: "Michael Carrick",
    owner: "Manchester United plc",
    established: 1878,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/360.png",
    name: "Manchester United",
    shortName: "Man United",
    color: "#da020e",
    secondaryColor: "#FFFFFF",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 361,
    espnId: 361,
    fullName: "Newcastle United",
    code: "NEW",
    city: "Newcastle upon Tyne",
    location: "Newcastle upon Tyne, England",
    coach: "Eddie Howe",
    owner: "Public Investment Fund, RB Sports & Media, PCP Capital Partners",
    established: 1892,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/361.png",
    name: "Newcastle United",
    shortName: "Newcastle",
    color: "#000000",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 393,
    espnId: 393,
    fullName: "Nottingham Forest",
    code: "NFO",
    city: "Nottingham",
    location: "Nottingham, England",
    coach: "Vítor Pereira",
    owner: "Evangelos Marinakis",
    established: 1865,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/393.png",
    name: "Nottingham Forest",
    shortName: "Nottm Forest",
    color: "#c8102e",
    secondaryColor: "#132257",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 366,
    espnId: 366,
    fullName: "Sunderland",
    code: "SUN",
    city: "Sunderland",
    location: "Sunderland, England",
    coach: "Régis Le Bris",
    owner: "Kyril Louis-Dreyfus",
    established: 1879,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/366.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/366.png",
    name: "Sunderland",
    shortName: "Sunderland",
    color: "#EB172B",
    secondaryColor: "#87cced",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 367,
    espnId: 367,
    fullName: "Tottenham Hotspur",
    code: "TOT",
    city: "London",
    location: "London, England",
    coach: "Roberto De Zerbi",
    owner: "ENIC International Ltd.",
    established: 1882,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/367.png",
    name: "Tottenham Hotspur",
    shortName: "Spurs",
    color: "#ffffff",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 371,
    espnId: 371,
    fullName: "West Ham United",
    code: "WHU",
    city: "London",
    location: "London, England",
    coach: "Nuno Espírito Santo",
    owner: "David Sullivan, Daniel Křetínský, Vanessa Gold",
    established: 1895,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/371.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/371.png",
    name: "West Ham United",
    shortName: "West Ham",
    color: "#7c2c3b",
    secondaryColor: "#F1E7E0",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 380,
    espnId: 380,
    fullName: "Wolverhampton Wanderers",
    code: "WOL",
    city: "Wolverhampton",
    location: "Wolverhampton, England",
    owner: "Fosun International",
    established: 1877,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/380.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/380.png",
    name: "Wolverhampton Wanderers",
    shortName: "Wolves",
    color: "#fdb913",
    secondaryColor: "#32A8DD",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2750,
    espnId: 2750,
    fullName: "Argentina",
    code: "ARG",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/arg.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/arg.png",
    name: "Argentina",
    shortName: "Argentina",
    color: "#74acdf",
    secondaryColor: "#173e69",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2751,
    espnId: 2751,
    fullName: "Australia",
    code: "AUS",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/aus.png",
    name: "Australia",
    shortName: "Australia",
    color: "#2a2d7c",
    secondaryColor: "#ed2f31",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2752,
    espnId: 2752,
    fullName: "Brazil",
    code: "BRA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/bra.png",
    name: "Brazil",
    shortName: "Brazil",
    color: "#fee000",
    secondaryColor: "#009c37",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2753,
    espnId: 2753,
    fullName: "Canada",
    code: "CAN",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/can.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/can.png",
    name: "Canada",
    shortName: "Canada ",
    color: "#ed2224",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2754,
    espnId: 2754,
    fullName: "China",
    code: "CHN",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/chn.png",
    name: "China",
    shortName: "China",
    color: "#dd342c",
    secondaryColor: "#ffe533",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 11337,
    espnId: 11337,
    fullName: "Colombia",
    code: "COL",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/col.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/col.png",
    name: "Colombia",
    shortName: "Colombia",
    color: "#fbd632",
    secondaryColor: "#21418c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2894,
    espnId: 2894,
    fullName: "Costa Rica",
    code: "CRC",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/crc.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/crc.png",
    name: "Costa Rica",
    shortName: "Costa Rica",
    color: "#ce1126",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2896,
    espnId: 2896,
    fullName: "Denmark",
    code: "DEN",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/den.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/den.png",
    name: "Denmark",
    shortName: "Denmark",
    color: "#d02a3e",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 5159,
    espnId: 5159,
    fullName: "England",
    code: "ENG",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/eng.png",
    name: "England",
    shortName: "England",
    color: "#ce1124",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2755,
    espnId: 2755,
    fullName: "France",
    code: "FRA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/fra.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/fra.png",
    name: "France",
    shortName: "France",
    color: "#002f79",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2756,
    espnId: 2756,
    fullName: "Germany",
    code: "GER",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/ger.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/ger.png",
    name: "Germany",
    shortName: "Germany",
    color: "#000000",
    secondaryColor: "#db2c32",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2891,
    espnId: 2891,
    fullName: "Haiti",
    code: "HAI",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/hai.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/hai.png",
    name: "Haiti",
    shortName: "Haiti",
    color: "#0033a0",
    secondaryColor: "#EF0000",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2792,
    espnId: 2792,
    fullName: "Italy",
    code: "ITA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/ita.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/ita.png",
    name: "Italy",
    shortName: "Italy",
    color: "#24923c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2893,
    espnId: 2893,
    fullName: "Jamaica",
    code: "JAM",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/jam.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/jam.png",
    name: "Jamaica",
    shortName: "Jamaica",
    color: "#348b42",
    secondaryColor: "#f9e032",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2758,
    espnId: 2758,
    fullName: "Japan",
    code: "JPN",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/jpn.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/jpn.png",
    name: "Japan",
    shortName: "Japan",
    color: "#ed1c24",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 18221,
    espnId: 18221,
    fullName: "Morocco",
    code: "MAR",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/mor.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/mor.png",
    name: "Morocco",
    shortName: "Morocco",
    color: "#df2027",
    secondaryColor: "#009060",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7151,
    espnId: 7151,
    fullName: "Netherlands",
    code: "NED",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/ned.png",
    name: "Netherlands",
    shortName: "Netherlands",
    color: "#ec2f00",
    secondaryColor: "#003da5",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 4153,
    espnId: 4153,
    fullName: "New Zealand",
    code: "NZL",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/nzl.png",
    name: "New Zealand",
    shortName: "New Zealand",
    color: "#273476",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2761,
    espnId: 2761,
    fullName: "Nigeria",
    code: "NGA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/nga.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/nga.png",
    name: "Nigeria",
    shortName: "Nigeria",
    color: "#008751",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2762,
    espnId: 2762,
    fullName: "Norway",
    code: "NOR",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/nor.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/nor.png",
    name: "Norway",
    shortName: "Norway",
    color: "#ef2b2d",
    secondaryColor: "#002868",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2895,
    espnId: 2895,
    fullName: "Panama",
    code: "PAN",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/pan.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/pan.png",
    name: "Panama",
    shortName: "Panama",
    color: "#d60a14",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 21546,
    espnId: 21546,
    fullName: "Philippines",
    code: "PHI",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/phi.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/phi.png",
    name: "Philippines",
    shortName: "Philippines",
    color: "#1f449b",
    secondaryColor: "#ce2931",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 9531,
    espnId: 9531,
    fullName: "Portugal",
    code: "POR",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/por.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/por.png",
    name: "Portugal",
    shortName: "Portugal",
    color: "#006600",
    secondaryColor: "#da291c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 4178,
    espnId: 4178,
    fullName: "Republic of Ireland",
    code: "IRL",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/irl.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/irl.png",
    name: "Republic of Ireland",
    shortName: "Rep Ireland",
    color: "#049a64",
    secondaryColor: "#f58241",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 13313,
    espnId: 13313,
    fullName: "South Africa",
    code: "RSA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/rsa.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/rsa.png",
    name: "South Africa",
    shortName: "South Africa",
    color: "#ffef00",
    secondaryColor: "#002f00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17639,
    espnId: 17639,
    fullName: "South Korea",
    code: "KOR",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/kors.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/kors.png",
    name: "South Korea",
    shortName: "South Korea",
    color: "#ce2028",
    secondaryColor: "#1e4384",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17640,
    espnId: 17640,
    fullName: "Spain",
    code: "ESP",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/esp.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/esp.png",
    name: "Spain",
    shortName: "Spain",
    color: "#c60b1e",
    secondaryColor: "#ffc400",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2764,
    espnId: 2764,
    fullName: "Sweden",
    code: "SWE",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/swe.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/swe.png",
    name: "Sweden",
    shortName: "Sweden",
    color: "#fecb00",
    secondaryColor: "#006aa7",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17641,
    espnId: 17641,
    fullName: "Switzerland",
    code: "SUI",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/sui.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/sui.png",
    name: "Switzerland",
    shortName: "Switzerland",
    color: "#d72b2c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2765,
    espnId: 2765,
    fullName: "United States",
    code: "USA",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/usa.png",
    name: "United States",
    shortName: "USA",
    color: "#213065",
    secondaryColor: "#d42339",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 17815,
    espnId: 17815,
    fullName: "Vietnam",
    code: "VIE",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/vie.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/vie.png",
    name: "Vietnam",
    shortName: "Vietnam",
    color: "#DA251D",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 20795,
    espnId: 20795,
    fullName: "Zambia",
    code: "ZAM",
    city: "",
    location: "",
    established: 0,
    logo: "https://a.espncdn.com/i/teamlogos/countries/500/zam.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/countries/500-dark/zam.png",
    name: "Zambia",
    shortName: "Zambia",
    color: "#00843d",
    secondaryColor: "#FFCD00",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 6418,
    espnId: 6418,
    fullName: "1. FC Heidenheim 1846",
    code: "HDH",
    city: "Heidenheim an der Brenz",
    location: "Heidenheim an der Brenz, Germany",
    coach: "Frank Schmidt",
    established: 1846,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/6418.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/6418.png",
    name: "1. FC Heidenheim 1846",
    shortName: "Heidenheim",
    color: "#DA0308",
    secondaryColor: "#003399",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 598,
    espnId: 598,
    fullName: "1. FC Union Berlin",
    code: "FCU",
    city: "Berlin",
    location: "Berlin, Germany",
    coach: "Mauro Lustrinelli",
    established: 1966,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/598.png",
    name: "1. FC Union Berlin",
    shortName: "Union Berlin",
    color: "#DA0308",
    secondaryColor: "#d4d4d4",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 131,
    espnId: 131,
    fullName: "Bayer Leverkusen",
    code: "B04",
    city: "Leverkusen",
    location: "Leverkusen, Germany",
    coach: "Carles Martínez Novell",
    owner: "Bayer AG",
    established: 1904,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/131.png",
    name: "Bayer Leverkusen",
    shortName: "Leverkusen",
    color: "#DA0308",
    secondaryColor: "#f9fbfc",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 132,
    espnId: 132,
    fullName: "Bayern Munich",
    code: "MUN",
    city: "Munich",
    location: "Munich, Germany",
    coach: "Vincent Kompany",
    owner: "FC Bayern München e.V.",
    established: 1900,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/132.png",
    name: "Bayern Munich",
    shortName: "Bayern",
    color: "#dc052d",
    secondaryColor: "#1a1a1a",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 124,
    espnId: 124,
    fullName: "Borussia Dortmund",
    code: "DOR",
    city: "Dortmund",
    location: "Dortmund, Germany",
    coach: "Niko Kovač",
    owner: "Borussia Dortmund GmbH & Co. KGaA",
    established: 1909,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/124.png",
    name: "Borussia Dortmund",
    shortName: "Dortmund",
    color: "#ffee00",
    secondaryColor: "#272726",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 268,
    espnId: 268,
    fullName: "Borussia Mönchengladbach",
    code: "BMG",
    city: "Mönchengladbach",
    location: "Mönchengladbach, Germany",
    coach: "Eugen Polański",
    established: 1900,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/268.png",
    name: "Borussia Mönchengladbach",
    shortName: "Gladbach",
    color: "#ffffff",
    secondaryColor: "#03915c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 125,
    espnId: 125,
    fullName: "Eintracht Frankfurt",
    code: "SGE",
    city: "Frankfurt",
    location: "Frankfurt, Germany",
    coach: "Adi Hütter",
    established: 1899,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/125.png",
    name: "Eintracht Frankfurt",
    shortName: "Frankfurt",
    color: "#ffffff",
    secondaryColor: "#272726",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 3841,
    espnId: 3841,
    fullName: "FC Augsburg",
    code: "FCA",
    city: "Augsburg",
    location: "Augsburg, Germany",
    coach: "Manuel Baum",
    owner: "FC Augsburg 1907 GmbH & Co. KGaA",
    established: 1907,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/3841.png",
    name: "FC Augsburg",
    shortName: "Augsburg",
    color: "#ffffff",
    secondaryColor: "#03915c",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 122,
    espnId: 122,
    fullName: "FC Cologne",
    code: "KOE",
    city: "Cologne",
    location: "Cologne, Germany",
    coach: "René Wagner",
    established: 1948,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/122.png",
    name: "FC Cologne",
    shortName: "Cologne",
    color: "#ffffff",
    secondaryColor: "#DA0308",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 127,
    espnId: 127,
    fullName: "Hamburg SV",
    code: "HSV",
    city: "Hamburg",
    location: "Hamburg, Germany",
    coach: "Merlin Polzin",
    established: 1887,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/127.png",
    name: "Hamburg SV",
    shortName: "Hamburg",
    color: "#1a26af",
    secondaryColor: "#1a1a1a",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 2950,
    espnId: 2950,
    fullName: "Mainz",
    code: "M05",
    city: "Mainz",
    location: "Mainz, Germany",
    coach: "Urs Fischer",
    established: 1905,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/2950.png",
    name: "Mainz",
    shortName: "Mainz",
    color: "#DA0308",
    secondaryColor: "#000055",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 11420,
    espnId: 11420,
    fullName: "RB Leipzig",
    code: "RBL",
    city: "Leipzig",
    location: "Leipzig, Germany",
    coach: "Ole Werner",
    owner: "Red Bull GmbH",
    established: 2009,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/11420.png",
    name: "RB Leipzig",
    shortName: "RB Leipzig",
    color: "#ffffff",
    secondaryColor: "#740c14",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 126,
    espnId: 126,
    fullName: "SC Freiburg",
    code: "SCF",
    city: "Freiburg",
    location: "Freiburg, Germany",
    coach: "Julian Schuster",
    established: 1904,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/126.png",
    name: "SC Freiburg",
    shortName: "Freiburg",
    color: "#DA0308",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 270,
    espnId: 270,
    fullName: "St. Pauli",
    code: "STP",
    city: "Hamburg",
    location: "Hamburg, Germany",
    established: 1910,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/270.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/270.png",
    name: "St. Pauli",
    shortName: "St. Pauli",
    color: "#442e23",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 7911,
    espnId: 7911,
    fullName: "TSG Hoffenheim",
    code: "TSG",
    city: "Sinsheim",
    location: "Sinsheim, Germany",
    coach: "Christian Ilzer",
    owner: "Dietmar Hopp",
    established: 1899,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/7911.png",
    name: "TSG Hoffenheim",
    shortName: "Hoffenheim",
    color: "#003399",
    secondaryColor: "#000055",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 134,
    espnId: 134,
    fullName: "VfB Stuttgart",
    code: "VFB",
    city: "Stuttgart",
    location: "Stuttgart, Germany",
    coach: "Sebastian Hoeneß",
    owner: "VfB Stuttgart 1893 AG",
    established: 1893,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/134.png",
    name: "VfB Stuttgart",
    shortName: "Stuttgart",
    color: "#ffffff",
    secondaryColor: "#DA0308",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 138,
    espnId: 138,
    fullName: "VfL Wolfsburg",
    code: "WOB",
    city: "Wolfsburg",
    location: "Wolfsburg, Germany",
    coach: "Tobias Strobl",
    owner: "Volkswagen AG",
    established: 1945,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/138.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/138.png",
    name: "VfL Wolfsburg",
    shortName: "Wolfsburg",
    color: "#81f733",
    secondaryColor: "#1a1a1a",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 137,
    espnId: 137,
    fullName: "Werder Bremen",
    code: "SVW",
    city: "Bremen",
    location: "Bremen, Germany",
    coach: "Daniel Thioune",
    owner: "SV Werder Bremen GmbH & Co. KG aA",
    established: 1899,
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/137.png",
    name: "Werder Bremen",
    shortName: "Bremen",
    color: "#03915c",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: false,
    isNational: false,
  },
  {
    id: 96,
    espnId: 96,
    name: "Alavés",
    fullName: "Alavés",
    shortName: "Alavés",
    code: "ALA",
    color: "#0000ff",
    secondaryColor: "#c3c3c3",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/96.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 93,
    espnId: 93,
    name: "Athletic Club",
    fullName: "Athletic Club",
    shortName: "Athletic",
    code: "ATH",
    color: "#C8142F",
    secondaryColor: "#0000ff",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/93.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 1068,
    espnId: 1068,
    name: "Atlético Madrid",
    fullName: "Atlético Madrid",
    shortName: "Atlético",
    code: "ATM",
    color: "#ca3624",
    secondaryColor: "#000099",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/1068.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 83,
    espnId: 83,
    name: "Barcelona",
    fullName: "Barcelona",
    shortName: "Barcelona",
    code: "BAR",
    color: "#990000",
    secondaryColor: "#FCE38A",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/83.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 85,
    espnId: 85,
    name: "Celta Vigo",
    fullName: "Celta Vigo",
    shortName: "Celta Vigo",
    code: "CEL",
    color: "#6cace4",
    secondaryColor: "#004996",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/85.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 3751,
    espnId: 3751,
    name: "Elche",
    fullName: "Elche",
    shortName: "Elche",
    code: "ELC",
    color: "#ffffff",
    secondaryColor: "#288A00",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/3751.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/3751.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 88,
    espnId: 88,
    name: "Espanyol",
    fullName: "Espanyol",
    shortName: "Espanyol",
    code: "ESP",
    color: "#3366CC",
    secondaryColor: "#C8142F",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/88.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 2922,
    espnId: 2922,
    name: "Getafe",
    fullName: "Getafe",
    shortName: "Getafe",
    code: "GET",
    color: "#0000ff",
    secondaryColor: "#C8142F",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/2922.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/2922.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 9812,
    espnId: 9812,
    name: "Girona",
    fullName: "Girona",
    shortName: "Girona",
    code: "GIR",
    color: "#C60000",
    secondaryColor: "#004996",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9812.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/9812.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 1538,
    espnId: 1538,
    name: "Levante",
    fullName: "Levante",
    shortName: "Levante",
    code: "LEV",
    color: "#C8142F",
    secondaryColor: "#000000",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/1538.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 84,
    espnId: 84,
    name: "Mallorca",
    fullName: "Mallorca",
    shortName: "Mallorca",
    code: "MLL",
    color: "#C8142F",
    secondaryColor: "#ccff00",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/84.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/84.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 97,
    espnId: 97,
    name: "Osasuna",
    fullName: "Osasuna",
    shortName: "Osasuna",
    code: "OSA",
    color: "#cd0000",
    secondaryColor: "#ffffff",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/97.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 101,
    espnId: 101,
    name: "Rayo Vallecano",
    fullName: "Rayo Vallecano",
    shortName: "Rayo",
    code: "RAY",
    color: "#ffffff",
    secondaryColor: "#cd0000",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/101.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 244,
    espnId: 244,
    name: "Real Betis",
    fullName: "Real Betis",
    shortName: "Betis",
    code: "BET",
    color: "#288A00",
    secondaryColor: "#ccff00",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/244.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 86,
    espnId: 86,
    name: "Real Madrid",
    fullName: "Real Madrid",
    shortName: "Real Madrid",
    code: "RMA",
    color: "#ffffff",
    secondaryColor: "#00529F",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/86.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 92,
    espnId: 92,
    name: "Real Oviedo",
    fullName: "Real Oviedo",
    shortName: "Real Oviedo",
    code: "OVI",
    color: "#e23627",
    secondaryColor: "#ffd200",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/92.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500/92.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 89,
    espnId: 89,
    name: "Real Sociedad",
    fullName: "Real Sociedad",
    shortName: "Real Sociedad",
    code: "RSO",
    color: "#3366CC",
    secondaryColor: "#ffdd00",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/89.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 243,
    espnId: 243,
    name: "Sevilla",
    fullName: "Sevilla",
    shortName: "Sevilla",
    code: "SEV",
    color: "#ffffff",
    secondaryColor: "#d81022",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/243.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 94,
    espnId: 94,
    name: "Valencia",
    fullName: "Valencia",
    shortName: "Valencia",
    code: "VAL",
    color: "#ffffff",
    secondaryColor: "#004996",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/94.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
  {
    id: 102,
    espnId: 102,
    name: "Villarreal",
    fullName: "Villarreal",
    shortName: "Villarreal",
    code: "VIL",
    color: "#ffff00",
    secondaryColor: "#6cace4",
    logo: "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
    logoLight: "https://a.espncdn.com/i/teamlogos/soccer/500-dark/102.png",
    isActive: true,
    isAllStar: false,
    isNational: true,
    city: "",
    location: "",
    established: 0,
  },
];

export const getSOCCTeam = (id: number | string) => {
  if (id == null) return undefined;
  return soccerTeams.find((t) => String(t.id) === String(id));
};

export function getSOCCTeamLogo(
  id: number | string | undefined,
  isDark: boolean,
) {
  const team = soccerTeams.find((t) => String(t.id) === String(id));
  if (!id || team?.logo === null || "") return placeholderLogo;

  return team
    ? isDark
      ? team.logoLight || team.logo || placeholderLogo
      : team.logo || placeholderLogo
    : placeholderLogo;
}
