//Logos
import { Team } from "@/types/football/football";
import NinersLogo from "assets/Football/NFL_Logos/49ers.png";
import AFCLogo from "assets/Football/NFL_Logos/AFC.png";
import BearsLogo from "assets/Football/NFL_Logos/Bears.png";
import BengalsLogo from "assets/Football/NFL_Logos/Bengals.png";
import BillsLogo from "assets/Football/NFL_Logos/Bills.png";
import BroncosLogo from "assets/Football/NFL_Logos/Broncos.png";
import BrownsLogo from "assets/Football/NFL_Logos/Browns.png";
import BuccaneersLogo from "assets/Football/NFL_Logos/Buccaneers.png";
import CardinalsLogo from "assets/Football/NFL_Logos/Cardinals.png";
import ChargersLogo from "assets/Football/NFL_Logos/Chargers.png";
import ChiefsLogo from "assets/Football/NFL_Logos/Chiefs.png";
import ColtsLogo from "assets/Football/NFL_Logos/Colts.png";
import CommandersLogo from "assets/Football/NFL_Logos/Commanders.png";
import CowboysLogo from "assets/Football/NFL_Logos/Cowboys.png";
import DolphinsLogo from "assets/Football/NFL_Logos/Dolphins.png";
import EaglesLogo from "assets/Football/NFL_Logos/Eagles.png";
import FalconsLogo from "assets/Football/NFL_Logos/Falcons.png";
import GiantsLogo from "assets/Football/NFL_Logos/Giants.png";
import GiantsLogoLight from "assets/Football/NFL_Logos/GiantsLight.png";
import JaguarsLogo from "assets/Football/NFL_Logos/Jaguars.png";
import JetsLogo from "assets/Football/NFL_Logos/Jets.png";
import JetsLogoLight from "assets/Football/NFL_Logos/JetsLight.png";
import LionsLogo from "assets/Football/NFL_Logos/Lions.png";
import NFCLogo from "assets/Football/NFL_Logos/NFC.png";
import PackersLogo from "assets/Football/NFL_Logos/Packers.png";
import PanthersLogo from "assets/Football/NFL_Logos/Panthers.png";
import PatriotsLogo from "assets/Football/NFL_Logos/Patriots.png";
import RaidersLogo from "assets/Football/NFL_Logos/Raiders.png";
import RamsLogo from "assets/Football/NFL_Logos/Rams.png";
import RavensLogo from "assets/Football/NFL_Logos/Ravens.png";
import SaintsLogo from "assets/Football/NFL_Logos/Saints.png";
import SeahawksLogo from "assets/Football/NFL_Logos/Seahawks.png";
import SteelersLogo from "assets/Football/NFL_Logos/Steelers.png";
import TexansLogo from "assets/Football/NFL_Logos/Texans.png";
import TitansLogo from "assets/Football/NFL_Logos/Titans.png";
import VikingsLogo from "assets/Football/NFL_Logos/Vikings.png";
import PlaceholderLogo from "assets/Placeholders/teamPlaceholder.png";

export const nflTeams: Team[] = [
  {
    id: 1,
    espnId: 13,
    fullName: "Las Vegas Raiders",
    code: "LV",
    city: "Las Vegas",
    location: "Las Vegas, NV",
    coach: "Pete Carroll",
    owner: "Carol and Mark Davis",
    established: 1960,
    logo: RaidersLogo,
    logoLight: RaidersLogo,
    name: "Raiders",
    color: "#000000",
    secondaryColor: "#a5acaf",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 2,
    espnId: 30,
    fullName: "Jacksonville Jaguars",
    code: "JAX",
    city: "Jacksonville",
    location: "Jacksonville, FL",
    coach: "Liam Coen",
    owner: "Shahid Khan",
    established: 1995,
    logo: JaguarsLogo,
    logoLight: JaguarsLogo,
    name: "Jaguars",
    color: "#101820",
    secondaryColor: "#d7a22a",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 3,
    espnId: 17,
    fullName: "New England Patriots",
    code: "NE",
    city: "Foxborough",
    location: "Foxborough, MA",
    coach: "Mike Vrabel",
    owner: "Robert Kraft",
    established: 1960,
    logo: PatriotsLogo,
    logoLight: PatriotsLogo,
    name: "Patriots",
    color: "#002a5c",
    secondaryColor: "#c60c30",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 4,
    espnId: 19,
    fullName: "New York Giants",
    code: "NYG",
    city: "New York",
    location: "New York, NY",
    coach: "Brian Daboll",
    owner: "John Mara, Steve Tisch",
    established: 1925,
    logo: GiantsLogo,
    logoLight: GiantsLogoLight,
    name: "Giants",
    color: "#003c7f",
    secondaryColor: "#c9243f",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 5,
    espnId: 33,
    fullName: "Baltimore Ravens",
    code: "BAL",
    city: "Baltimore",
    location: "Baltimore, MD",
    coach: "John Harbaugh",
    owner: "Steve Bisciotti",
    established: 1996,
    logo: RavensLogo,
    logoLight: RavensLogo,
    name: "Ravens",
    color: "#29126f",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 6,
    espnId: 10,
    fullName: "Tennessee Titans",
    code: "TEN",
    city: "Nashville",
    location: "Nashville, TN",
    coach: "Brian Callahan",
    owner: "Amy Adams Strunk",
    established: 1960,
    logo: TitansLogo,
    logoLight: TitansLogo,
    name: "Titans",
    color: "#4b92db",
    secondaryColor: "#002a5c",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 7,
    espnId: 8,
    fullName: "Detroit Lions",
    code: "DET",
    city: "Detroit",
    location: "Detroit, MI",
    coach: "Dan Campbell",
    owner: "Sheila Ford Hamp",
    established: 1930,
    logo: LionsLogo,
    logoLight: LionsLogo,
    name: "Lions",
    color: "#0076b6",
    secondaryColor: "#bbbbbb",
    isAllStar: false,
    isActive: true,
  },

  {
    id: 8,
    espnId: 1,
    fullName: "Atlanta Falcons",
    code: "ATL",
    city: "Atlanta",
    location: "Atlanta, GA",
    coach: "Raheem Morris",
    owner: "Arthur Blank",
    established: 1966,
    logo: FalconsLogo,
    logoLight: FalconsLogo,
    name: "Falcons",
    color: "#a71930",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 9,
    espnId: 5,
    fullName: "Cleveland Browns",
    code: "CLE",
    city: "Cleveland",
    location: "Cleveland, OH",
    coach: "Kevin Stefanski",
    owner: "Dee and Jimmy Haslam",
    established: 1946,
    logo: BrownsLogo,
    logoLight: BrownsLogo,
    name: "Browns",
    color: "#472a08",
    secondaryColor: "#ff3c00",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 10,
    espnId: 4,
    fullName: "Cincinnati Bengals",
    code: "CIN",
    city: "Cincinnati",
    location: "Cincinnati, OH",
    coach: "Zac Taylor",
    owner: "Mike Brown",
    established: 1968,
    logo: BengalsLogo,
    logoLight: BengalsLogo,
    name: "Bengals",
    color: "#fb4f14",
    secondaryColor: "000000",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 11,
    espnId: 22,
    fullName: "Arizona Cardinals",
    code: "ARI",
    city: "Glendale",
    location: "Glendale, AZ",
    coach: "Jonathan Gannon",
    owner: "Michael Bidwill",
    established: 1920,
    logo: CardinalsLogo,
    logoLight: CardinalsLogo,
    name: "Cardinals",
    color: "#a40227",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 12,
    espnId: 21,
    fullName: "Philadelphia Eagles",
    code: "PHI",
    city: "Philadelphia",
    location: "Philadelphia, PA",
    coach: "Nick Sirianni",
    owner: "Jeffrey Lurie",
    established: 1933,
    logo: EaglesLogo,
    logoLight: EaglesLogo,
    name: "Eagles",
    color: "#06424d",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 13,
    espnId: 20,
    fullName: "New York Jets",
    code: "NYJ",
    city: "New York",
    location: "New York, NY",
    coach: "Aaron Glenn",
    owner: "Robert Wood Johnson IV",
    established: 1960,
    logo: JetsLogo,
    logoLight: JetsLogoLight,
    name: "Jets",
    color: "#115740",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 14,
    espnId: 25,
    fullName: "San Francisco 49ers",
    code: "SF",
    city: "San Francisco",
    location: "San Francisco, CA",
    coach: "Kyle Shanahan",
    owner: "Jed York",
    established: 1946,
    logo: NinersLogo,
    logoLight: NinersLogo,
    name: "49ers",
    color: "#aa0000",
    secondaryColor: "#b3995d",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 15,
    espnId: 9,

    fullName: "Green Bay Packers",
    code: "GB",
    city: "Green Bay",
    location: "Green Bay, WI",
    coach: "Matt LaFleur",
    owner: "Green Bay Packers, Inc.",
    established: 1921,
    logo: PackersLogo,
    logoLight: PackersLogo,

    name: "Packers",
    color: "#203731",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 16,
    espnId: 3,
    fullName: "Chicago Bears",
    code: "CHI",
    city: "Chicago",
    location: "Chicago, IL",
    coach: "Ben Johnson",
    owner: "Virginia Halas McCaskey",
    established: 1920,
    logo: BearsLogo,
    logoLight: BearsLogo,
    name: "Bears",
    color: "#0B162A",
    secondaryColor: "#e64100",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 17,
    espnId: 12,
    fullName: "Kansas City Chiefs",
    code: "KC",
    city: "Kansas City",
    location: "Kansas City, MO",
    coach: "Andy Reid",
    owner: "Clark Hunt",
    established: 1960,
    logo: ChiefsLogo,
    logoLight: ChiefsLogo,
    name: "Chiefs",
    color: "#E31837",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 18,
    espnId: 28,
    fullName: "Washington Commanders",
    code: "WSH",
    city: "Washington",
    location: "Washington, DC",
    coach: "Dan Quinn",
    owner: "Josh Harris",
    established: 1932,
    logo: CommandersLogo,
    logoLight: CommandersLogo,
    name: "Commanders",
    color: "#5a1414",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 19,
    espnId: 29,
    fullName: "Carolina Panthers",
    code: "CAR",
    city: "Charlotte",
    location: "Charlotte, NC",
    coach: "David Canales",
    owner: "David Tepper",
    established: 1995,
    logo: PanthersLogo,
    logoLight: PanthersLogo,
    name: "Panthers",
    color: "#0085ca",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 20,
    espnId: 2,
    fullName: "Buffalo Bills",
    code: "BUF",
    city: "Buffalo",
    location: "Buffalo, NY",
    coach: "Sean McDermott",
    owner: "Kim and Terry Pegula",
    established: 1960,
    logo: BillsLogo,
    logoLight: BillsLogo,
    name: "Bills",
    color: "#00338d",
    secondaryColor: "#d50a0a",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 21,
    espnId: 11,
    fullName: "Indianapolis Colts",
    code: "IND",
    city: "Indianapolis",
    location: "Indianapolis, IN",
    coach: "Shane Steichen",
    owner: "Jim Irsay",
    established: 1944,
    logo: ColtsLogo,
    logoLight: ColtsLogo,
    name: "Colts",
    color: "#002C5F",
    secondaryColor: "#ffffff",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 22,
    espnId: 23,
    fullName: "Pittsburgh Steelers",
    code: "PIT",
    city: "Pittsburgh",
    location: "Pittsburgh, PA",
    coach: "Mike Tomlin",
    owner: "Art Rooney II and Family",
    established: 1933,
    logo: SteelersLogo,
    logoLight: SteelersLogo,
    name: "Steelers",
    color: "#000000",
    secondaryColor: "#ffb612",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 23,
    espnId: 26,
    fullName: "Seattle Seahawks",
    code: "SEA",
    city: "Seattle",
    location: "Seattle, WA",
    coach: "Mike Macdonald",
    owner: "Seattle Seahawks Ownership Trust",
    established: 1976,
    logo: SeahawksLogo,
    logoLight: SeahawksLogo,
    name: "Seahawks",
    color: "#002244",
    secondaryColor: "#69be28",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 24,
    espnId: 27,
    fullName: "Tampa Bay Buccaneers",
    code: "TB",
    city: "Tampa",
    location: "Tampa, FL",
    coach: "Todd Bowles",
    owner: "Bryan Glazer, Edward Glazer, Joel Glazer",
    established: 1976,
    logo: BuccaneersLogo,
    logoLight: BuccaneersLogo,
    name: "Buccaneers",
    color: "#bd1c36",
    secondaryColor: "#3e3a35",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 25,
    espnId: 15,
    fullName: "Miami Dolphins",
    code: "MIA",
    city: "Miami",
    location: "Miami, FL",
    coach: "Mike McDaniel",
    owner: "Stephen M. Ross",
    established: 1966,
    logo: DolphinsLogo,
    logoLight: DolphinsLogo,
    name: "Dolphins",
    color: "#008e97",
    secondaryColor: "#fc4c02",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 26,
    espnId: 34,
    fullName: "Houston Texans",
    code: "HOU",
    city: "Houston",
    location: "Houston, TX",
    coach: "DeMeco Ryans",
    owner: "Janice S. McNair",
    established: 2002,
    logo: TexansLogo,
    logoLight: TexansLogo,
    name: "Texans",
    color: "#03202f",
    secondaryColor: "#c41230",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 27,
    espnId: 18,
    fullName: "New Orleans Saints",
    code: "NO",
    city: "New Orleans",
    location: "New Orleans, LA",
    coach: "Dennis Allen",
    owner: "Gayle Benson",
    established: 1967,
    logo: SaintsLogo,
    logoLight: SaintsLogo,
    name: "Saints",
    color: "#d3bc8d",
    secondaryColor: "#000000",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 28,
    espnId: 7,
    fullName: "Denver Broncos",
    code: "DEN",
    city: "Denver",
    location: "Denver, CO",
    coach: "Sean Payton",
    owner: "Walton-Penner Family Ownership Group",
    established: 1960,
    logo: BroncosLogo,
    logoLight: BroncosLogo,
    name: "Broncos",
    color: "#0a2343",
    secondaryColor: "#fc4c02",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 29,
    espnId: 6,
    fullName: "Dallas Cowboys",
    code: "DAL",
    city: "Dallas",
    location: "Dallas, TX",
    coach: "Brian Schottenheimer",
    owner: "Jerry Jones",
    established: 1960,
    logo: CowboysLogo,
    logoLight: CowboysLogo,
    name: "Cowboys",
    color: "#041E42",
    secondaryColor: "#b0b7bc",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 30,
    espnId: 24,
    fullName: "Los Angeles Chargers",
    code: "LAC",
    city: "Los Angeles",
    location: "Los Angeles, CA",
    coach: "Giff Smith (interim)",
    owner: "Alex Spanos and Family",
    established: 1960,
    logo: ChargersLogo,
    logoLight: ChargersLogo,
    name: "Chargers",
    color: "#0080C6",
    secondaryColor: "#ffc20e",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 31,
    espnId: 14,
    fullName: "Los Angeles Rams",
    code: "LAR",
    city: "Los Angeles",
    location: "Los Angeles, CA",
    coach: "Sean McVay",
    owner: "Stan Kroenke",
    established: 1937,
    logo: RamsLogo,
    logoLight: RamsLogo,
    name: "Rams",
    color: "#003594",
    secondaryColor: "#ffd100",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 32,
    espnId: 16,
    fullName: "Minnesota Vikings",
    code: "MIN",
    city: "Minneapolis",
    location: "Minneapolis, MN",
    coach: "Kevin O'Connell",
    owner: "Zygi Wilf",
    established: 1961,
    logo: VikingsLogo,
    logoLight: VikingsLogo,
    name: "Vikings",
    color: "#4f2683",
    secondaryColor: "#ffc62f",
    isAllStar: false,
    isActive: true,
  },
  {
    id: 34,
    espnId: 31,
    fullName: "AFC All-Stars",
    code: "AFC",
    city: "American Football Conference",
    location: "AFC",
    coach: "null",
    established: 1950,
    logo: AFCLogo,
    logoLight: AFCLogo,
    name: "AFC",
    color: "#D71920", // AFC red
    secondaryColor: "#002A5C",
    isAllStar: true,
    isActive: false,
  },

  {
    id: 33,
    espnId: 32,
    fullName: "NFC All-Stars",
    code: "NFC",
    city: "National Football Conference",
    location: "NFC",
    established: 1950,
    logo: NFCLogo,
    logoLight: NFCLogo,
    name: "NFC",
    color: "#013369", // NFC blue
    secondaryColor: "#A5ACAF",
    coach: "null",
    isAllStar: true,
    isActive: false,
  },
];

export const getNFLTeam = (id: number | string) =>
  nflTeams.find((t) => String(t.id) === String(id));

export function getNFLTeamLogo(
  id: string | number | undefined,
  isDark: boolean,
) {
  if (!id) return PlaceholderLogo; // fallback

  const searchStr = String(id).toLowerCase();

  const team = nflTeams.find((t) => {
    return (
      t.id === Number(id) || // match by ID
      (t.name && t.name.toLowerCase() === searchStr) || // match by name
      (t.code && t.code.toLowerCase() === searchStr) // match by code
    );
  });

  if (!team) return PlaceholderLogo;

  return isDark ? team.logoLight || team.logo : team.logo;
}

export const getTeamByESPNId = (espnId: number | string) => {
  return nflTeams.find((t) => t.espnId?.toString() === espnId?.toString());
};
