import { Colors, Fonts } from "constants/styles";
import { StyleSheet } from "react-native";

export const conferenceListModalStyles = (isDark: boolean) =>
  StyleSheet.create({
    backgroundStyle: {
      backgroundColor: "transparent",
      overflow: "hidden",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    handleStyle: {
      backgroundColor: "transparent",
      height: 40,
      justifyContent: "center",
      alignItems: "center",
      position: "absolute",
      left: 8,
      right: 8,
      top: 0,
    },
    handleIndicatorStyle: {
      backgroundColor: Colors.midTone,
      width: 36,
      height: 4,
      borderRadius: 2,
      zIndex: 9999,
      marginBottom: 4,
    },
    blurContainer: {
      flex: 1,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      overflow: "hidden",
      paddingHorizontal: 16,
      paddingTop: 60,
    },
    scrollContent: {
      paddingBottom: 40,
    },
    header: {
      position: "absolute",
      width: "100%",
      top: 0,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: isDark ? Colors.darkGray : Colors.lightGray,
      paddingVertical: 12,
    },
    headerText: {
      textAlign: "center",
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      fontFamily: Fonts.OSBOLD,
      color: isDark ? Colors.white : Colors.black,
      fontSize: 18,
    },
    container: {
      flex: 1,
      overflow: "hidden",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    contentContainerStyle: { padding: 16, paddingTop: 60, paddingBottom: 80 },
    leagueButton: {
      paddingVertical: 12,
      backgroundColor: "transparent",
      borderBottomWidth: 1,
      borderBottomColor: isDark ? Colors.darkGray : Colors.midTone,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    leagueText: {
      color: isDark ? Colors.dark.text : Colors.light.text,
      fontSize: 18,
      fontFamily: Fonts.OSREGULAR,
    },
    leftContent: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    logo: {
      width: 28,
      height: 28,
      marginRight: 12,
    },
    logoPlaceholder: {
      width: 28,
      height: 28,
      marginRight: 12,
      alignItems: "center",
      justifyContent: "center",
    },
  });
