import { StyleSheet } from "react-native";
import { Colors, Fonts } from "constants/Styles";
// Styles
export const playByPlayFieldStyles = (isDark: boolean) =>
  StyleSheet.create({
    wrapper: {
      borderColor: Colors.midTone,
      borderWidth: 1,
      borderRadius: 8,
      overflow: "hidden",
      padding: 12,
    },
    lastPlayTextContainer: {
      borderColor: Colors.midTone,
      borderBottomWidth: 1,
      paddingBottom: 12,
    },
    playerContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginRight: 12,
    },
    headshot: {
      width: 40,
      height: 40,
      borderRadius: 100,
      marginRight: 6,
      borderColor: isDark ? Colors.white : Colors.black,
      borderWidth: 0.5,
      paddingTop: 4,
    },
    name: {
      fontFamily: Fonts.OSREGULAR,
      fontSize: 16,
      color: isDark ? Colors.white : Colors.black,
    },
    posistion: {
      fontFamily: Fonts.OSREGULAR,
      fontSize: 14,
      color: isDark ? Colors.lightGray : Colors.darkGray,
      marginLeft: 4,
    },
    number: {
      fontFamily: Fonts.OSREGULAR,
      fontSize: 14,
      color: isDark ? Colors.lightGray : Colors.darkGray,
      marginLeft: 2,
    },
    driveDescription: {
      fontFamily: Fonts.OSREGULAR,
      fontSize: 12,
      marginTop: 4,
      color: isDark ? Colors.lightGray : Colors.darkGray,
    },
    fieldContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      borderWidth: 2,
      borderColor: isDark ? Colors.white : Colors.black,
      borderRadius: 4,
      marginTop: 40,
    },
    endzone: {
      width: 40,
      height: 200,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    fieldStripe: {
      position: "absolute",
      top: 0,
      bottom: 0,
      width: "10%",
      zIndex: 0,
    },
    glowOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 4,
      zIndex: 5,
    },
    endzoneLogo: {
      width: 100,
      height: 100,
      resizeMode: "contain",
      position: "absolute",
      opacity: 0.4,
    },
    endzoneHighlight: { shadowOpacity: 0.9, shadowRadius: 15, elevation: 10 },
    field: {
      flex: 1,
      height: 200,
      backgroundColor: isDark ? Colors.black : Colors.white,
      position: "relative",
    },
    marker: {
      position: "absolute",
      top: 0,
      width: 2,
      height: "100%",
      borderRadius: 2,
      zIndex: 1,
    },
    yardLine: {
      position: "absolute",
      top: 0,
      height: "100%",
      backgroundColor: isDark ? Colors.white : Colors.black,
      borderRadius: 1,
      zIndex: 1,
    },
    yardNumber: {
      position: "absolute",
      top: -22,
      fontSize: 12,
      fontFamily: Fonts.OSBOLD,
      color: isDark ? Colors.white : "#1d1d1d",
      textAlign: "center",
      zIndex: 3,
      width: 20,
    },
    scoreOverlay: {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: [{ translateX: -125 }, { translateY: -20 }],
      alignItems: "center",
      justifyContent: "center",
      zIndex: 5,
    },
    touchdownAnimation: { flexDirection: "row", alignItems: "center" },
    scoreLogo: { width: 40, height: 40, resizeMode: "contain", marginRight: 8 },
    scoreText: {
      fontFamily: Fonts.OSBOLD,
      fontSize: 20,
      textAlign: "center",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 5,
      color: isDark ? Colors.white : Colors.black,
    },
    firstDownMarker: {
      position: "absolute",
      top: 0,
      width: 2,
      height: "100%",
      zIndex: 2,
      borderRadius: 1,
      backgroundColor: isDark ? Colors.dark.yellow : Colors.light.yellow,
    },
  });
